### ISSUE TITLE
Background Shader is overly bright

### ISSUE THREAD

**Issue by zauberparacelsus** [armory3d/armory#100]
I used a image as an Environment Texture in the world shader, and found two problems: it was much much brighter compared to what rendered in cycles, and it was also much less saturated.  For the image in question, I used versions of it in the .jpeg and .hdr formats, without any luck.

Image 1: Render from Cycles, with Background node's Strength set to 2.0
![backgroundrender_cycles](https://cloud.githubusercontent.com/assets/548168/21559423/0aefa008-ce1a-11e6-9ec9-e3d60c8fa192.jpg)

Image 1: Screenshot from Armory, with Background node's Strength set to 1.0
![backgroundrender_armory](https://cloud.githubusercontent.com/assets/548168/21559424/0e92d202-ce1a-11e6-821b-30dbd119e0de.jpg)

The following .zip file contains an example scene that displays this problem.
[test2.blend.zip](https://github.com/armory3d/armory/files/678221/test2.blend.zip)

_Footnote 1:_ I attempted to correct the brightness problem by using the following nodes: Bright/Contrast, Gamma, Hue/Saturation, and MixRGB.  In all cases, the world shader instead gave a gray background, so I am guessing that Armory doesn't know how to handle those nodes in the world shader.

_Footnote 2:_ I have no idea why the view in armory is so much wider in comparison to the cycles render.

**Comment by bibleuspro** [comment]
I will add that when I built for windows, and then built a release and debug of the "animation.sln" (don't know why it built to that, as I was in scene3.arm) the camera viewport seemed further away and at different xyz or something.
![image](https://cloud.githubusercontent.com/assets/19825051/21562181/f0baeafc-ce33-11e6-914d-8b35ef33ca4e.png)
I will be making a separate issue about https://developer.blender.org/T47464 this problem, diagonal line going across monitor top left to top right, over the view of armory blender player. This issue, (it is hard to tell from the new angle on release build but it) seems diminished although still there. using latest NVidia driver 376.33 I will note, my previous NVidia driver also had issue in that the gui of blender ran crazy slow, upgrading to the above driver build fixed that issue but may have opened new can of worms here. I will add that I have tried telling my NVidia control panel to use my built in intel hd instead of the NVidia 970m (laptop) and no difference still diagonal line, and still xyz off (the main issue here, just combining in case related)
http://steamcommunity.com/app/365670/discussions/0/154642447926384520/

**Comment by luboslenco** [comment]
Background brightness should match better now. Still working on

- World nodes shader generator
- Light calibration
- Camera view fix

![lcal](https://cloud.githubusercontent.com/assets/3685704/21948495/f8e22cb8-d9eb-11e6-959d-a06ed2118896.jpg)

**Comment by zauberparacelsus** [comment]
Under build 10, this issue has returned in reverse: now the background is overly dark.

**Comment by luboslenco** [comment]
With properties and tool shelf panels closed, viewport camera should now match perfectly.
