### ISSUE TITLE
Diagonal Screen Tearing in Blender Armory Player

### ISSUE THREAD

**Issue by bibleuspro** [armory3d/armory#101]
this problem, diagonal line going across monitor top left to top right, over the view of armory blender player.  using latest NVidia driver 376.33 
https://developer.blender.org/T47464 

I will note, my previous NVidia driver also had issue in that the gui of blender ran crazy slow, upgrading to the above driver build fixed that issue but may have opened new can of worms here. 

I will add that I have tried telling my NVidia control panel to use my built in intel hd instead of the NVidia 970m (laptop) and no difference still diagonal line
![20161230_021932](https://cloud.githubusercontent.com/assets/19825051/21562545/ecc305b2-ce36-11e6-9a6b-95bfdc45d5a1.jpg)

![20161230_021912](https://cloud.githubusercontent.com/assets/19825051/21562551/f52d2174-ce36-11e6-879d-5ada5165355c.jpg)

![image](https://cloud.githubusercontent.com/assets/19825051/21562602/5d993ca2-ce37-11e6-8475-b3c5afd72c5a.png)

**Comment by marcclintdion** [comment]
@luboslenco I can have a look at this if you like.  My graphics system is similar(GTX 965M) with driver version 375.95 WHQL
I have a fair amount of experience with finding sources of shader/rendering errors.  I don't have the Armory SDK.  I just finished reading your docs so I guess now is a good time to volunteer. :)

**Comment by marcclintdion** [comment]
After a bit of digging I fairly certain this has nothing to do with Blender or Armory.  There are oodles of people complaining about this on various threads going back to about 1 year ago and it affects a whole lot of commercial big-budget software.

One person reports that using DDU(Display Driver Uninstaller) worked.  You'll want to run this after booting Windows into Safemode.  It will do it's best to remove any traces of old driver settings to prevent conflicts.  Here's a link http://www.guru3d.com/files-details/display-driver-uninstaller-download.html
  
Another solution that  is reported to work is to set V-Sync to Adaptive using the nVidia Control Panel, however, others are reporting that this does not work.  I'd try all the V-Sync options to be sure.    I guess I got lucky here, my screen uses G-Sync which seems to be problem free.

I see one interesting solution that's been reported.  It says to max out your visual quality settings using AA and DSR(Dynamic Super Resolution) to slow your GPU down.  The idea being that these cards are too fast and need to be throttled back.    

Another person reports that using an extension to force the use of Flash instead of HTML5 does it but I'm not sure that's applicable here and sounds like a poo-do solution to me.

Does this happen immediately or does it take a while before it begins to happen?  It could be a heating issue.  Perhaps there is a Fan Control utility that you can find.  Notebook Fan Control perhaps.

While we're on the topic.  You may want to disable Windows Graphics features using Control Panel>System>Advanced System Settings>Performance. to free up some extra GPU memory for Cycles if you are doing any rendering.  I always disable most of those settings just to help make sure that the OS graphics system (DirectX or Aero or whatever) is not going to conflict with OpenGL.  

![screenshot 8](https://cloud.githubusercontent.com/assets/5705667/21580015/8c0ec010-cf87-11e6-9e71-5bf5480fe300.png)

Well, good luck.  I'm sorry this is happening to you and others.

**Comment by bibleuspro** [comment]
thanks for the reply.

to answer your question. it does happen right away.

I tried the v-sync and a few other settings in there, no luck.

I can plugin an external hdmi monitor to my Alienware laptop, and it goes away on external monitor. nothing fancy about the external monitor...cheap dell one. nice to hear that g-sync clears it up.

If I can ask about your hardware that would be good to know. Are you on alienware? It seems you are on a laptop of some sort with the m class to your card?

There is a separate issue about camera matrix on CPP builds and Krom, that I will need to do a issue for. I mention there that the problem seems to be reduced, but the camera is so far off it is hard to tell if it is gone. If it is gone in release build of projects I won't have as much concern about this. But if it is still there on release builds, and happens to a wide range of laptops, I think it will be important to flush out to maintain a AAA target audience which I think this engine can hit. For example, Unity, UE4, Stingray, Lumberyard, CryEngine all don't have this issue. So though it may be traced to a driver or manufacturer problem, I would argue it is important not to just forget that audience. It can be put on back burner or put into deep testing, but not say o well. Keep trying is all I suggest, and I will.

**Comment by marcclintdion** [comment]
The machine I'm using is an Asus G752VL

**Comment by luboslenco** [comment]
@marcclintdion Wow, thanks for investigation :)

@bibleuspro I guess this is still issue with Build 8? Is it still happening when you select Browser as a runtime?

**Comment by marcclintdion** [comment]
@luboslenco: no problem :)
---------------------------------------------------------------------------------------------------------

On the very last page of a 25 page long  nVidia forum thread, someone posts a program that is suppose to hook into the running game and adjusts how the code syncs with the screen.  The GitHub page mentions that this problem affects both DirectX and OpenGL but no obvious mention is made of a solution for OpenGL.  Maybe the DirectX solution can be ported...

Here is the nVidia forum thread:    

 https://forums.geforce.com/default/topic/903422/geforce-mobile-gpus/diagonal-screen-tearing-issues-on-gtx-860m-870m-960m-965m-970m-980m-/25/

---------------------------------------------------------------------------------------------------------

Here is the GitHub code. 
https://github.com/Dwedit/NvidiaOptimusFixer

---------------------------------------------------------------------------------------------------------

The following code was mentioned a bit earlier in the thread as a fix.    I think it was mentioned that this goes after all the drawing, ie: after SwapBuffers or something analogous.  I'm confused by this, to me it looks like this should destroy the graphics context but I don't know OS/Graphics interaction code well at all. 

HDC dc = GetDC(NULL);
GetPixel(dc, 0, 0);
ReleaseDC(NULL, dc);

---------------------------------------------------------------------------------------------------------

**Comment by adriansnetlis** [comment]
I am confirming diagonal screen tearing. Also it happens in BF Blender and UPBGE, too. So I think it's a Blender issue. This is not a problem on Linux, though, only happens on Windows.
