### ISSUE TITLE
Scene 4 crashes to desktop.

### ISSUE THREAD

**Issue by ja-moli** [armory3d/armory#113]
So today I have tried to follow scene 4 from the manual 
http://armory3d.org/manual/getting_started/scene4.html

and when going to render Armory crashes to desktop.
Before doing more changes and repeating the entire tutorial several times I just downloaded scene 4 .blend file from here
https://github.com/armory3d/armory_examples/tree/master/scene4

and tried it.

It crashed to desktop. 
It crashes to desktop when I try to render from viewport, when I try to render to a new screen (f5) it just open and closes inmediately. 

Heres what cmd says to me when I try it from CMD

![error scene 4](https://cloud.githubusercontent.com/assets/12383027/21957743/30d09b34-da9e-11e6-848b-6ea96722e097.jpg)

Since it says something about loading error I repeated opening Armory as administrator. 
Same Issue.

Is very similar to the one with animation I posted at the forum.
---
optional - drag & drop .blend file here

**Comment by luboslenco** [comment]
Heyo, thanks for report.

Can you paste full console output? Is this using Build 6 (version 17.01)?

**Comment by ja-moli** [comment]
Version 6, yep

![part 1](https://cloud.githubusercontent.com/assets/12383027/21958087/59772402-daa5-11e6-88b1-777cedbf1c87.jpg)


![part 2](https://cloud.githubusercontent.com/assets/12383027/21958089/5ea86ac6-daa5-11e6-88cf-16b4531b486a.jpg)

**Comment by ja-moli** [comment]
I installed version 5 and give it a try. 
It gives this error. 

![also](https://cloud.githubusercontent.com/assets/12383027/21958134/99eca5ce-daa6-11e6-9398-8d137929d3b9.jpg)

**Comment by ja-moli** [comment]
About the last one. I discovered a 'build' folder in my desktop. I didn't know what was. I deleted it. If Armory needed that, is a way to force Armory to create it again? I have deleted and installed Armory v5 and v6 a couple times to make the test, but the folder didn't returned.

**Comment by luboslenco** [comment]
It is safe to delete build folder - it is placed alongside the .blend file when you hit play, basically the build output & compiled files.

The error from Build 5 was fixed, that's why I was curious about the version, so we have something new here:)

- Can you locate file *Armory/armsdk/armory/tools/cmft/cmft.exe*? This binary is responsible for creating the radiance files that appears to be missing. Could anything block this file?
- In the folder with your scene4.blend file, can you locate *build/compiled/Assets/envmaps/envmap_radiance_0.hdr*? The file will likely be missing.
- In Blender, press *Properties - Armory Build - Clean - Clean Project*. Run the project now and please paste the console output again. This way we can see if the *cmft.exe* binary is executed - there should be 'CMFT Info' messages printed.

Hope it's not too much annoyance!

**Comment by ja-moli** [comment]
I founded the cmft.exe  is there. I'm on windows 10. I don't know if I must se this in some 'compatibility mode' but I have not touched anything in advanced options/permissons.

in build/compiled/Assets/envmaps/ there is no file. Is empty.

I did the cleaning. It provoked my entire screen go white and blender to crash. I stopped blender and saved the output.

![1](https://cloud.githubusercontent.com/assets/12383027/21959146/eb2ebb6c-dabe-11e6-8005-26b664dc697a.jpg)

![2](https://cloud.githubusercontent.com/assets/12383027/21959148/ef77018e-dabe-11e6-9385-43eadf07bb3b.jpg)

**Comment by luboslenco** [comment]
Aha, nice catch! So the problem seems to be that *cmft.exe* binary is crashing the gpu driver while processing the envmap. That would explain the white screen & crash & missing radiance files.

- There is a newer version of cmft but I did not make it the default yet. Can you try to rename *Armory/armsdk/armory/tools/cmft/cmft_new.exe* to *cmft.exe* (move the current *cmft.exe* out or just delete it).
- Don't forget to clean to project before running.
- Maybe updating the gpu driver is worth a try?
- I will add a check box to Armory to process envmaps using cpu only, slower but will atleast make it possible to work in case of crash.

Let me know if any of that helps.

**Comment by ja-moli** [comment]
Renaming the cmtf exe worked!
It now renders.

**Comment by luboslenco** [comment]
Yes! I will switch to *cmft_new.exe* by default then. Will still add an option for cpu-only processing, just in case. And will also add a check if the radiance files were properly generated, to generate a proper error message next time.

**Comment by luboslenco** [comment]
New cmft.exe binary is now default in Build 7. In case of issues there is also option to disable gpu from processing textures: Armory Player - Advanced - GPU Processing.
