### ISSUE TITLE
Weirdness with rot

### ISSUE THREAD

**Issue by trsh** [armory3d/armory#1221]
[untitled.zip](https://github.com/armory3d/armory/files/2974896/untitled.zip)

Expected: model resets x axis to zero
Actual: i don't know hat is that

Ubuntu bionic, sdk utd, arm 0.6

**Comment by Bugsbane** [comment]
I think the issue here is that Blender, and thus Armory, natively does rotations in quaternions, that is a type of vector separated out into *four* numbers, rather than just a 3 number vector3. You can see this if you print the rotation value and look in the console. Thus, when you run the rotation through a "Separate XYZ" node, I suspect that you're giving it data in a format that it doesn't expect (ie a four part quaternion, instead of a 3 part vector3). Data is then missing when you go to set the rotation afterwards.

Now, personally I think a strong case could be made for not having quaternions be used at all in logic node setups, however there are technical benefits to them, so I would suggest that at the very least, a warning be displayed (even if just in the console) when a node gets data of a type that it's input isn't expecting (such as a quaternion into a vector 3 input).

This way, if I'm right about the problem, users would at least be warned and could look into finding their own solutions, without being confused by what the problem is.

**Comment by trsh** [comment]
Actually nodes use get/set Euler what is exactly XYZ v3

**Comment by Bugsbane** [comment]
Interesting... looking at the source code for the "Get Rotation" node it uses return object.transform.rot.getEuler();

It's weird though because attaching a print command to that, outputs four numbers... ¯\_(ツ)_/¯

If the problem isn't what I wrote above, then maybe you're just running into the infamous issue #512  ...

**Comment by trsh** [comment]
Maybe. So bugs are linked now. More info and samples for fixing, great.
I have 0 idea why getEuler returns vec4 instead of vec3, as 4th param is always default `return new Vec4(pitch, roll, yaw);`  ¯\(ツ)/¯

**Comment by zicklag** [comment]
> It's weird though because attaching a print command to that, outputs four numbers... ¯\(ツ)/¯ -- @Bugsbane 

> I have 0 idea why getEuler returns vec4 instead of vec3, as 4th param is always default return new Vec4(pitch, roll, yaw); ¯(ツ)/¯ -- @trsh 

The reason that it uses Vec4 for even 3 dimensional values has to do with the fact that it makes the 3D vector and matrix math simpler.

See [OpenGL Tutorial 3: Matrices -- Homogeneous coordinates](http://www.opengl-tutorial.org/beginners-tutorials/tutorial-3-matrices/#homogeneous-coordinates).

**Comment by Bugsbane** [comment]
@zicklag So are all four of the values actually used to determine the rotation, or are the first three enough?

**Comment by zicklag** [comment]
The fourth number should be 1 or 0 ( I think 0, but it might not matter ) and it **does not** effect the rotation. If you are dealing with rotations in Logic Nodes, excluding the logic pack which *does* have some Quaternions which are 4 dimensional, all of the rotation values are in Eulers which are 3 dimensional.

I think `Vec4`'s are used pretty much everywhere that you need a 3 or 4 dimensional value. `Vec3`'s are almost [never used](https://github.com/armory3d/iron/search?q=vec3&unscoped_q=vec3) it looks like.

**Comment by luboslenco** [comment]
Linking with the infamous https://github.com/armory3d/armory/issues/512.
