### ISSUE TITLE
Baked F-Curves don't work

### ISSUE THREAD

**Issue by blackno666** [armory3d/armory#1254]
Baked F-Curves for animations don't work.

Create a simple animation: works
Bake F-Curve: won't work

Here's a workflow to reproduce the issue:
![out](https://user-images.githubusercontent.com/47137964/56166711-96d9b180-5fd6-11e9-8fa9-9e299dc4beb6.gif)

This is a pitty since the modifiers and interpolation modes (like elastic our bounce) for F-curves can be used to easily create complex animations.

**Comment by MoritzBrueckner** [comment]
@luboslenco Is there a border case where sampled animations can't be converted to keyframes? If not, why not convert them in `export.py`? For an addon of mine, I did exactly that and it worked.

If you want I can try that out, this would also simplify the code as the distinction between keyframes and sampled data would not be required anymore.

**Comment by luboslenco** [comment]
@MoritzBrueckner if I recall correctly it's from the older days when only sampled animation worked - removing / simplifying code always welcome!

**Comment by MoritzBrueckner** [comment]
So I finally got time for this and it works now, I've even implemented a per-keyframe interpolation like in Blender :) Only the bone animations use the old system as I didn't really understand the way their transformations work. There are a lot of unnamed and uncommented matrices in the code and its very hard to understand what's happening there, but I'm not that into matrix math anyway. But it works and thats important.

The problem is that FCurve modifiers are not included in the animations, as their ouput is neither sampled nor consists of keyframes (modifiers must be baked first). So my idea now is to use the `evaluate(frame)` method of the FCurve class to export each frame (we would then just use this method for everything and export a value per frame, like sampled data). This would require a little bit more storage for the game but saves a very little bit of performance as well. Also, every possible interpolation would be supported that way without implementing them in armory too.

So, before opening a PR: whats your opinion on that, @luboslenco?

**Comment by luboslenco** [comment]
> So my idea now is to use the evaluate(frame) method of the FCurve class to export each frame (we would then just use this method for everything and export a value per frame, like sampled data). This would require a little bit more storage for the game but saves a very little bit of performance as well. Also, every possible interpolation would be supported that way without implementing them in armory too.

Sounds pretty good to me. Thanks for working on that!
