### ISSUE TITLE
Accessing objects in a script

### ISSUE THREAD

**Issue by sh-dave** [armory3d/armory#127]
Is there a way to get notified when an object (including children) is fully loaded in a script?
I tried to use notifyOnInit(), but it seem that does get called too early. At the moment i use notifyOnUpdate() and query (object.getChild('something')) until i find all children. In a KS html5 build i have ~10 frames until all children are loaded, in an exported html5 it's even as much as ~60.

(still using Preview 6 build)

**Comment by luboslenco** [comment]
Unable to verify now but one way could be to use `Scene.active.notifyOnInit()` instead. This should get called once all the scene objects are ready.

Otherwise `trait.notifyOnInit()` is called as soon as the object itself is ready, not necessarily it's children since object creation is asynchronous - to make streaming new objects possible.
