### ISSUE TITLE
HDR Is not uniform

### ISSUE THREAD

**Issue by TylerMcKenzie** [armory3d/armory#1277]
### SHORT DESCRIPTION:
HDR is not uniformly mapped to scene. 

### EXPECTED RESULT:
HDR is uniform

### ACTUAL RESULT:
My HDR is lemon.

### HDR
![hdr_weirdness](https://user-images.githubusercontent.com/15006338/58073642-c2693200-7b68-11e9-8ce3-9bebf16b6aca.png)

### Nodes
![nodes](https://user-images.githubusercontent.com/15006338/58073710-f0e70d00-7b68-11e9-9b7e-31ae3e60b4ca.png)

**Comment by BlackGoku36** [comment]
Looks like the hdr produce by cmft is at fault
https://forums.armory3d.org/t/equirectangular-world-texture/3801/5?u=blackgoku36
(Left is original, right is generate by cmft)
<img width="1440" alt="Screen Shot 2020-01-03 at 2 02 58 PM" src="https://user-images.githubusercontent.com/36535717/71762938-03e1fe00-2efc-11ea-9435-2ec88d46df77.png">
<img width="1440" alt="Screen Shot 2020-01-03 at 2 02 32 PM" src="https://user-images.githubusercontent.com/36535717/71762940-05abc180-2efc-11ea-91e3-ae2046c0f192.png">

**Comment by MoritzBrueckner** [comment]
Hi, I'm currently revisiting this topic for the implementation of the nishita sky model for the upcoming Blender 2.9 support. I believe that this issue is not caused by cmft, but instead by the geometry of the skydome itself, which seems to be a "sphere" with a rather flat lower half.

You can see that the same distortion happens on non-environment-map backgrounds too, the sun should be completely round in the following screenshot:

![nishita_sun_distorted](https://user-images.githubusercontent.com/17685000/108608348-b8700500-73c6-11eb-8771-d0e13340338f.jpg)

This is the world geometry displayed in RenderDoc:

![skydome_geometry](https://user-images.githubusercontent.com/17685000/108608495-83b07d80-73c7-11eb-8b8f-88d1e5b81d10.jpg)


@luboslenco is there a reason for this? Do you remember how the vertex coordinates in [`ConstData.hx`](https://github.com/armory3d/iron/blob/de3c4ce777199706c15eda90314f221353852082/Sources/iron/data/ConstData.hx#L125-L127) were generated? Of course, in many cases you don't see the bottom of the world but sometimes you do. The distortion is even visible a bit above the horizon.

**Comment by BlackGoku36** [comment]
I still think there is issue with cmft, mine show issues happen horizontally. How does cmft output appear in build file? We could just use cube or simple sphere primitive that blender make and set skydome to appear last setting depth to 1 in vertex shader (this is how most people do). If i remember correctlly what armory do is adjust skydome size based on camera's far plane.

**Comment by MoritzBrueckner** [comment]
It's possible that there is also a cmft issue (your screenshots indeed look like that), but this particular lemon-like distortion you can also see in the first post is very likely not related to cmft as you can see the same effect in different kinds of world shaders (sun example is above, [here](https://github.com/armory3d/armory/pull/1924) is another screenshot where you can see that the geometry is problematic). Normals are distorted by the non-sphere geometry and I guess that they even are distorted a tiny bit above the horizon due to interpolation between vertices. The texture coordinates for environment maps are actually calculated based on the world normals ([source](https://github.com/armory3d/armory/blob/f99ff0576d2d81c5ec8231c399f0f488c49c8c22/blender/arm/material/cycles_nodes/nodes_texture.py#L455)).

Cmft is only used for radiance and irradiance map generation as far as I know.

A simple sphere (icosphere maybe?) primitive would likely be the best solution. A cube is helpful for cubemaps and it has less geometry (which is neglible I guess), but with a unit sphere we have `normals = position = direction` which is absolutely helpful for sky shaders.

I'm not sure about the skydome size, but I guess that it doesn't matter because we don't even write its depth to the depth buffer ([source](https://github.com/armory3d/armory/blob/f99ff0576d2d81c5ec8231c399f0f488c49c8c22/blender/arm/make_world.py#L41)). But drawing it last with depth 1 might indeed be a good idea to have less pixels drawn due to depth testing (@luboslenco what do you think about that?), there is even a problem with the current approach when it comes to SSR (screen space reflections), the world is not visible in the reflection).

**Comment by luboslenco** [comment]
@MoritzBrueckner hm don't recall the ConstData vertices generation, the regular sphere you suggested sounds much better.
