### ISSUE TITLE
Limiting the amount of spot light on scene

### ISSUE THREAD

**Issue by VeniGogniti** [armory3d/armory#1289]
### SHORT DESCRIPTION:
In scene I have more than 4 spot light but when I press play only 4 of them are visible, others not. After switching off one of the lights, the next ones are switched on during play.
[NearDay.zip](https://github.com/armory3d/armory/files/3257367/NearDay.zip)

Armory: 06 win64
Operating system: win 7
Graphics card & driver: Radeon RX580

**Comment by indokan1945** [comment]
AFAIK it was intended to be maxed at 4. You can change the max size manually by changing the size of maxLights and maxLightsCluster in LightObject.hx, but it will slow down the rendering as the looping mechanism of lights is still need to be fixed.

**Comment by luboslenco** [comment]
IIRC the main pain is handling the shadow maps and all the light types. The cap is set to 16 lights total and 4 lights per cluster. The view is divided into 16x16x16 clusters.

Haxe part:
https://github.com/armory3d/iron/blob/master/Sources/iron/object/LightObject.hx#L30

Shader part:
https://github.com/armory3d/armory/blob/master/Shaders/std/clusters.glsl#L2

A good start could be to simplify uniforms passing:
https://github.com/armory3d/armory/blob/master/Shaders/std/light.glsl#L33

```glsl
// Instead of
uniform mat4 LWVPSpot0;
uniform mat4 LWVPSpot1;
uniform mat4 LWVPSpot2;
uniform mat4 LWVPSpot3;

// Do
uniform mat4 LWVPSpot[maxLightsCluster];
```

Passing array of mat4 uniforms should nowadays work in Kha.

```glsl
// Instead of
if (index == 0) {
	vec4 lPos = LWVPSpot0 * vec4(p + n * bias * 10, 1.0);
	direct *= shadowTest(shadowMapSpot[0], lPos.xyz / lPos.w, bias);
}
else if (index == 1) {
	vec4 lPos = LWVPSpot1 * vec4(p + n * bias * 10, 1.0);
	direct *= shadowTest(shadowMapSpot[1], lPos.xyz / lPos.w, bias);
}

// Do?
vec4 lPos = LWVPSpot[index] * vec4(p + n * bias * 10, 1.0);
direct *= shadowTest(shadowMapSpot[index], lPos.xyz / lPos.w, bias);
```
The problem is the above will cause trouble with WebGL. Alternative solution is to bake shadow maps into single atlas.

Here is where light matrices are bound:
https://github.com/armory3d/iron/blob/master/Sources/iron/object/Uniforms.hx#L785

Here is where shadow maps are bound:
https://github.com/armory3d/armory/blob/master/Sources/armory/renderpath/Inc.hx#L42

If that gets resolved we can investigate raising `maxLights` and `maxLightsCluster`.

**Comment by N8n5h** [comment]
I gave it a go and tried to simplify the uniform passing and here is [my progress so far](https://github.com/N8n5h/armory/tree/light-fix), I think the uniform part works in Krom at least, but I think I have a problem with `index`, 
i.e., if I change this part from `light.glsl`:
```glsl
if (index == 0) direct *= PCFCube(shadowMapPoint[0], ld, -l, bias, lightProj, n);
else if (index == 1) direct *= PCFCube(shadowMapPoint[1], ld, -l, bias, lightProj, n);
else if (index == 2) direct *= PCFCube(shadowMapPoint[2], ld, -l, bias, lightProj, n);
else if (index == 3) direct *= PCFCube(shadowMapPoint[3], ld, -l, bias, lightProj, n);
```
to simply
```glsl
direct *= PCFCube(shadowMapPoint[index], ld, -l, bias, lightProj, n);
```
then shadows stop working in my simple scene with 4 point lights. I don't understand much of how `index` is calculated, so my question is: can index go outside the array range?

```glsl
int li = int(texelFetch(clustersData, ivec2(clusterI, i + 1), 0).r * 255);
```

> The problem is the above will cause trouble with WebGL

Can you elaborate on this?

> Alternative solution is to bake shadow maps into single atlas.

Have you eyed any implementation/presentation in particular?

@luboslenco

**Comment by luboslenco** [comment]
> can index go outside the array range?

It should never get higher than `maxLightsCluster` - 1, and `maxLightsCluster` is defined to 4.

I am not sure the `"name": "LWVPSpot[0]", "link": "_biasLightWorldViewProjectionMatrixSpot0"` can work? It might need to be done via `setFloats` instead.

Example on how array of vectors is passed:
https://github.com/armory3d/armory/blob/master/Shaders/deferred_light/deferred_light.frag.glsl#L39
https://github.com/armory3d/armory/blob/master/Shaders/deferred_light/deferred_light.json#L32
https://github.com/armory3d/iron/blob/master/Sources/iron/object/Uniforms.hx#L640
> >The problem is the above will cause trouble with WebGL

>Can you elaborate on this?

Dynamic array index was not allowed in WebGL. Maybe this is no longer the case for WebGL2?
https://stackoverflow.com/questions/30585265/what-can-i-use-as-an-array-index-in-glsl-in-webgl

> >Alternative solution is to bake shadow maps into single atlas.

>Have you eyed any implementation/presentation in particular?

I recall reading about it in the presentation below (in the lighting section), unfortunately  it's not very detailed.
http://advances.realtimerendering.com/s2016/Siggraph2016_idTech6.pptx
http://advances.realtimerendering.com/s2016/Siggraph2016_idTech6.pdf

**Comment by N8n5h** [comment]
>  can index go outside the array range?

> It should never get higher than maxLightsCluster - 1, and maxLightsCluster is defined to 4.

Ok, maybe it has something to do with this https://stackoverflow.com/a/60110986

> I am not sure the "name": "LWVPSpot[0]", "link": "_biasLightWorldViewProjectionMatrixSpot0" can work? It might need to be done via setFloats instead.

According to [this answer](https://stackoverflow.com/questions/22336213/writing-values-to-a-glsl-uniform-array-element-with-offset) and some of my tests it seems to be working, at least on Krom. 
I've avoided `setFloats` because of having to write that array, I thought that maybe with the offset I could get past the extra loop when passing the values.

> The problem is the above will cause trouble with WebGL

> Can you elaborate on this?

> Dynamic array index was not allowed in WebGL. Maybe this is no longer the case for WebGL2?
> https://stackoverflow.com/questions/30585265/what-can-i-use-as-an-array-index-in-glsl-in-webgl

Ok, if the if/else if branching doesn't cause much performance difference than dynamic indexing, then it's possible to go in that route with the uniform setting with offset, right? What do you think?

I will also still be looking towards implementing shadowmap atlases, but it will take me some time since I'm still figuring out how that part of the rendering works in the engine.

**Comment by N8n5h** [comment]
Update: I got some free time again so I decided to continue with this. 

I'm currently trying move the spot lights wvp matrices to a more "dynamic" solution so it's no longer constrained to just 4, 
> I am not sure the "name": "LWVPSpot[0]", "link": "_biasLightWorldViewProjectionMatrixSpot0" can work? It might need to be done via setFloats instead.

so I gave this a go to try to do it with a setFloats approach, and this is my progress so far https://github.com/N8n5h/armory/tree/light-fix-setfloats, https://github.com/N8n5h/iron/tree/light-fix-setfloats
I'm currently facing an issue that I'm not very sure why it's not working, but shadows stop working using the same logic but instead of an array of matrices bound via "LWVPSpot[0]" using a setfloats approach is not working. I managed to get renderDoc to work and I could check that the uniform is passed correctly and all the values are the same in both cases, so unless there is some typo that I didn't manage to catch, I'm not sure what's going on. Do you have any idea if setfloats uniforms are treated differently @luboslenco 

This is my test file, I included renderDoc captures for both cases.
[lights_tests.zip](https://github.com/armory3d/armory/files/5498254/lights_tests.zip)


If no solution rises up I will alternatively try to advance my original approach to make it more dynamic. The problem I face is that I'm not sure where the "dynamism" should be. Should the `deferred_light.json` file be parsed in python and then write dynamically a version with all the uniforms, or should it be done in iron... what do you think? @luboslenco

**Comment by N8n5h** [comment]
Progress update: I managed to get RenderDoc to confirm that the atlasing solution for shadow maps I wrote is working 

![image](https://user-images.githubusercontent.com/42382648/98811791-2720e800-2400-11eb-9f37-b02e1d72f62c.png) 

So now I'm trying to find a way to utilize this atlas data in the shader...

I'm "following" along this tutorial which helped me writing some parts of the solution
https://catlikecoding.com/unity/tutorials/scriptable-render-pipeline/spotlight-shadows/

**Comment by N8n5h** [comment]
### Progress update: 

I managed to finally get the deferred/light/shadow shaders to work with an atlas instead of an array of shadowmaps for spot lights... 

![image](https://user-images.githubusercontent.com/42382648/99666557-e6515080-2a49-11eb-8c49-cde75afd2168.png)

Now that I got that to work I will move to implement support for some of the trickier ones, directional lights (sun) which already has some sort of atlasing for cascading so I have to take that into account, and point lights, which have a lot of images per light so it may need to be approached differently https://www.gamedev.net/forums/topic/684019-point-light-shadows-in-shadow-atlas/ 

From there I still need to work 
* in the current limitation of 4 light matrices to be sent to the deferred shader
* optimize the algorithm that I wrote for managing atlases which currently uses recursion in a lot of places.
* cover corner cases such as, what happens to the atlas if you remove lights?
* investigate how to make it work for forward

and then finally investigate the "in-fighting" between different lights shaders.

**Comment by N8n5h** [comment]
### Progress Update: 

I finally found out what was wrong with my float array approach for spot lights matrices and managed to unlock the limit for those  with ease. So at last 16 spot lights using an atlas of 4096x4096:

![image](https://user-images.githubusercontent.com/42382648/100562377-52c61e00-329a-11eb-9bb5-634a1a9a1101.png)

I'm currently working into adding support for point lights, which can be tricky since it may require a move from cubemaps to a simple texture so it can be part of the atlas.
https://www.gamedev.net/forums/topic/687535-implementing-a-cube-map-lookup-function/

**Comment by N8n5h** [comment]
### Progress Update: 

I managed to add support for point lights in the atlas solution, by faking a cubemap lookup, so this is the result, 9 point lights in the same texture:
![Screenshot from 2020-12-10 17:34:00](https://user-images.githubusercontent.com/42382648/101827867-9547f000-3b0f-11eb-97a8-af3eec187f63.png)
There is still some things that I need to solve because it's has a few artifacts, mostly related to bias I think. The atlas is 8192x8192 without dynamic tile sizes, which could be very big for some targets, so I'm trying to add support for dual paraboloid shadow mapping as an alternative for those that really need to save space but want a considerable numbers of lights showing up with acceptable performance and don't mind the quality loss and probably some artifacts.

While I was testing around I also noticed an issue with the rendering, which from my tests I think it's related to the clustering algorithm, since I could reproduce it in "vanilla" armory.
![Screenshot from 2020-12-10 17:34:43](https://user-images.githubusercontent.com/42382648/101828352-2cad4300-3b10-11eb-804d-e94bd7c2d5a9.png)
The issue seems to appear when you are far enough with more than 2 point lights rendering (that's what I tested so far), the more the lights, the more noticeable the issue gets.

I will try to learn and understand how the clustering algorithm work to try to get this solved, but @luboslenco is this a known issue with the algorithm, or there is something else that you suspect could be causing it?

**Comment by luboslenco** [comment]
Super cool!

> The issue seems to appear when you are far enough with more than 2 point lights rendering (that's what I tested so far), the more the lights, the more noticeable the issue gets.

Not aware of that but likely issue with clustering like you mention - from what I gather it changes with camera movement?

**Comment by N8n5h** [comment]
> Super cool!

Thanks! :)

> Not aware of that but likely issue with clustering like you mention - from what I gather it changes with camera movement?

Yes, camera movement and distance. I noticed that the more lights are rendered the closer it appears and the more noticeable it gets

![ezgif-3-2e09ae723ab9](https://user-images.githubusercontent.com/42382648/101908286-9b36e300-3b9a-11eb-8044-0c6f617760f8.gif)

https://streamable.com/y17l2b

**Comment by N8n5h** [comment]
## Progress update:
I'm still trying to get this issue with clustering solved. In the mean time, I extended the support for the atlas for directional lights, 
![c](https://user-images.githubusercontent.com/42382648/103085648-121fa300-45c1-11eb-90c2-b3aafe4f17b6.png)

Original left | New right

Unfortunately I ran into some issue that makes the result of cascaded shadows a bit different compared to the original (it can be seen by clicking the image and zooming in). 
I'm not sure why bundling the shadow maps in a different way could cause such issue but I need to investigate it. 

Besides from that, the difference now is that it's trivial to have directional lights share an image with other type of lights.


@luboslenco with respect about the clustering implementation, I'm trying to piece together what [`updateClusters()`](https://github.com/armory3d/iron/blob/a2d8e4280ae5ad2e50f017a2dc6d5fa3cf61301e/Sources/iron/object/LightObject.hx#L339) does too see if the issue is there. I noticed some pieces of the equations that appear in the paper 
like [here](https://github.com/armory3d/iron/blob/a2d8e4280ae5ad2e50f017a2dc6d5fa3cf61301e/Sources/iron/object/LightObject.hx#L365), but I also noticed that `near` only appears in the calculations for the Z coordinate, do you remember why is that? 

Also do you remember where `distSliceX()` and `distSliceY()` came from?

![image](https://user-images.githubusercontent.com/42382648/103086231-d980c900-45c2-11eb-94ca-8fe8c7578e02.png)
![image](https://user-images.githubusercontent.com/42382648/103086769-32049600-45c4-11eb-87e8-5af9d0285c74.png)

**Comment by N8n5h** [comment]
### progress update:

It took longer than I expected, but after a lot of arduous debugging sessions I finally got LOD to work, or at least to not fail immediately within simple tests. It's still experimental though and probably needs more testing to make sure it's usable.

This is a comparison to show how much space is saved by just varying the subdivisions number in the same scene:

![no_lod](https://user-images.githubusercontent.com/42382648/104325279-376c4680-54c7-11eb-9025-7ad860e15159.png)

![2_subdivs](https://user-images.githubusercontent.com/42382648/104325291-3cc99100-54c7-11eb-9e4e-101692feddb1.png)

![4_subdivs](https://user-images.githubusercontent.com/42382648/104325302-405d1800-54c7-11eb-8c3b-172b2eb4b5f0.png)

<details>
  <summary>Explanation</summary>
  
To save a lot of performance I manually keep count of occupied children tiles for every tile. This allows me to simply use this to discard a tile immediately when looking for free tiles for LOD.
Otherwise it would require some complicated algorithm or having to iterate over all the sub-tiles to find out if it can be occupied or not.
  
The size of the shadowmap is determined by taking advantage of the clustering data, similarly to the presentation/paper for clustering, but instead of using the angle I use the minimal Z cluster paired with a custom made function that plots from 1-16, to 1.0-0.0, and basically the closer you get the higher the `shadowMapScale` becomes. So far results I think are acceptable enough and it's a lot faster compared with the solution proposed in the paper.
  
I tried to implement it the way it's done in the paper, but unfortunately I got stuck at the step of obtaining the "solid angle". I couldn't find a way to do it without overcomplicating the clustering algorithm with the data there is available.
  
</details>

I'm also currently trying to wrap up other sub-projects before opening a PR. Currently porting changes to make the other render paths work, like forward or deferred mobile. Also still trying to get dual paraboloid maps to work.

Oh and also, I solved the issue with directional lights, it seemed to be the `uniformSize` parameter that was incorrect and that lead to that rendering issue. There is still some differences with filtering that I need to investigate, but the result looks more closer now to the original.

![image](https://user-images.githubusercontent.com/42382648/104326174-2ec84000-54c8-11eb-832b-cf216ad60659.png)

**Comment by MoritzBrueckner** [comment]
@N8n5h I guess this can be closed now?

**Comment by N8n5h** [comment]
> @ N8n5h I guess this can be closed now?

Yes, it can be closed now :+1:
