### ISSUE TITLE
Mesh distortion

### ISSUE THREAD

**Issue by MGeymer** [armory3d/armory#1293]
### SHORT DESCRIPTION:
Mesh distortion occurs due to normal map and height map. For the material I used Armory PBR.

### TECHNICAL SPECIFICATIONS:
_What version(s) of the following did you try:_
Blender: 2.80
Armory: 0.6
Operating system: Windows 10
Graphics card & driver: AMD Radeon (TM) R5 M330

**Comment by N8n5h** [comment]
What do you mean by "mesh distortion"? can you provide screenshots?

**Comment by MGeymer** [comment]
@N8n5h , 
![изображение](https://user-images.githubusercontent.com/20752579/59326473-19919b00-8d00-11e9-9779-9a0b31f616b2.png)

**Comment by N8n5h** [comment]
Ok, I tested it and it seems that you didn't link the correct texture for the normal map:

![image](https://user-images.githubusercontent.com/42382648/59369511-f6261a80-8d16-11e9-87f9-4e0767da8ab6.png)
(notice that it has no thumbnail)

![image](https://user-images.githubusercontent.com/42382648/59369687-51f0a380-8d17-11e9-8cf3-ae07cafdd576.png)
(after selecting the image in the Sources folder with the zip you provided).

If you try to run the Player after selecting the correct image it will throw and error because you have n-gons in your door (more than 4 vertices in a face)
![image](https://user-images.githubusercontent.com/42382648/59370074-26ba8400-8d18-11e9-9a46-e2710e4ee773.png)

after fixing them:
![image](https://user-images.githubusercontent.com/42382648/59370209-6bdeb600-8d18-11e9-9c55-f905e5af7efc.png)
