### ISSUE TITLE
Build 7: first person controller camera movements 

### ISSUE THREAD

**Issue by AndreaMonzini** [armory3d/armory#132]
Hello,

the camera movements in the first person controller are shaky when i press keyboard and i move mouse at the same time.
The problem is more visible when fps are lower than 60 ( > 16,7 ms for frame) but the camera shakes even at 60 fps.

My system : OS X® 10.11.6

How to reproduce: just enable "walk" in viewport camera, translate the position with keyboard and point the mouse towards an object at the same time ( the same effect is present in the template_first_person  example ).
It seems that  the problem is related to the translate position movements and not in the mouse look.

Quick video example:

http://andreamonzini.com/files/img/1P_Controller.ogg

**Comment by HeadClot** [comment]
@AndreaMonzini your video is either down or does not want to play for me :\

**Comment by AndreaMonzini** [comment]
Hello,
just checked the video and it works. 
You should be able to download it maybe open it with VLC.

**Comment by luboslenco** [comment]
I can reproduce on a Mac. Strange thing is that holding any (character) key makes it shaky, even when camera is not translating, just rotating. As soon as the key is released, camera rotation is smooth again. That may indicate the problem is not calculating camera matrices, but maybe input / timing / update loop. Will investigate further.

Also seems to not happen on Windows.

**Comment by sixFingers** [comment]
Having the same issue. It's become an obsession - for the record, after facing the issue with Kha, I've tried endless alternative implementations (Amulet engine, native GLFW and SDL), with the exact same output. I'm on Macbook Air early 2015, with Intel HD Graphics 6000 (if that matters). I'm sure my math works since everything's smooth if I take output out of the equation. Also mouse only seems smooth, while adding a key press introduces jittering.

**Comment by luboslenco** [comment]
Craziness, apparently not a direct bug in armory/kha then.:(

**Comment by sixFingers** [comment]
I have spent an insane amount on this, it happens even at lower level. With both GLFW and SDL the issue is there. The only way I got rid was avoiding GLFW and SDL event loops (which use native Mac API under the hood), and instead reading mouse and keyboard input directly through Hid interface. I can't remember, what's taking care of native windowing and GL context in Kha?

**Comment by luboslenco** [comment]
Great to hear there is a solution. In Kha it's handled by Kore (developed alongside it). For the keyboard handling: https://github.com/Kode/Kore/blob/master/Backends/System/macOS/Sources/Kore/BasicOpenGLView.mm#L43. Adding a different implementation should be doable.
