### ISSUE TITLE
save the nimbus! - transparency

### ISSUE THREAD

**Issue by onelsonic** [armory3d/armory#1413]
So in blender you have two ways to achieve a correct 24bits transparency :

1. Cycle Renderer: You will use directly the alpha channel from a the Principled BSDF material.

2. Eevee Renderer: You will use the Principled BSDF and a Transparent BSDF and mix them together with a Mix Shader

Neither of these works in Armory:
are there any other way to achieve correct transparency other than haxe coding the pixel color with calculations?

here is my file :
https://github.com/onelsonic/armory_tests/blob/master/nimbus_24bits.7z

What I am trying to achieve, a correct transparency : 
![nimbus](https://user-images.githubusercontent.com/53947594/65795781-58424880-e16b-11e9-80b8-dc05c02f1f96.png)

**Comment by Sandy10000** [comment]
Couldn't solve the problem of noise in the center, but other than that  could fix it by changing the settings.

3D Viewport : Since it is in edit mode, change to object mode.
Shader Editor : Use the settings for cycles.
Material tab : Uncheck Alpha Test as in the image.
![3](https://user-images.githubusercontent.com/48373918/66750728-2994d380-eec8-11e9-8173-042f4dc5f1cf.jpg)
![2](https://user-images.githubusercontent.com/48373918/66750733-2d285a80-eec8-11e9-8ac5-ffa8323c7c89.jpg)

**Comment by Sandy10000** [comment]
Open the image "nimbus_24bits_transparent.png" used for transparency in the RenderDoc Texture Viewer, select alpha and set the black point to 1, and the same shape as noise was displayed.
![1](https://user-images.githubusercontent.com/48373918/67578020-93409780-f77c-11e9-9e45-27476dda1c5b.png)

**Comment by Sandy10000** [comment]
The bug has not been fixed and is a workaround, but adding a Math node and subtracting 0.0002 from the alpha value eliminates the noise.
![1](https://user-images.githubusercontent.com/48373918/67634542-d9266880-f900-11e9-93ae-a6be88a7bc62.png)
![2](https://user-images.githubusercontent.com/48373918/67634544-daf02c00-f900-11e9-8a40-233d9206ef54.png)

**Comment by onelsonic** [comment]
Hi @Sandy10000, nice workaround. Maybe we can fix it using this workaround in the code of Armory.
This works with the Cycle settings ok.
I will have a look, great finding 👍

**Comment by Sandy10000** [comment]
I don't know where to fix it so far, so if you can fix it.

**Comment by onelsonic** [comment]
@Sandy10000 I did some tests and it works fine. The strange part is that we have to disable the Alpha Test parameter... I will look if the subtract operation can be added internally, since transparency is not handle correctly.
Thank you

**Comment by Sandy10000** [comment]
@onelsonic Alpha Test seems to be a function to cut out the background using the binarized alpha value. I think that it is necessary to remove the check if you want to express the transparency of the clouds with 8-bit 256-level transparency.

**Comment by N8n5h** [comment]
I found the line for opacity
https://github.com/armory3d/armory/blob/b3dab3c1b5315ffd5952ab729d166ae1063532a9/blender/arm/material/cycles.py#L93
so the fix could be applied there: https://github.com/N8n5h/armory/commit/35274c86734c04a62c6cfa4836b00d9412c84f09

**Comment by Sandy10000** [comment]
It was confirmed that no noise was generated even when Math node was not added. It can be said that the problem of the noise seen from the user side has been solved. Great progress!

When talking about the internal processing, it uses an incorrect value ({0} -0.0002) that is very close to the correct value ({0}). I think that additional correction is necessary so that it can calculate using the correct value.

Again, great progress!
