### ISSUE TITLE
Having problems with physics raycast

### ISSUE THREAD

**Issue by Henriqu3d** [armory3d/armory#1541]
First, sorry for the bad english. The problem is: when i try to use the physics raycast to print a object name, i always get a null information.

I try different ways to do this, but i don't have sucess. I have downloaded the raycast example file and it works fine, but when i try to make it by myself using logic nodes, i can't. I reproduce the same logic as in example file, but keep getting null information... If it help, the problem is not with Blender version nor my PC, cause in some older version of Armory 3d (05-legacy-win64-b27 if i remember) it appearly works as it should.

Blender: 2.81a
Armory: 2020-1
OS: Win x64
Graphics card: 920mx

Here is two ways that i have tried: 
[raycastest.zip] (https://github.com/armory3d/armory/files/4038140/raycastest.zip)

**Comment by Sandy10000** [comment]
**test1.blend:**
Connect the "Cast Physics Ray" node Object output terminal and the "Set Material" Object input terminal directly. No "Get Object" node is required.

**test2.blend:**
The Raycast example uses the "Get Name" node to get the Object name from the Object. If you want to do the same, you need to connect a "Get Name" node instead of a "Get Object" node. There seem to be other connections than the example.

**Comment by Henriqu3d** [comment]
Problem solved thanks to Sandy10000. You are awesome and helped me a lot! Sorry for the mistake :/
