### ISSUE TITLE
Mesh exports terribly sometimes...

### ISSUE THREAD

**Issue by TriVoxel** [armory3d/armory#1559]
In the attached file, you can play the animation to see what the scene looks like and see the objects. If you build it, you will notice that the table becomes a jumbled mess that is unrecognizable.

Only fix is to delete the table and start over. Has happened to me before on a different mesh.

![Screenshot_20200203_013127](https://user-images.githubusercontent.com/25536957/73637394-69252e00-4625-11ea-8c87-b118e31d7e37.png)

[Lego Anim Test 1 Armory Test.zip](https://github.com/armory3d/armory/files/4146885/Lego.Anim.Test.1.Armory.Test.zip)

**Comment by N8n5h** [comment]
I was unable to reproduce the issue in your test file. 
Did you try cleaning the cache to see if it solves the issue?

**Comment by TriVoxel** [comment]
Yes I tried that. Was using latest Armory from Git.

**Comment by MoritzBrueckner** [comment]
I didn't try the test file, but I have similar issues with different meshes sometimes. But these issues are not reproducible, sometimes the build works, sometimes not (cleaning the cache doesn't help). I will try to upload another test file in the next days if that issue reoccurs

**Comment by N8n5h** [comment]
I had an issue similar to this one when I inadvertently lost a normal map by not saving it and then when building the mesh was all broken like the picture, so my hunch is that the problem may be around UVs and/or normal maps.

> But these issues are not reproducible, sometimes the build works, sometimes not (cleaning the cache doesn't help).

I think probably to aid testing something like this would be to change the debug Play button to allow exporting assets on demand, so that if you find a case that doesn't work you can then keep reproducing it without the fear of "stepping" over it with a new build export.

**Comment by MoritzBrueckner** [comment]
[This](https://github.com/armory3d/armory/pull/1590) pull request fixed it for me :)

**Comment by MoritzBrueckner** [comment]
@TriVoxel This issue seems fixed, please reopen if the issue persists.
