### ISSUE TITLE
Weird name issue when instancing multiple objects

### ISSUE THREAD

**Issue by philipmduarte** [armory3d/armory#1605]
Hey Lubos, I found this when I tried to instance two instances of a linked collection. I'm not so sure if this is armory-related or not, but at iron's Scene::spawnObject I noticed that the hierarchy lookup was failing to reach the proper node due to a name change, as you can check on the file.
[multiple-instances.zip](https://github.com/armory3d/iron/files/4294890/multiple-instances.zip)

Try as I might, I couldn't locate where the object name was being changed, so I tried this:  https://github.com/philipmduarte/iron/commit/d742aa343120bd30eb6d38d3e3775a91e4030447. 

Now the file runs. If `object.name = name` is commented out, there's another error down the line at createTraits also because the actual game object has a different name than the one in the scene file. How come the name is changed? or maybe this is armory-related?

Interestingly enough, there doesn't seem to be a problem instancing many cubes...

**Comment by MoritzBrueckner** [comment]
Hi, I just took a look at the file and the renaming seem to happen in `Scene.createMeshObject()` because armatures probably need unique names in another place I don't know.

The whole name thing is pretty broken due to the fact that there are so many possible conflicts of names and I recall that there were a lot of other issues like this which we fixed by some ugly exporter workaround code. I think that your idea with using UIDs is much cleaner and robust and is a real solution instead of just fixing symptoms. Probably, the same can be applied to `createTraits()` when you omit `object.name = name` (which breaks the uniqueness of armature names). I will have a look at it :)
