### ISSUE TITLE
Logic Nodes: Array Add with Vector overwrites Array

### ISSUE THREAD

**Issue by Simonrazer** [armory3d/armory#1629]
**Description**
When using Array Add with an Vector as Value input all places of the Array get overwritten to the set Vector.

**To Reproduce**
![Unbenannt](https://user-images.githubusercontent.com/30187223/77636560-98d12200-6f54-11ea-86f5-a710cee642bf.PNG)
This outputs this after having pressed space a couple times: 
```
armory.logicnode.PrintNode:13: Game: [(10, 69, 39, 1)]
armory.logicnode.PrintNode:13: Game: [(39, 51, 98, 1),(39, 51, 98, 1)]
armory.logicnode.PrintNode:13: Game: [(83, 94, 33, 1),(83, 94, 33, 1),(83, 94, 33, 1)]
armory.logicnode.PrintNode:13: Game: [(64, 45, 53, 1),(64, 45, 53, 1),(64, 45, 53, 1),(64, 45, 53, 1)]
```

**Expected behavior**
A new place should be made in the Array and only this place should have the values of the used Vector. The places generated in the beginning should stay at the same value.

**System**
Blender: 2.82
Armory: git version
OS: Win10
Graphics card: GTX 1060

**Test File**
[MS.zip](https://github.com/armory3d/armory/files/4386556/MS.zip)

**Comment by MoritzBrueckner** [comment]
The problem is the Vector node, it creates a `Vec4` object internally and updates it without copying, so the resulting array just has multiple references to that single vector object.

I fixed the Vector node (it now returns a new `Vec4` object everytime `get()` is called on it) and also refactored the ArrayAdd node a little bit, but before opening a PR I would like to ask if the changes are actually helpful. Should the Vector node instead get a toggle to enable the new behaviour?

This would be the new Array Add node:
![array_add_node](https://user-images.githubusercontent.com/17685000/78927978-17bf7200-7aa0-11ea-80f3-113cb4bced27.png)

It combines the old `Array Add` node with the `ArrayAddUnique` node and replaces the "unique" setting with a boolean switch (unfortunately, the "unique" option only works with data types that are comparable with `==` in Haxe for now because of `Array.indexOf()` but this also was the case for the old node).
There is another new option "Copy Array" that works with a copy of the input array, never replacing values in it. To read that copied array, another output is added to the node and if "Copy Array" is `false`, it just outputs the changed input array (but it is the same `Vec4` object then, so changing that will also change the input of course).

Both "Unique Values" and "Copy Array" are `false` by default, resulting in the old behaviour (with a fixed Vector node of course :)).

**Comment by Simonrazer** [comment]
That's great! I think "Copy Array" does not really convey what turning that option on actually does (for me at least). Maybe let it say "Modify original" and let its default value be true?

**Comment by MoritzBrueckner** [comment]
Thats a good idea :) PR: https://github.com/armory3d/armory/pull/1653
