### ISSUE TITLE
"While" node crashs the engine

### ISSUE THREAD

**Issue by knowledgenude** [armory3d/armory#1638]
"While" node crashes the engine if Condition = True

How to reproduce:

1. Add a While node.
2. Place an input to it.
3. Check true the Condition box.
4. Start the player and active the input.

**Comment by MoritzBrueckner** [comment]
The problem with this is that the while node gets executed every frame. But when the condition is never `false`, the while loop never ends and the frame doesn't "end" as well.

I think this is not an Armory bug but rather a misuse of that node. The same will happen if you put `while(true)` in your Haxe code and it is normal behaviour in all other engines as well. It is up to the game developer to take care of it so that it never happens.

**Comment by knowledgenude** [comment]
It seems a little complicated to understand this node, I thought it was like a Branch node. If there is nothing wrong, then I will close this problem. Thanks for the answer.
