### ISSUE TITLE
How would I go about making cutscenes?

### ISSUE THREAD

**Issue by AviaNick** [armory3d/armory#1698]
Hello! I'm very interested in Armory3D. However, my game has a story with cutscenes. I would like to play a video of the cutscene, made in a different application. Can I do that, or will I have to animate and render the cutscene out in Blender and Armory3D?

**Comment by knowledgenude** [comment]
I recommend you to make in-game cutscenes because of the work you will have with animations will be the same, apart of videos will  increase (in some cases to much) the game size. Cutscenes in-game will need to keep the same graphics settings or a little better if your scene don't have too much geometry. A problem you will have in this way is sounds. Is easier to sync the sound in video than in game. I never played a video in Armory and i don't know if it is possible. I recommend you to keep the animations out of Armory, letting you switch from game to video when you want. And keep in mind, the organization always is very importante from start to finish.
