### ISSUE TITLE
can't install when using activepython 

### ISSUE THREAD

**Issue by Ryder17z** [armory3d/armory#1713]
**Description**
when i launch setup.py
![explorer_2020-05-23_18-20-37](https://user-images.githubusercontent.com/2000703/82735508-96a3fd80-9d22-11ea-80ec-f07b37254139.png)

**To Reproduce**
1 install activepython
2 try running setup.py

**System**
Blender: 2.82a
Armory: latest today
OS: win10 x64

I need more information on what's the problem.

**Comment by MoritzBrueckner** [comment]
Hi, Armory is a Blender addon and can't be installed purely using Python (or any other Python distribution). You can find detailed installation instructions [here](https://github.com/armory3d/armory/wiki/setup).

**Comment by Ryder17z** [comment]
That was less than obvious. I thought this was a separate tool that I would need to link to blender.

**Comment by Ryder17z** [comment]
It might not even be suitable for me, considering the insane learning curve blender (2.7x) has for someone who started modeling in "proper" software like AutoCAD, Solidworks, etc

**Comment by Ryder17z** [comment]
(if you want a picture: imagine bashing your head through a brick wall)

**Comment by knowledgenude** [comment]
Hi @Ryder17z. I don't think that Blender have a insane learning curve. I think AutoCAD is more complex than it because i never used it. Anyway, you don't need to be a Blender expert to use Armory. Enabling Armory addon just change Blender into a game engine, like Unity, Unreal, etc. Don't block yourself from Blender, it is an amazing tool that deserves a try. Take a day to just look into Blender, i know that you will love it. The problem is that Blender is different from what you get used. If you want any help with Armory addon installation i give you 2 or 3 prints that will solve this for you, but i recommend you to get used to Blender a bit more first :)
