### ISSUE TITLE
Armory3d can't handle rotations - Impossible to make 3rd person games

### ISSUE THREAD

**Issue by ArmoryBlender** [armory3d/armory#1740]
Hey there!

Whoever tried to make a third person controller like the one from unreal engine's starter example knows that it is nearly impossible! The reason for that are the rotations in armory3d. I would like to share my problems:

**Problems**
1: You can't get a 360° angle from the player. You will get a 180° angle and then it starts from -180° which is a huge problem for making a smooth turn.

2: If you rotate your player in the desired direction it gets messed up...somehow. If you would press the S key your player supposed to turn around. That works but if want to get the angle of the player  while you pressing the S and D key you don't get 225°, instead you will get an angle of -135°. With this problem the player will flip on the head and also dont know where exactly to walk. 

I really hope this problem will get fixed.

Please share your experience with 3rd person game in armory3d!!

![Unbenannt-1](https://user-images.githubusercontent.com/48133099/85227267-b63f4c00-b3dc-11ea-9d79-5d5c4649f71e.png)

**Comment by MoritzBrueckner** [comment]
As a workaround you could try using `angle % 360` (modulo). It's very likely related to Iron, so I'm not sure if fixing this would temporarily break Armorpaint. Maybe move this issue to the Iron repo so that there is a higher chance of lubos fixing that?

**Comment by knowledgenude** [comment]
I think 3rd person is not a good idea for C targets now because the physics ray is not working to make the camera collision.

First person is more imersive, but maybe you dont like it

About the rotation, i am very bad at math but in my mind:

You have -180-180
You want 0-360

If you add 180 to the rotation, the value will you not be 0-360? You say that you have -135 in the place of 225, in this case adding 180 don't works :/

**Comment by ArmoryBlender** [comment]
> I think 3rd person is not a good idea for C targets now because the physics ray is not working to make the camera collision.
> 
> First person is more imersive, but maybe you dont like it
> 
> About the rotation, i am very bad at math but in my mind:
> 
> You have -180-180
> You want 0-360
> 
> If you add 180 to the rotation, the value will you not be 0-360? You say that you have -135 in the place of 225, in this case adding 180 don't works :/

**Comment by ArmoryBlender** [comment]
@knowledgenude I tried a similar thing but it still doesnt work because if you rotate the player from the euler angles the euler angles will rotate from 0 - 180° and then it gets flipped on the head. The problem is related to iron like @MoritzBrueckner said.

**Comment by knowledgenude** [comment]
I make an example file for this issue. Isn't possible to get the object rotation with correct values, see the example: 
[rotation_issue.zip](https://github.com/armory3d/armory/files/4813834/rotation_issue.zip)]

Just use right and left to rotate the object and there is a display for its euler rotation

**Comment by Simonrazer** [comment]
Link to #512

**Comment by knowledgenude** [comment]
@ArmoryBlender , hi again! I found a workaround for you...

Yes, is impossible to get the correct value of rotations in Armory for now, but you can create a fake rotation for the object in this way:

1. Create a float property "Rotation" for the object you want

3. Sync the value of the property to the object rotation (use Get Property, Vector and Set Rotation nodes for this). 

Just don't use Get Rotation for now. After it be fixed, you can simple delete Get Property and put a Get Rotation instead :)

I really hope this works for you. I will send an example here when i can

**Comment by ArmoryBlender** [comment]
Hey @knowledgenude !!
First of thank you for your help. Im not a fan of logic nodes....I just can't work with logic nodes. Could you send me please your blendfile. That would be awesome!!

**Comment by knowledgenude** [comment]
I've done a simple example of how you can reach this, but i think that it can be a big work to do the full logic working, nothing impossible

[untitled.zip](https://github.com/armory3d/armory/files/5010820/untitled.zip)

The Axis (outside) object is where the "X, Y, Z" coordinates of the Direction (inside) object will be stored. Axis can be used for the horizontal camera axis.

![thumb](https://user-images.githubusercontent.com/63247726/89104171-9e9caf80-d3ed-11ea-95fb-5e3784c164be.jpg)

So in case of the player press S, the Direction will be for back from the Axis. If you rotate the Axis, the Direction will follow it, because it is updating every frame, but you can update it just when W, A, S, D keys are pressed. You can smooth this using Timer and some math with the stored values.

The problem here is because the values don't match Blender values and are very inaccurate (always have 0.00*** in the end), it is why you have to always have full control of the rotations, this need a reference object with accurate values.

The nearest accurate values i found to convert into the values you want is:

3.200° for 180°
1.600 for 90º
-1.600 for -90º
0.000 for 0º

Maybe i can do a full third person logic here when i have more time and find out an easier way to do this, but not wait for nothing as i always end with confusing methods

**Comment by ArmoryBlender** [comment]
Thanks for your little documentation @knowledgenude.
I dont think that I will use this method because it is very time consuming to set everything up. I also don't have that much time to set this up. Like I said Im working on other projects but I will save your documentation in case I will go back and try it with a new armory3d version. Anyways thank you so much for your time!!

**Comment by knowledgenude** [comment]
I've done some progress here, but i am failing when i try to interpolate the rotation for the nearest angle to make the smooth turn.

I already tryed to use the values between 360/180 but the behavior is almost the same. If someone know a method to make the the rotation for the nearest angle, please let me know

I have a variable for **Player Rotation** and a variable for **Rotation**, just need to interpolate then:

[Test4.zip](https://github.com/armory3d/armory/files/5074806/Test4.zip)

After i find a way to do that, i think just adding the horizontal axis rotation to the player rotation should change the directions, like in the last example i send.

But due to the lack of vertex parenting, i will need to find an workaround for the axis not be fixed at the player.

**Comment by knowledgenude** [comment]
I've found a script here https://stackoverflow.com/questions/2708476/rotation-interpolation

Now is possible to interpolate the rotation for the nearest angle, but i don't know a way to get the distance between the from-to rotation to reduce the timer... Probably this method will not allow this but if you don't care about the same speed in any direction distance, this method look feasible.

I also don't know how the modulus will work in other targets.

You can test it here, the code is commented: [RotTest.zip](https://github.com/armory3d/armory/files/5643652/RotTest.zip)

I think this can't be a function yet, because without knowing the distance between the angles, the interpolation will not be correct. I will keep searching for better methods and i post here any news.

**Comment by ArmoryBlender** [comment]
Hey there! Thank you so much for your time that you invested in this
problem!! I tested your blend file and I have to say that you did a really
great job in implementing the method from stackoverflow. Unfortunately I
still can't create my third person controller because of the following
reasons:
- Wrong rotations
I need to work with full 360° angle for the player and the camera to turn
in the right direction like the unreal engine 3rd person template

I'm still trying to find a way to somehow implement it in armory3d without
going deep inside armory and change the core settings!

Anyways I'm really happy for your answer on this topic and excited for the
future :)

Greetings

Armoryblender





Am Fr., 4. Dez. 2020 um 16:38 Uhr schrieb knowledgenude <
notifications@github.com>:

**Comment by knowledgenude** [comment]
@ArmoryBlender , i think it is not possible to only work in a 0-360 degrees space, because there is a "wall" between the -180 and 180 space, when you need to passes trough it, you need to change the space to 0-360 and vice-versa. But i found a new way to do that (better in my opinion, as you can now catch the distance between the two angles). That is why i deleted the older comment.

The method is here in the last comment: https://gist.github.com/shaunlebron/8832585
Basically i just copy and past it, but i put the "from" rotation to a 2 rad modulo, you can see the result with an animated character here: [PlayerControl.zip](https://github.com/armory3d/armory/files/5649579/PlayerControl.zip)

I really can't imagine a place where it can't be applied, it is basically a "Mix" node that takes in count the nearest angle.

Ps: I don't know if there is some restriction about sharing this animations here, didn't find anything in Mixamo FAQ, so i will remove it after you see. Also the animations are glitchy, i don't know if it is because of the incorrect scale or some bug in Armory.

**Comment by ArmoryBlender** [comment]
@knowledgenude Oh my god!! How the f*ck! You really made it....I'm literally speechless. This works exactly how I wanted. You are amazing!! I'm impressed how did you implement this method. Now I have 3 questions:
- Can I use your scripts for my project?
- Do you want money of your work?
- Do you want to work together in the future?
I reallly want to thank you from the bottom of my heart for this time consuming issue!! I really want to thank you. I worked soo damn long to solve this problem...

Have a good day

Greetings 

Armoryblender

**Comment by knowledgenude** [comment]
@ArmoryBlender thanks! Of course you and anyone can use these scripts, you engaged me to search for the solution, otherwise i wouldn't try to find it! 

I just recommend you to replace the "acceleration" method because it need to be clamped depending on the pace. I didn't care about it because my main purpose was to solve that rotation thing. If you press "alt" you can see that the character is flickering because its velocity is never exactly. Also try to review the whole thing, because i am very beginner and may have optimized ways to do the same thing!

I don't want money for this, now i do it for learning it was more than sufficient! But i really thanks you for your respect, you made my day! :+1: 

And of course i would like to work together in a project in the future if i have time for it! Doing this alone is a pain... Also i need to gain more experience. Feel free to contact me for any project some day!

I made i little text to explain this method even for case i forget it someday, if anyone need https://forums.armory3d.org/t/how-to-interpolate-a-rotation-to-the-nearest-angle-smooth-free-axis-third-person/4388.

Greetings!

**Comment by ArmoryBlender** [comment]
@knowledgenude Alright! I already changed the code a bit. I fixed the acceleration movement and the animations. 1 thing I have to figure out is how to change the distance between the camera and the player without changing the ray cast function. Maybe I have to create a new one! With your documentation on the forum that you just posted its easier for people to understand the issue.

Thank you again so much for your valuable time!

Greetings

Armoryblender

**Comment by knowledgenude** [comment]
@ArmoryBlender i don't know if i changed something in the posted code, but you can just change the camera and its ray (empty)  position and the collision will work as well. You can change the distance between the camera and the hit if you can see trough the surfaces.

```
camDist = cam.transform.world.getLoc().distanceTo(camAxis.transform.world.getLoc()); // get the distance between the camera and the player on init

camRay.transform.loc.set(0, -camDist, 0); // set the camera ray position to the camera position

camDist -= camDistFromRay; // now just increase the distance to also consider the distance between the camera and the distance from hit
```
This script was improved: [CamControl.zip](https://github.com/armory3d/armory/files/5653818/CamControl.zip)

**Comment by ArmoryBlender** [comment]
@knowledgenude I already figured it out and fixed other small issues! My next challenge is to implement a animation state machine like this: https://www.youtube.com/watch?v=z5dOzYKB3Qo&t=119s I searched a lot but didn't find a good documentation about implementing it. The majority shows how to implement a FSM which is not what I want. What I want is a FSM but for animations.  The implementation shouldn't be that hard i guess....

**Comment by ArmoryBlender** [comment]
@knowledgenude I found a new much simpler way to smoothly rotate the player!! I played with the iron.math.Vec4 around and found a function called "fromTo". With this function I finally can smoothly rotate the player without complex calculations.

![Unbenannt](https://user-images.githubusercontent.com/48133099/103141076-822c4700-46ef-11eb-8a1f-0e9d9b200ffb.PNG)

I will soon upload a video about it. Meanwhile I'm adding some new things to the template!

I'm still thankful for your invested time into this topic!!!

Greetings 

Armoryblender

**Comment by knowledgenude** [comment]
@ArmoryBlender Hello again! If you still interested, feel free to make suggestions for the fsm here: https://github.com/knowledgenude/statemachine

It doesn't have any directly relation with animations yet, because i don't know what exactly it should have. If you miss any functionality or have any suggestion to improve the user API you could tell me and i try to send a PR for Armory when it is finished.

**Comment by ArmoryBlender** [comment]
@knowledgenude Heey man! Thank you for the Informations. I'm already working on my own state machine. I think it is not bad to compare mine with yours! Im trying to create it for character animations...but I will also use it for enemy AI etc. It would be awesome if you could send me your implementation documentations(website, pdf etc.)!

Greetings

Armoryblender

**Comment by knowledgenude** [comment]
@ArmoryBlender sorry for the long time to reply, i don't had finished it yet. Unfortunately i don't have any experience on using it, but as soon as possible i will try to make something with that and see where i can improve it. I also didn't found any documentation on this, the few things i do was trying to understand the code of the guy in the video you send and made something simple from that.

I know it looks complicated but the working of it is very simple (from performance view i don't have any clue on how to improve it, but looks acceptable right now). So a pdf is not necessary...

* The class FSM is the class that controls the execution of the states (you can see in the `run()` method, it calls for the `onEnter()`, `onUpdate()` and `onExit()` methods from of the current state).

* The class Transition have two states (start and end) and the function responsible to call the next state. The FSM tries to get the next state of ALL transitions that match the START state (the current state is X, then all transitions where the FROM state is X). The Transition only returns the next state if its function returns true.

Other way to check if the transition can happens is instead of trying to get the next state, get the return of the function and if its is true, then the next state is set to the transition next state.

              class Main {
	              var test = new Test(myFunc);
              
	              public function new() {}
              
	              function myFunc() {
		              return false;
	              }

                       if (test.func()) doSomething;
              }
              
              class Test {
	              public var func: Void -> Bool;
              
	              public function new(func: Void -> Bool) {
		              this.func = func;
	              }
              }

I found a similar fsm here https://stackoverflow.com/questions/5923767/simple-state-machine-example-in-c what means that there is not too much ways to do a fsm...

I highly recommend you to look on design patterns (more specifically strategy pattern and observer) it does not helps too much on the state machine itself but help to better learn Haxe and conding in general (which indirectly will help you to understand the fsm and further other stuff)... https://refactoring.guru/pt-br/design-patterns/catalog

I am a very confuse person, i am not good explaining things. If you have any specific question about the fsm you could ask me, but it is really that simple. Feel free to use it as it is if you want, i don't see any problem on that!

All the best!

**Comment by ArmoryBlender** [comment]
Hey @knowledgenude!! First you don't need to apologize for your time, I totally accept that, it's no problem! I studied your state machine and it works perfect. My state machine got inspired by yours and the one from the guy who created mario in armory3d. I tried to make it work with animations, it worked except for one thing. The one thing is armory3d's fault. I'm talking 'bout the animation blending. If I try to make a combo attack state or something else with an attack state it does not blend from one to the other state smoothly. I also tried it in unreal engine (same animations) and there it blends smoothly. Anyways I literally have no idea how to fix that...in the meantime I use the state machine to create a enemy AI thingy.

Thank you for the websites and your effort that you put in

Greetings

Armoryblender

**Comment by knowledgenude** [comment]
You won't belive me, but i guess the mario guy pushed a wrong fix... :1st_place_medal:

By deleting [those added lines](https://github.com/armory3d/iron/commit/38de0b215f943b660e36cd22feac5dabecf15008#diff-833951d6a7bb4f645ce64623c1ca82c39b8c6496daabc26746a7179d7d865c0e) the blending works better. I suspect that there will still have some issue related to this, but unfortunately i don't have too much time to test. If you face something wrong please open a issue with a small example file, so we all can track that together. If you think this change improved anything feel free to open a PR or i do that later.

**Comment by JAWS81** [comment]
Hello,

I used the above mentioned solution for the third person player controller. And rebuild ti using nodes.
https://forums.armory3d.org/t/how-to-interpolate-a-rotation-to-the-nearest-angle-smooth-free-axis-third-person/4388

It now seems that in Armory3d 202111 something has change regarding the player angels. 

Has anybody recognized this as well? The solution is now not working anymore and I am struggling to get it working again
Maybe someone has a solution for this.

**Comment by knowledgenude** [comment]
Do as the last print shows:

// The first vector in the arguments determines that the player will "look" to the new vector after you apply the rotation...

targetRotation = fromTo(0.0, 1.0, 0.0, yourDirectionVector); // use "Look At" in logic nodes

// Do a lazy lerp

currentRotation = currentRotation.lerp(currentRotation, targetRotation, speed); // Use quaternion lerp in logic nodes, probably in the quaternion math

This should work

**Comment by JAWS81** [comment]
Hi,

thanks for the quick reply. I will try your suggestion.

But I am wondering if something inside armory3d has change at this point. My controller was working pretty well till I updated my SDK. And I haven´t found anything mentioned in the release notes.

**Comment by knowledgenude** [comment]
I think your logic node shouldn't be affected by the last changes in Armory. Anyway this method from the forum isnt that good because it complicates the thing and can be used only in one axis, while with quaternions you can lerp whatever axis you want. Probably this operation deserves a node specific for this task (lerp to nearest angle). Please, tell if that worked :)

**Comment by JAWS81** [comment]
Hi,

your solution worked great . It also makes it more easys for the eyes. Had to look a bit around but found the function under rotation math.
