### ISSUE TITLE
Armory is slow! (Blender v2.82)

### ISSUE THREAD

**Issue by IL7Games** [armory3d/armory#1743]
Hello devs,

Well, I tried to use Armony 3D in hopes of being able to develop a mobile game in 3d. But with Blender 2.82 I am having slow issues even with the default project.  I'm running the project on the notebook and the fps rate only reaches 22 per second and I'm using the armory's default settings.

I also wanted to talk about two more things.. The first is that when I went to install the Armory that I downloaded from the itch (ArmorySDK-2020-6.zip), the armory player was not working! And some properties were not willing to open as "armory export" and "armory project". So I decided to download ArmorySDK-2020-4.zip and it's working here.

Second, I tried to create a post on the Armory forum, however, when trying to sign up, I haven't received the verification email so far! I already looked at the spam box, the trash can, I went to check if I typed the right email...

I don't know what's going on! : /

I tried to use Armory 3D because, I thought it was cool to create the models and test directly in the Blender. Because in Godot I have to keep exporting whenever I make a change.

<details>
   <summary>$ Neofetch</summary>

   ```
		    -```````````                  il7games
		  `-+/------------.`              ----------------- 
	       .---:mNo---------------.           OS: Solus x86_64 
	     .-----yMMMy:---------------.         Host: Z450LA 1.0 
	   `------oMMMMMm/----------------`       Kernel: 5.6.18-155.current 
	  .------/MMMMMMMN+----------------.      Uptime: 2 hours, 34 mins 
	 .------/NMMMMMMMMm-+/--------------.     Packages: 933 (eopkg) 
	`------/NMMMMMMMMMN-:mh/-------------`    Shell: bash 5.0.11 
	.-----/NMMMMMMMMMMM:-+MMd//oso/:-----.    Resolution: 1366x768 
	-----/NMMMMMMMMMMMM+--mMMMh::smMmyo:--    DE: Budgie (git-bc1f87765258a2b716a26 
	----+NMMMMMMMMMMMMMo--yMMMMNo-:yMMMMd/.   Theme: Plata-Noir [GTK2/3] 
	.--oMMMMMMMMMMMMMMMy--yMMMMMMh:-yMMMy-`   Icons: Papirus [GTK2/3] 
	`-sMMMMMMMMMMMMMMMMh--dMMMMMMMd:/Ny+y.    Terminal: gnome-terminal 
	`-/+osyhhdmmNNMMMMMm-/MMMMMMMmh+/ohm+     CPU: Intel i3-4005U (4) @ 1.600GHz 
	  .------------:://+-/++++++oshddys:      GPU: Intel Haswell-ULT 
	   -hhhhyyyyyyyyyyyhhhhddddhysssso-       Memory: 2852MiB / 3841MiB 
	    `:ossssssyysssssssssssssssso:`
	      `:+ssssssssssssssssssss+-                                   
		 `-/+ssssssssssso+/-`                                     
		      `.-----..`
   ```
</details>

Test File: [default.zip](https://github.com/armory3d/armory/files/4834638/default.zip)

**Comment by knowledgenude** [comment]
Hi @IL7Games, about the problem with FPS, try to change the render path to mobile. You can keep desktop render path but you have to disable SSAO and MSAA.

If you have some problem trying to open the Armory player, please send a print of the error (in the Blender console).

I have the same problem with the forum and didn't found a way to it until now.

**Comment by IL7Games** [comment]
@knowledgenude I changed my render path to mobile and now it's going at 60 fps. But why if I leave my render path on the desktop and test it here on my notebook, the frame rate only reaches 22?

Sorry but I didn't understand what these SSAO and MSAA.

How strange, I tested the version ArmorySDK-2020-6.zip and now it's working here, maybe the problem was having put the folder in a hidden directory.

Thanks :)

**Comment by knowledgenude** [comment]
It's because mobile render path have lower system requiriments. Armory have some ready presets like Desktop and Mobile but you can change it as you want.

SSAO add a kind of shadows to the objects, you can search it on google images.
MSAA makes a blur on the object edges, it is used in low resolutions to "mask" the pixelated edges. Search for Anti Aliasing in google to see in practice how it works.

Both SSAO is expensive for low end PCs and MSAA not if you use 2x or 4x. When you select Mobile render path, you set the graphics to mobile targets, then SSAO is disabled there because phones can't handle it, i don't know about MSAA, but i think phones can handle it very well. As i say, you can perfectly use Desktop render path, but you have to reduce the graphics.

Use the "+" button to add a new render path and make your presets:

![render](https://user-images.githubusercontent.com/63247726/85903200-26ceda00-b7dc-11ea-8f28-a386bdd67cba.jpg)

I hope you have fun now!
