### ISSUE TITLE
file path special characters failure on windows

### ISSUE THREAD

**Issue by PrettyCoolPattern** [armory3d/armory#1761]
Thank you for contributing to Armory!

**Description**
file path special characters failure on windows

**To Reproduce**
Add any special characters to file path.

**Expected behavior**
Smoothness.

**System**
Blender:
Armory:
OS: Win 10
Graphics card:

**Test File**
*(drag & drop the zipped .blend file here)*

**Comment by MoritzBrueckner** [comment]
Which file path? The file path of the blender file/project? Or the path of an asset?

In general, you should avoid special characters when possible, but if you have a good example I can try to find a fix for it.

**Comment by PrettyCoolPattern** [comment]
Yes. In windows I use these characters to force some folders/files to be
displayed first through name categorization. I've worked around this by
using AAA but thought you all might like to know for an ease of access
enhancement to the application.
[image: image.png]

**Comment by MoritzBrueckner** [comment]
@PrettyCoolPattern It should work now, the problem was just that the warning that you use special characters couldn't be printed in the console anymore. So now you should see a warning and compilation should work again. Thanks for reporting :)

Please paste the error message next time, it's easier to find the cause then.
