### ISSUE TITLE
Game doesn't build if package name contains dots

### ISSUE THREAD

**Issue by SeleDreams** [armory3d/armory#1798]
**Description**
If the package name of the haxe scripts is set to a name containing dots (in this case "com.seledreams.codestars") the game won't build.
The scripts are still recognized by the engine, it seems like while the blender extensions recognizes the trait because it reads the directory of this name correctly, the build system converts the name to subdirectories
"Referenced trait file "Sources\com/seledreams/codestars/PlayerInput.hx" not found"

I did an experiment by copying the haxe file in both com.seledreams.codestars and in com/seledreams/codestars, and as I thought it worked properly this time

**fix**
It seems like the compiler is converting dots into forward slashes so the fix would be to keep them as dots

**Comment by knowledgenude** [comment]
Hi , @SeleDreams .  I think the package name (default as 'arm') is just the file termination, as .exe, .dll, etc. You can't have an executable called '.exe.xex' for example, because your OS just consider the words after the last dot. I've set the package name for 'phfa' in the pool game example, you can see in its files the termination '.phfa'. But maybe you are talking about the package name in the compiler.

**Comment by SeleDreams** [comment]
> Hi , @SeleDreams . I think the package name (default as 'arm') is just the file termination, as .exe, .dll, etc. You can't have an executable called '.exe.xex' for example, because your OS just consider the words after the last dot. I've set the package name for 'phfa' in the pool game example, you can see in its files the termination '.phfa'. But maybe you are talking about the package name in the compiler, in this case i can't change the package name too, using Android Studio.

when I talked about package name it was more the name of the haxe package rather than the name of the build
but I got the issue and in fact I think it is wanted behaviour from the devs so i'll close this issue
