### ISSUE TITLE
armory3d on 2.76

### ISSUE THREAD

**Issue by chiemillous** [armory3d/armory#1811]
Hello, I want to know how possible is it to get armory 3d working on blender 2.76. I am asking for a friend whose enthusiasm to make games with armory 3d. If not, can it be ordered?

Thank you

**Comment by luboslenco** [comment]
Hi, the latest releases only work for Blender 2.8, but you can get an older one for Blender 2.7 here https://github.com/armory3d/armsdk/releases/tag/0.5.

**Comment by knowledgenude** [comment]
Is not possible to easy get it working because of Blender 2.8 changes. But why your friend don't use 2.8? There are a lot of new features and bug fixes. If your friend have problems with performance, maybe changing Blender settings or even reducing the 3d view window size should solve his problems. :)
