### ISSUE TITLE
Node “Gate” - Execution Error (C/HL targets)

### ISSUE THREAD

**Issue by e1e5en-gd** [armory3d/armory#1814]
Thank you for contributing to Armory!

**Description**
The event "On Surface" is used for control and it is calculated in which part of the screen the click occurs:
![touch_control](https://user-images.githubusercontent.com/7114353/91393612-f38fe200-e842-11ea-889d-bee00c7d2deb.jpg)

When running Windows (Krom) and HTML5 (JS) - it works:
![krom](https://user-images.githubusercontent.com/7114353/91393684-f8549600-e842-11ea-9ab1-a3e1917503a4.jpg)

When launched on a smartphone (Android(C)), the error is, the object always moves to the left (i.s. the condition is always False):
![android](https://user-images.githubusercontent.com/7114353/91393725-fb4f8680-e842-11ea-8ad3-84c069976b3f.jpg)

User with nickname @QuantumCoderQC confirms the same error on Windows (C) target ([thread](https://forums.armory3d.org/t/android-node-gate-problem/4179/4)).

**To Reproduce**
Build a project using Windows(C), Android(C) as the target.

**Expected behavior**
The game should behave the same in both Krom, JS and C.

**System**
Blender: 2.83.4
Armory: git, master (Aug 19, 2020)
OS: Windows 10 64-bit
Graphics card: NVIDIA GeForce 930M

**Test File**
[error_coord.zip](https://github.com/armory3d/armory/files/5134311/error_coord.zip)
[APK](https://drive.google.com/file/d/1HvtV8uKH-Qqnd41VrskVrCvlOA8B3FTw/view?usp=sharing)

**Comment by knowledgenude** [comment]
I think that the problem is having integers and floats in the comparison, but if it don't behaviours the same as in Krom, maybe it need some fix

Can you test an exported APK as this: 
![fkamnf](https://user-images.githubusercontent.com/63247726/91456300-7ae85000-e859-11ea-8167-18f2fa1819ee.jpg)

I don't have android studio installed and it is pretty big to download now
[error_coord.blend.zip](https://github.com/armory3d/armory/files/5137002/error_coord.blend.zip)

**Comment by Dok-Sergey** [comment]
@knowledgenude, tried it - doesn't work.

**Comment by knowledgenude** [comment]
Can you test this just to make sure that the problem is with gate node? This also can be useful if you need a workaround on this

[MoveUsingMouseCoords.blend.zip](https://github.com/armory3d/armory/files/5138893/MoveUsingMouseCoords.blend.zip)

![test](https://user-images.githubusercontent.com/63247726/91496964-73459d00-e893-11ea-9abb-545bc5d82e82.jpg)

I installed android studio but it is returning "unknown HAXE_MODULE" error

**Comment by MoritzBrueckner** [comment]
I took a look at the generated sources and it looks like the `Dynamic` type might be the problem here.

In the .c sources it seems that the values are compared as strings, which is obviously wrong:
```c
r13 = (vbyte*)USTR("Greater");
r4 = hl_string_compare(r12,r13,r4);
```

I can't test it on android, so can you try to find out if a simple integer or float comparison works? If yes, we might fix this by tweak ing the return types of the connected input nodes.

**Comment by Dok-Sergey** [comment]
@knowledgenude, thanks for your help, this option works.

> I had installed android studio but it is returning "unknown HAXE_MODULE" error

I didn't have such an error. Sorry, I can't tell you.
My version Android Studio:
Android Studio 4.0.1
Build #AI-193.6911.18.40.6626763, built on June 25, 2020
Runtime version: 1.8.0_242-release-1644-b01 amd64
Android Gradle Plugin Version: 3.5.1
Gradle version: 5.4.1
Build Tools Version: 29.0.2
NDK: 21.3.6528147

**Comment by knowledgenude** [comment]
I've changed my OS and now Android Studio works. I did a test with this: 

![test](https://user-images.githubusercontent.com/63247726/91595664-4b5d4480-e93a-11ea-97e7-92577c3b4c91.jpg)

It works as expected, even changing the input positions in the gate node (each cube has a different trait layout)

[untitled.zip](https://github.com/armory3d/armory/files/5143375/untitled.zip)

I think that the issue is with sensor/mouse coords, and i also expect that movement coords have bugs in C targets too, because i already faced a similar thing it in  the past

**Comment by Dok-Sergey** [comment]
@knowledgenude, that's how it works. But like this, no:
![check_7_error](https://user-images.githubusercontent.com/7114353/91603410-9c3e5e80-e975-11ea-9ebf-00fe0a29f77c.jpg)

**Comment by knowledgenude** [comment]
Then problem is the value given by Separate XYZ. Also trying to compare it with a float is not working. Another workaround here that works is to put a Math node with 'round' between the separated vector and the gate node:

![test](https://user-images.githubusercontent.com/63247726/91605597-17d4e700-e947-11ea-92df-642926267591.jpg)

I couldn't understand, the problem is  with gate node and separate xyz together

**Comment by MoritzBrueckner** [comment]
I suspect that there is an issue with comparing `kha.FastFloat` values as returned by the Separate XYZ node to "regular" floats, maybe in combination with dynamic types.

Changing

```haxe
if (from == 0) return vector.x;
else if (from == 1) return vector.y;
else return vector.z;
```

in SeparateVectorNode.hx to

```haxe
if (from == 0) return cast(vector.x, Float);
else if (from == 1) return cast(vector.y, Float);
else return cast(vector.z, Float);
```

fixes the issue for me on the Windows (C) target. But that solution isn't that good probably as it discards the advantages of using FastFloats (less precision for better performance).

**Comment by knowledgenude** [comment]
But why is this happening just with the gate node? I think that in the math node the comparison is right. 

Probably don't worth to have less performance in separate xyz just for gate node, because is very common to have a lot of separate xyz in the traits. 

Maybe the  greater equal, less equal, etc. should be moved to the math node and compared in the gate node as booleans, or this is bad for performance too?

**Comment by MoritzBrueckner** [comment]
The Math node doesn't use `kha.FastFloat`, it casts the incoming values to floats at the beginning of its execution. But we can't do that with the Gate node as it should work on multiple types.
But actually, if there is a cast in the Math node I think we could also cast to float in the Separate XYZ node. Nodes are slower than self-written code anyway so maybe it's not that big of an issue to have a tiny bit slower code.

**Comment by knowledgenude** [comment]
This makes sense, at least everything will  work fine. I think Separate RGB should need this fix too

**Comment by Dok-Sergey** [comment]
I figured that the Gate node should check the input values and transform them to perform a correct comparison. Or display an error / warning, otherwise it will be "difficult" to use.
If we still think that there is an error in the separator node, then we need to rename the issue

**Comment by MoritzBrueckner** [comment]
So I found a minimal working example of the bug:

```haxe
var a: kha.FastFloat = 4.123;
var b: Float = 4.120;

// Without those two lines, both C and Krom would print 'true'
var aD: Dynamic = a;
var bD: Dynamic = b;

// Krom: true, C: false
trace(aD >= bD);
```

I've opened an issue on the Kha repo [here](https://github.com/Kode/Kha/issues/1237). If it can't be fixed, we can check for FastFloats in the Gate node and cast them to floats

**Comment by MoritzBrueckner** [comment]
Looks like it is a Haxe bug (I've opened an issue on their repo). It's probably better to find a workaround instead of waiting for it getting fixed? Even if the fix would be included in the next Haxe version, Kha would need to be updated and Armory would need to update to the latest Kha version which might take a while.

**Comment by Sanva** [comment]
@MoritzBrueckner this looks like a Hashlink bug, it's working fine with C++ — I'll take a look at it this week.

**Comment by Sanva** [comment]
This works for me using *Linux (C)* target with this change to Kha/KoreHL → https://github.com/Kode/Kha/pull/1238 .

**Comment by e1e5en-gd** [comment]
Sorry I haven't checked it for a long time.
Everything works on Android (C).
