### ISSUE TITLE
Open .hx/.py files trough the context menu

### ISSUE THREAD

**Issue by knowledgenude** [armory3d/armory#1820]
This opens .hx/.py files of the selected node with the user default text editor.

![nodecontextmenu](https://user-images.githubusercontent.com/63247726/91592305-b86ddb80-e934-11ea-982a-9d3baed2b44c.jpg)

Currently i don't know a way to open those files without searching for them  trough directories, then this can speed up node testing and be more user friendly :)

I hope Blender allow this

**Comment by N8n5h** [comment]
This should do the trick: https://github.com/N8n5h/armory/tree/nodes-context-menu
I don't have a lot of time to properly test it, so feel free to do so and tell me if it works to open a PR.

I used an existing operator to implement it, but I changed it because it opened the git version of the file, which may not be the same you have in your local sdk if you don't update it frequently. Also I purposely choose to keep it as a browser to avoid the user accidentally modifying the code and breaking their SDK (and creating sub-sequent issues about X not working), but I feel that maybe it could be changed to something else, maybe like a mini-web service to display the file as doc? (like old software used to do with their html documentation), or maybe use the version of the sdk to load the correct version from github.

**Comment by knowledgenude** [comment]
No issues running this, just a small difference between opening .py and .hx files, maybe related to my OS:

![screenshot](https://user-images.githubusercontent.com/63247726/93934308-574de380-fcf9-11ea-8597-3768384806f0.jpg)

![screenshot2](https://user-images.githubusercontent.com/63247726/93934318-5a48d400-fcf9-11ea-9e2b-892c070d401d.jpg)

And i confim that this don't work with custom nodes:

![screenshot3](https://user-images.githubusercontent.com/63247726/93934352-67fe5980-fcf9-11ea-8f93-ab5c01e46f07.png)

I can't affirm that the best is to open the files trough Browser, maybe in some cases it is better. The purpose of this is to provide a easy way to fix nodes (but this is not supposed to be frequently) and also to leave users getting examples of haxe script, or creating their custom nodes and testing it, maybe to contribute in the future too. 

I think you should send the PR, this will already be of great help :+1:

**Comment by N8n5h** [comment]
Yeah I noticed that too, with .py files firefox doesn't like to open them and instead prompts you to download them.

> I can't affirm that the best is to open the files trough Browser, maybe in some cases it is better. The purpose of this is to provide a easy way to fix nodes (but this is not supposed to be frequently) and also to leave users getting examples of haxe script, or creating their custom nodes and testing it, maybe to contribute in the future too.

Oh, ok. I thought the idea was to simply inspect the source of the node and not necessarily modify it.

Editing the source files from sdk directly could be an interesting option but I can foresee some problems with it.  First it would be problematic if the user wants to update their sdk, because they would lose all the changes they made to the files. 
Second is that if you break something (without knowing too), that problem could move to other projects that rely on the same nodes.

Maybe a better course of action (if you confirm editing the source code is something desired and not to simply inspect the code) would be doing something like armory does when you try to inspect the source of a bundled trait: it copies it directly to your project folder before opening it from there. So the original copy in the sdk is kept unedited and you can change the copy in your project. What do you think?

I will check that out when I get some more free time, before opening a PR :smiley:

**Comment by knowledgenude** [comment]
Indeed, as i said there is not too much need to use this feature to edit the existent nodes currently. 

I only think that they are a bit hard to access, and this feature would encourage new users to know how nodes work or even help contributors (in this case requires a way to edit those files).

Your PR would be welcome as it is now, but of course anyone can suggest alternative ways to do that :+1:

Thanks in advance!

**Comment by N8n5h** [comment]
Hi, I updated the branch and now it opens the browser and shows the github version of the source file. It will try to get the last commit from your .git folder but default to "master" version if it fails, https://github.com/N8n5h/armory/commits/nodes-context-menu

I tried to add an alternative behavior for custom nodes but gave up because the example in the wiki for custom nodes seems to be way outdated and causes multiple errors that I find hard to debug because I'm out of the loop with current changes to nodes :grimacing:

**Comment by MoritzBrueckner** [comment]
Thats awesome! A few things that come into my mind:

- The title/section label in the menu looks a bit like a disabled menu entry and might be a bit confusing
- When right clicking on a node, that doesn't select the node unfortunately. If no node is selected, the last selected node will be used for the new operators which might lead to a situation where one had selected a node, deselects it and then right clicks on another node which will show options for the wrong node. I'm not sure if there is a way around that.
- Maybe the operators should be at the bottom of the menu? I think this functionality is used mainly by people involved into developing
- Opening the Python sources doesn't work because the `LN` prefix is in lowercase in the opened url
- Also, just a question: does the `get_last_commit()` really return the last commit or just the checked out commit?


> I tried to add an alternative behavior for custom nodes, but gave up because the example in the wiki for custom nodes seems to be way outdated. It causes multiple errors that I find hard to debug because I'm out of the loop with current changes to nodes 😬

Can you paste the errors?

**Comment by N8n5h** [comment]
> The title/section label in the menu looks a bit like a disabled menu entry and might be a bit confusing

It seems there is not much config on labels I'm afraid https://docs.blender.org/api/2.83/bpy.types.UILayout.html?highlight=bpy%20types%20uilayout#bpy.types.UILayout.label

>When right clicking on a node, that doesn't select the node unfortunately. If no node is selected, the last selected node will be used for the new operators which might lead to a situation where one had selected a node, deselects it and then right clicks on another node which will show options for the wrong node. I'm not sure if there is a way around that.

Yes I noticed this too. That's why the only thing I could think of is a label so the user doesn't have to double check what node is selected.

> Opening the Python sources doesn't work because the LN prefix is in lowercase in the opened url

I'm not sure I understand this in particular. With what node did you test that it failed?

> Also, just a question: does the get_last_commit() really return the last commit or just the checked out commit?

I'm not sure I'm following, but this is where I got how to get the last commit without git cli https://stackoverflow.com/a/29961159

> Can you paste the errors? I've updated the wiki page a bit (there was an error in the python example), maybe that helps.

I updated the files in my test project by following the wiki and I get this. First is when opening the project file, then the repeated error is every time I open the `Add` menu option. Also the test node doesn't seem to show up when searching for it in the same menu.

```
Traceback (most recent call last):
  File "/path-to-sdk/Armory SDK//armory/blender/arm/handlers.py", line 131, in on_load_post
    blender.register()
AttributeError: module 'blender' has no attribute 'register'
search for unknown menutype ARM_MT_action_menu
uiItemM: not found ARM_MT_action_menu
/path-to-sdk/Armory SDK//armory/blender/arm/nodes_logic.py:54
search for unknown menutype ARM_MT_action_menu
uiItemM: not found ARM_MT_action_menu
/path-to-sdk/Armory SDK//armory/blender/arm/nodes_logic.py:54
search for unknown menutype ARM_MT_action_menu
uiItemM: not found ARM_MT_action_menu
/path-to-sdk/Armory SDK//armory/blender/arm/nodes_logic.py:54
```

**Comment by MoritzBrueckner** [comment]
There is [`bpy.context.selected_nodes`](https://docs.blender.org/api/2.83/bpy.context.html#bpy.context.selected_nodes) which might help finding if a node is selected at all (`active_node` might be used for shortcuts, maybe that's why nodes are active even if no longer selected). When that works you don't need to use a label anymore, instead a simple separator would be sufficient.

> I'm not sure I understand this in particular. With what node did you test that it failed?

Event > On Init. But this happens with any other node I've tested (using your latest changes as well). This is opened (which doesn't work): https://github.com/armory3d/armory/blob/24643eac51d01f4b015165266c7a5897794bde8e/blender/arm/logicnode/event/ln_on_init.py but this works: https://github.com/armory3d/armory/blob/24643eac51d01f4b015165266c7a5897794bde8e/blender/arm/logicnode/event/LN_on_init.py. I'm using Firefox on Windows 10. This might happen because paths on windows are not case sensitive so the path returned by some of the Pathlib functions might be lowercase. [This stackoverflow answer](https://stackoverflow.com/a/54984701/9985959) says that `pathlib.resolve()` does the trick of getting the correct case.

Btw, you should be able to use `NodeType.__module__` to get the value that's currently hard-coded into `source_file_name`. It returns the full module path (i.e. `arm.logicnode.event.LN_on_timer`) but a simple `rsplit('.', 1)` should solve that :))

> I don't think I'm following, but this is where I got how to get the last commit without git cli https://stackoverflow.com/a/29961159

Nevermind, it seems to be the latest (=youngest) commit on the master branch which is good (branches might not be pushed yet, usually nobody uses the fork's master branch for a PR and even if they do this functionality will be broken only then).

Regarding the error: are you sure that there is no error message before, when Blender started? To me it looks like something failed when loading the library which prevents Blender to register the category submenus.

Anyway: great work!

**Comment by N8n5h** [comment]
> Btw, you should be able to use NodeType.__module__ to get the value that's currently hard-coded into source_file_name. It returns the full module path (i.e. arm.logicnode.event.LN_on_timer) but a simple rsplit('.', 1) should solve that :))
I didn't know about that and also couldn't find anything about  __module__;  so is module == dir to the python or can it differ? 
What I mean, maybe instead of using system path I could just obtain the path from the module.

**Comment by MoritzBrueckner** [comment]
Those attributes like `__module__`, `__class__`, `__doc__` (docstring of the current function or class) etc. are possible because of the Python [data model](https://docs.python.org/3/reference/datamodel.html), it's worth scrolling to that document (Python is very powerful).

`__module__` is the full module name of the object, so indeed like the path consisting of all the packages and then the module (`toplevelpkg.sublevelpkg.etc.module`, it's that string you would write after `import`). So indeed this might help to get rid of all those pathlib usages.

Tested your changes and now everything works like a charm

**Comment by N8n5h** [comment]
About that issue with the custom node;
I noticed the first error is `AttributeError: module 'blender' has no attribute 'register'`
inspecting the code in `handlers.py` in this line it's "importing" blender, which if I understood correctly, it's referencing this file https://github.com/armory3d/armory/blob/master/blender/__init__.py right? So it's trying to call `register()` on an empty file, or there is something I didn't get right? The functionality seems to be working regardless, but that issue/"warning" may be something good to mitigate to not confuse new users.

About  the other issue, I changed the category of the node from `Action` to `Object` and that solved it but I had but a new one appeared. When inspecting the object category in the add menu, I'm greeted with this:
![image](https://user-images.githubusercontent.com/42382648/94310988-e274e680-ff50-11ea-891c-61707989b4ea.png)
and these errors when I try to click on those `Unknown`
```
Traceback (most recent call last):
  File "/Armory SDK//armory/blender/arm/nodes_logic.py", line 82, in description
    return nodetype.__doc__.split('.')[0]
AttributeError: 'NoneType' object has no attribute 'split'

location: <unknown location>:-1

Traceback (most recent call last):
  File "/path-to-blender/blender-2.83.6-linux64/2.83/scripts/startup/bl_operators/node.py", line 131, in invoke
    result = self.execute(context)
  File "/path-to-blender/blender-2.83.6-linux64/2.83/scripts/startup/bl_operators/node.py", line 122, in execute
    self.create_node(context)
  File "/path-to-blender/blender-2.83.6-linux64/2.83/scripts/startup/bl_operators/node.py", line 92, in create_node
    node = tree.nodes.new(type=node_type)
RuntimeError: Error: Node type LNTestNode undefined


location: /path-to-blender/blender-2.83.6-linux64/2.83/scripts/modules/bpy/ops.py:199
```

This is my test file project 
[dev_test.zip](https://github.com/armory3d/armory/files/5285086/dev_test.zip)

**Comment by MoritzBrueckner** [comment]
> Is there any way to difference custom nodes from the ones in the sdk with a docstring or something?

I don't know but we should implement a reliable one. It's possible with the node's module but that's a rather bad solution.

Node packages need a file called `blender.py` which is the main file of the node package and should contain all custom nodes of that package or manage importing and registering all of those nodes. But I think the documentation is missing that you need to call `arm.nodes_logic.register_nodes()` in `register()` (see [this](https://gitlab.com/koui/koui-logic-nodes/-/blob/master/blender.py) for reference). Maybe that solves your issues?

Btw, I'm currently working on a script that automatically generates the logic node reference (using docstrings) and I've already written a [script that automatically generates node screenshots](https://github.com/armory3d/armory_wiki_images/blob/master/logic_nodes/make_screenshots.py). Maybe we should add another menu entry "Show Documentation" when the work is done that links to the correct node entry in the wiki?

**Comment by N8n5h** [comment]
> Node packages need a file called blender.py which is the main file of the node package and should contain all custom nodes of that package or manage importing and registering all of those nodes. But I think the documentation is missing that you need to call arm.nodes_logic.register_nodes() in register() (see this for reference). Maybe that solves your issues?

Yes, that did the trick! I added 
```python
def register():
    arm.nodes_logic.register_nodes()
```
to the end of the blender.py file and that solved both issues, though it seems I'm still getting duplicate `Test` node entries in the add menu, so not sure what is going on.

> I don't know but we should implement a reliable one. It's possible with the node's module but that's a rather bad solution.

Yes, definitely. I tested it with a custom node now that they work and they show up and go to a 404 github page for now.

> Maybe we should add another menu entry "Show Documentation" when the work is done that links to the correct node entry in the wiki?

I added a new commit to adress that, please check it out :smile:

**Comment by MoritzBrueckner** [comment]
Great! I think we should make that call to `arm.nodes_logic.register_nodes()` in handlers.py after loading all libraries so that it is more easy to create a library, less documentation and less overhead due to multiple calls that all iterate through all nodes. I will test it and open a PR tomorrow or so.

Do you have any idea on how to implement a good way to differ between internal and custom nodes? We maybe could add a subclass of `ArmLogicTreeNode` called `ArmLogicTreeNodeInternal` or `ArmLogicNodeInternal` (probably better). If a node is a custom node, `isinstance(node, ArmLogicNodeInternal)` would be false then. The problem with this approach is that people might copy code from internal nodes for their custom nodes and would then use the internal subclass.

Maybe we should really go with the module path, that's where the nodes are and the URL is generated too according to that path. A classmethod `ArmLogicTreeNode.is_internal()` could be helpful (not tested):

```python
class ArmLogicTreeNode(Node):
    # other stuff...

    @classmethod
    def is_internal(cls) -> bool:
        """Returns whether the node belongs to Armory's default node package."""
        return cls.__module__.startswith('arm.logicnode.')
```

Your changes work great!

**Comment by N8n5h** [comment]
> Great! I think we should make that call to arm.nodes_logic.register_nodes() in handlers.py after loading all libraries so that it is more easy to create a library, less documentation and less overhead due to multiple calls that all iterate through all nodes. I will test it and open a PR tomorrow or so.

Ok, looking forward to it! :smiley: 

> Do you have any idea on how to implement a good way to differ between internal and custom nodes?

Maybe code injection when loading the blender.py file to add a discriminator to custom nodes? I would go with that and see if it doesn't affect performance too much or if it can be done reliably.
Although I will try your method as well.
