### ISSUE TITLE
Get Child returns the parent name

### ISSUE THREAD

**Issue by knowledgenude** [armory3d/armory#1845]
`Parent` and `child` names starts with `Cube`. The node returns only the parent name. Both objects are deleted because when the parent is deleted, child is too.

[getchild.zip](https://github.com/armory3d/armory/files/5183653/getchild.zip)

**Comment by QuantumCoderQC** [comment]
Thank you for reporting @knowledgenude 

This behaviour of the logic node is because the code searches for the children's' children too. Not just one layer of child objects but every layer. 

I guess this will cause confusion since even if an object has a child with a particular name, another object somewhere at a lower level will be returned. 

![image](https://user-images.githubusercontent.com/55564981/92477049-39a05a80-f1e0-11ea-88dd-99d5162237a3.png)


In the example above, the user might expect to get the object `C` at `Layer 1` but instead gets `C1` at `Layer 2`. 

One way to solve this is to remove the search for children's children and instead use the search node again on the child object. I can make changes if there are no objections.

**Comment by knowledgenude** [comment]
For me i don't see any need to search for the "child child". If this is  required, just use a node for search the child of the parent and another to search for the child of the child.
