### ISSUE TITLE
Draw order issue

### ISSUE THREAD

**Issue by knowledgenude** [armory3d/armory#1933]
This is happening when you use `Draw Order: Distance` with a lamp in the scene:

![Screenshot from 2020-10-15 09-54-52](https://user-images.githubusercontent.com/63247726/96129152-a76d2f80-0ecc-11eb-84b1-a1b676373115.png)

[draworderissue.zip](https://github.com/armory3d/armory/files/5384973/draworderissue.zip)

**Comment by MoritzBrueckner** [comment]
Looks correct for me:

![draworder](https://user-images.githubusercontent.com/17685000/96139162-da301b80-0efe-11eb-8792-520e17425202.png)

Actually, `Draw Order: Auto` also defaults to `Distance`.

On what system/graphics card do you run this?

**Comment by MoritzBrueckner** [comment]
Hmm, I still cannot reproduce this (tested with DirectX and OpenGL), maybe it's something with AMD graphics cards?

> Using `Draw Order: Shader` works fine, do you know if there is some performance difference between this two options?

I'm pretty new to computer graphics so don't trust me, but my guess is that when choosing `Shader` for the drawing order, all objects with the same shader are drawn in a row to reduce the amount of context switches (shader pipelines need to be changed which takes a lot of time because the CPU has to wait for the GPU I think). So I think that using shader order should be faster when you have many objects with the same material in a scene (it's always better to test it! Don't trust me^^!). On the other hand, sorting by shader is problematic when using transparent materials, in this case sorting by distance is much better (see http://www.opengl-tutorial.org/intermediate-tutorials/tutorial-10-transparency/).

**Comment by knowledgenude** [comment]
I don't know exactly what is the problem for now. I don't remember it happening in other OS with the same hardware, but anyway i will have to update the OS version in a few days when it have a stable version, hence the drivers may change and i will see if the problem still. I will keep this open before i change the OS, this way other people can confirm or not the issue.

The information you send looks trustworthy, probably it will be also useful in the future and for other users, thank you very much as always :+1:

**Comment by e1e5en-gd** [comment]
I'm also fine:
![it_work](https://user-images.githubusercontent.com/7114353/96339583-56ad3080-109e-11eb-8d5f-f756a313b524.jpg)


OS: Windows 10 64-bit
Graphics card: NVIDIA GeForce 930M

**Comment by knowledgenude** [comment]
It was probably related to drivers. After updating to Fedora 33 today, it is working fine. :+1:
