### ISSUE TITLE
When the project contains custom nodes, node buttons wont work

### ISSUE THREAD

**Issue by knowledgenude** [armory3d/armory#1975]
When i  try to add an input to `Gate` or `Switch` node:

![Captura de tela de 2020-10-30 13-39-55](https://user-images.githubusercontent.com/63247726/97732592-805e5280-1ab5-11eb-953c-949e831a8789.png)

Also the categories are created using the nodes names: 
![Captura de tela de 2020-10-30 13-41-11](https://user-images.githubusercontent.com/63247726/97732677-9ec44e00-1ab5-11eb-802f-047be8dbf660.png)

Is not better to have a "default" category for empty categories?

**Comment by MoritzBrueckner** [comment]
Regarding the first error: I can't reproduce it, are you using the latest master without local changes?

> Also the categories are created using the nodes names

Hm, that shouldn't happen. How does the folder structure of your package look like?

Using a default category works and it exists, but currently all nodes (if not stated otherwise) will use the package name as the category name. This makes it very easy to move nodes in Armory and other libraries and if libraries don't use packages to organize nodes, the library name will be used (as long as there is a `__init__.py` file, this might be the problem)

**Comment by knowledgenude** [comment]
The folder structure uses the same as community ln, here is the example file: [PlayerController.zip](https://github.com/armory3d/armory/files/5466968/PlayerController.zip)

The second issue is not a real problem.

If the folder structure of the custom nodes and other libraries may change with updates, is not better a button for "generate" this libraries folder and the user just places its nodes, etc? How much this is possible without overwriting this nodes?

**Comment by MoritzBrueckner** [comment]
Added some fixes at https://github.com/armory3d/armory/pull/1979, good catches 👍 

About the category name: because most logic node definitions are bundled in `logicnode_definitions` packages, this will be the new category name. However, you can rename this package and add more packages just as you want, or set the category via `arm_category` as you want.
