### ISSUE TITLE
Make a professional document, similar to animation node or presentation document

### ISSUE THREAD

**Issue by 2655251820** [armory3d/armory#2041]
There are too few teaching resources, and even some learning cases will run incorrectly. Some logic nodes do not know what they can do for beginners. Hope that there are similar documents like animation node to tell users the correct way to use them. Especially if you want to create some complex logic, there is no way。
  Otherwise, novices have no way to learn and use, because there is no correct specification, some problems will be regarded as bugs. I have waited for two years and have not resolved it, whether it is related to the new teaching and related teaching, it seems dead. I hope that I can rely on logic nodes to complete the production of small games, so that more people can play games without learning to write programming as much as possible, because many people are interested in games but will not be a career, and learning programming takes too much time.
I am really disappointed, because I have also seen that some people in my country want to promote this addon, but there is no way, because there is no operation specification, there is no way to effectively solve the problem of the logic node, and it can only destroy the enthusiasm.
I hope you don’t mind, but I hope you can pay attention to this issue

**Comment by MoritzBrueckner** [comment]
Hi,

I totally agree with you that Armory needs more documentation and up-to-date tutorials.

Armory is mostly developed by people who contribute in their spare time for free, not for profit but because we like to code and to improve Armory. This means that the time we can spend in making Armory better is very limited and writing documentation is a slow and tedious process. Don't get me wrong, that's not an excuse for not writing documentation, it's just the way it is and we try to constantly update the documentation nonetheless.

There is a monthly updated logic node reference in the wiki: https://github.com/armory3d/armory/wiki/reference. It's not the most detailed one but it should give you enough information to know which logic nodes to use for what purpose. If in doubt and if you know Haxe you can always look into the node's source code, some more special nodes require Haxe knowledge anyway (most of them are in the `Native` category).

If you know how Armory works, you can help a lot by creating tutorials, maybe even in your native language so more people get involved. To us contributors: we should always think about updating the documentation after a PR is merged so that it gets more complete over time.
