### ISSUE TITLE
shader/renderer

### ISSUE THREAD

**Issue by zartan9** [armory3d/armory#2057]
Hi im new to armory and came across this shader.... Since armory uses its own renderer, would this shader be seen? any work around? thanks

" https://blendermarket.com/products/painterly-shader/docs
The second node works flawlessly with both EEVEE and Cycles. I am not entirely sure about armory, but if it supports all the 2.8x nodes like the regular blender version then it should work fine. If you don't need rim light then you can skip it entirely, as most of the work is done by the base color generator anyway."

**Comment by knowledgenude** [comment]
I suspect it will work, but if you plan to use only the baked textures you can purchase it without doubt. Otherwise I recommend you to test at least the main nodes first, like i do here with vertex colors: [vertex-col.zip](https://github.com/armory3d/armory/files/5698279/vertex-col.zip)
And you can make some adjustments if the node group don't work properly.

**Comment by zartan9** [comment]
thanks! also, is there a spot on here to hire help for my game Im trying to make? Im so new to this. Well thanks.

**Comment by MoritzBrueckner** [comment]
Not here on Github, but there is the [forum](https://forums.armory3d.org/) and we also have a [Discord server](https://discordapp.com/invite/axq6qWV), you're welcome to join :)
