### ISSUE TITLE
Particle emitter and instanced models - Material Popping visual issue

### ISSUE THREAD

**Issue by onelsonic** [armory3d/armory#2072]
if you have custom GLSL shaders like this example here :
https://github.com/armory3d/shader_pack/tree/master/Shaders

then when adding a particles emitter the custom shader will be broken.

Can this be related this property ? "update=assets.invalidate_shader_cache" :
https://github.com/armory3d/armory/blob/4038a67385d3cc0d92d1455f991820c62129eee3/blender/arm/props_renderpath.py#L494
The shader will pop out with wrong vertices and ghost meshes all over the place.

**Comment by MoritzBrueckner** [comment]
Hi, thanks for report :) Do you have a small example file for this? Also, are there any error messages in the console (Blender or browser)?

The line you've mentioned is not likely to be related to this bug. It ensures that the shader cache is deleted when you change the particles property (=> the shaders will be recompiled upon building the game).

**Comment by onelsonic** [comment]
I did others tests and exporting with Krom doesn't work neither in fact.

Below is what I mean, see the artifacts popping in the grass shader (bottom left)
![Animation_2020-12-28-12-46-36](https://user-images.githubusercontent.com/53947594/103212838-402c1c80-490c-11eb-9b62-a2f08bfdcabc.gif)

(also applying the particles system modifier does not affect anything)

Here is the Blend file :  https://github.com/onelsonic/armory_tests/blob/master/particuleswithshaderbug.7z?raw=true
Here is a live demo : https://onelsonic.github.io/particuleswithshaderbug/index.html
(Similar artifacts appears if exporting to Krom)

**Comment by QuantumCoderQC** [comment]
Thanks for the example, I tried it out and I get a different behavior on Krom. In Krom, the grass disappears and appears at random when camera is at a certain position

![bugKrom](https://user-images.githubusercontent.com/55564981/103224993-31a02e00-4929-11eb-8c07-d581af63c4e1.gif)

**Comment by MoritzBrueckner** [comment]
Did some tests and the flickering grass @QuantumCoderQC describes only happens when there is at least one of the particle systems in the scene, but depending on what particle system is deleted other grass objects are not drawn (the grass in front flickers when the yellow particles exist, when only blue particles exist grass in the background flicker).

What irritates me is that Renderdoc displays less draw calls when the flickering grass isn't visible but the debug console shows a constant amount of draw calls and culled objects. Maybe there is a full buffer somewhere?

**Comment by onelsonic** [comment]
from my understanding Blender was using some visible triangles when you were scattering instanced objects in a scene, these triangles were responsible for all the transforms (scale, positions, rotations) of the instanced objects.
I think it is the same in the new Blender but these triangles are hidden. These triangles should also be hidden in runtime (en maybe removed?), and that what Armory is doing incorrectly I supposed, 
when we add a particules emitter.

**Comment by MoritzBrueckner** [comment]
@onelsonic I don't think that Armory exports some hidden internal Blender triangles if they should exist. Blender probably doesn't expose them in the Python API.

**A few other observations:**

When printing out the position of all non-instanced draw calls in a frame (remember: the flickering grass objects belong to `grass 4` for which instancing is set to `Off` in the file), the amount of calls to `g.drawIndexedVertices()` turned out to be varying depending on the amount of visible grass (The printing takes place [immediately before this line](https://github.com/armory3d/iron/blob/a2d8e4280ae5ad2e50f017a2dc6d5fa3cf61301e/Sources/iron/object/MeshObject.hx#L309)). But because the reported amount of draw calls in the debug console stays constant (which is incremented [after the for loop](https://github.com/armory3d/iron/blob/a2d8e4280ae5ad2e50f017a2dc6d5fa3cf61301e/Sources/iron/object/MeshObject.hx#L317) in [line 265](https://github.com/armory3d/iron/blob/a2d8e4280ae5ad2e50f017a2dc6d5fa3cf61301e/Sources/iron/object/MeshObject.hx#L265)), I guess that the length of `ldata.geom.indexBuffers` varies... Maybe the draw call counting should be moved inside the for loop to ease debugging those issues?

**Comment by QuantumCoderQC** [comment]
@MoritzBrueckner That's quite interesting. Thanks for your observations.

I prefer having just the warning, and probably a suggestion in the warning to use a different material. This will give maximum control to the user.

**Comment by onelsonic** [comment]
I rebuilt this file with only one grass model and it seems like this meshs popping effect appear whenever you have in your scene :

- [ ] a particles emitter 
- [ ] instanced models 
- [ ] and the original model present in the scene.

If you have a game that need to spawn many instanced 3d models like shooting bullets, having the original model present in the scene is breaking the particles emitter.
 
 I think it might be better to find why the `ipos` uniform is not passed to all objects, and pass it to the object that should get it.
 Otherwise all methods using instanced objects will need to be rewritten.

**Comment by MoritzBrueckner** [comment]
It happens because the instancing is incorrectly set up in the file (some objects (`grass 4`) do not use instancing, so there simply is no value for `ipos`). Here it is described how to enable instancing the right way: https://github.com/armory3d/armory/wiki/instancing.

I opened a PR so that in cases like this a warning is displayed: https://github.com/armory3d/armory/pull/2076.

Thanks for reporting, as always 👍

**Comment by onelsonic** [comment]
Thanks @MoritzBrueckner makes sense now.
I deleted / re-scatter the grass many times and did not reconfigure the Armory instancing properties.
A warning will be super welcome for this. Great for spotting it.
