### ISSUE TITLE
Normal map cannot be used when using bone animation

### ISSUE THREAD

**Issue by sachopu** [armory3d/armory#2100]
Thank you for contributing to Armory!

**Description**
When you apply an action to a mesh with bones applied, the material turns black.

**To Reproduce**
Occurs when connecting an image to a normal map node and connecting to a normal shader.
There is no problem if you connect the bump to the normal shader.

**Expected behavior**
Animation of objects adapted to materials including normal maps
No problem with Armory SDK 2011.
There is a problem from Armory SDK 2012 or later.

**System**
Blender: 2.83.8
Armory: 2101
OS: Windows 10
Graphics card: GTX1060
[NomalmapBlack.zip](https://github.com/armory3d/armory/files/5918988/NomalmapBlack.zip)

**Test File**
*(drag & drop the zipped .blend file here)*

**Comment by MoritzBrueckner** [comment]
Thanks for reporting! Will be fixed in https://github.com/armory3d/armory/pull/2101.

---

There was a wrong statement order in the generated vertex shader code in `Material_armskin_mesh.vert.glsl`:

```glsl
vec3 bitangent = normalize(cross(wnormal, tangent));
TBN = mat3(tangent, bitangent, wnormal);
wnormal = normalize(N * (vec3(nor.xy, pos.w) + 2.0 * cross(skinA.xyz, cross(skinA.xyz, vec3(nor.xy, pos.w)) + skinA.w * vec3(nor.xy, pos.w))));
```

`wnormal` is used before it's set, thus it's still filled with zeroes and the cross product in the first line above gives a NaN output. I guess this was the problematic commit: https://github.com/armory3d/armory/commit/b49bd549012bd3ddd38986541b8a84941f8a4203.
