### ISSUE TITLE
How does this GE behaves on low-end system?

### ISSUE THREAD

**Issue by UltraBurstXD** [armory3d/armory#2103]
Hi, I want to start using this GE for game development on my small indie company, but first I want to know how it behaves on low-end systems with 4GiB to 8GiB RAM? I want to stick in simple games for time being, and I'll progress with time. And, I use Ubuntu 20.10 for programming, it's good OS for that after macOS.

**Comment by SunDaw** [comment]
A question like this is inherently nearly impossible to answer, since a large part of the behavior will depend on what your game does. Armory itself is very configurable (including different render paths, quality options and 2 different physics engines), so you should be able to adjust these to work well with your particular game.
And since the engine itself is open source you can also fix any issues or performance problems you find yourself (and ideally merge back into this repository so others can benefit from it as well)

**Comment by UltraBurstXD** [comment]
Alright, thanks for the answer.
