### ISSUE TITLE
kraffiti crash processing HDR file

### ISSUE THREAD

**Issue by ja-moli** [armory3d/armory#215]
Hello. It must be my destiny to help this example get fixed. I apologize if any other has reported this previously, I have not checked the forums.

I have downloaded scene 4 available on downloads, and appart from my Linux pc, I have one with windows 10.
In the one with windows 10, when I simply try to render the project, it says Kraffity breaks.

![1](https://user-images.githubusercontent.com/12383027/29024627-437412cc-7b73-11e7-9c5e-ae857e4dec2c.jpg)

Then, it says this.

![2](https://user-images.githubusercontent.com/12383027/29024639-4b7bc26c-7b73-11e7-8ba9-005e1a8458c0.jpg)

And the console says this.

![3](https://user-images.githubusercontent.com/12383027/29024650-53df5c5c-7b73-11e7-88b1-27806e62db62.jpg)

My pc is
Intel core i7 4770
16 gig ram
Amd 380 with latest drivers whql 17.7.2 from July 2017

I reaally would love to not to see this error again in beta 12. This is the third time I battle versus scene 4.

**Comment by luboslenco** [comment]
Can not get to reproduce this for the life of me. Nonetheless I am updating the kraffiti tool for build 12, maybe we will get lucky. Otherwise I will have to test on more machines.

**Comment by ja-moli** [comment]
So I will see what happens In v12 then.

**Comment by Naxela** [comment]
After spending some time getting slightly annoyed at why this kept happening randomly with the same files, I decided to try out some different stuff, only to find out the reason it's breaking is most likely because Kraffiti doesn't like space characters. I noticed ja-moli's example have the same problem.

I've uploaded a folder with examples files, where one crashes and another one doesn't.
[Kraffiti Error.zip](https://github.com/armory3d/armory/files/1379596/Kraffiti.Error.zip)

![kraffiti_2](https://user-images.githubusercontent.com/5429817/31500881-04249af4-af69-11e7-9e96-000237d113a4.png)

![kraffiti_3](https://user-images.githubusercontent.com/5429817/31500893-07e1982c-af69-11e7-8513-299a512167d9.png)

Lubos can you reproduce this?

**Comment by luboslenco** [comment]
@Naxela thanks for an excellent investigation! I did some plumbing and now the `HDR Breaking.blend` appears to be working too! Hopefully one of the most annoying bugs now gone in the upcoming build 14. :)
