### ISSUE TITLE
[Logic nodes] New node "Count executions".

### ISSUE THREAD

**Issue by ItsCubeTime** [armory3d/armory#2203]
A node that counts how many times it has been executed.

Also has an option to reset the counter, here we could for instance plug in a "On update" node set to "Late Update" to have the counter reset every frame. However its up to the user when he/she desires to reset it ofc.

![image](https://user-images.githubusercontent.com/20190653/118655633-0475ee80-b7ea-11eb-9833-836d141af127.png)

If the "Count starting from 1 (int)" output is attempted to be read before the node "In" pin has ever been called, it should return 0 to allow for creative use cases ;) .

**Comment by knowledgenude** [comment]
Hello @ItsCubeTime , i think this node wouldn't be very useful afaik, because you can do that using the set variable node just by adding +1 when the set variable node is called and set to 0 when some other condition. And plus it will allow more flexibility and can be saved in **save games** etc.

The same here: if you need examples i can send to you :)

**Comment by QuantumCoderQC** [comment]
I agree here with @knowledgenude. If a function can be achieved with a few nodes with ease, then there is no point in having a specific node for that specific task. Of course it might be easy, but this brings a question if there must be a a node for everything.

**Comment by onelsonic** [comment]
or you can code your game loop in just HAXE code

**Comment by ItsCubeTime** [comment]
Considering the critisism, would a node like this get rejected from being merged if I made a pr for it?
