### ISSUE TITLE
Node replacement option not available in 2.93 Blender

### ISSUE THREAD

**Issue by QuantumCoderQC** [armory3d/armory#2209]
**Description**
The node replacement option to test new nodes can no longer be invoked in Blender 2.93 versions. It was an option to search for "Replace Nodes" and invoke it to replace nodes with newer versions.

**To Reproduce**
In Blender, simply search for "Replace Nodes"

**Expected behavior**
Replace nodes option must appear and replace all to newer versions when invoked.

**System**
Blender: 2.93
Armory: Armory v2021.5 ($Id: 99497c80048d5b0614144ab4b87fb2303e416be2 $)
OS: Windows 10

**Comment by MoritzBrueckner** [comment]
Weird, I still have it: 
![](https://user-images.githubusercontent.com/17685000/119205099-8f2f4580-ba97-11eb-94e3-c65965b1c196.png)

Make sure that your mouse cursor is over the node editor, otherwise the operator poll will fail.

**Comment by QuantumCoderQC** [comment]
Hmm, yes it is weird.

The node replacement doesn't appear even if my cursor is in the node editor. Maybe I have to reinstall Blender or delete the configuration file?

will try a few and get back

**Comment by MoritzBrueckner** [comment]
Doesn't look like it's caused by the poll function, nothing was changed there and it looks correct:

https://github.com/armory3d/armory/blob/3b72fff76d98710b25dbd8aa044dd4c4fd2de20a/blender/arm/nodes_logic.py#L360-L362

Maybe it's caused by what is described in the first paragraph here: https://wiki.blender.org/wiki/Reference/Release_Notes/2.90/Python_API ? Then it could maybe help to add an entry to the operator to the menu bar in the header.

**Comment by QuantumCoderQC** [comment]
I still couldn't get it to work, unfortunately. I tried the following but no luck:
1. re-install the addon.
2. Clear all user preferences in AppData and re-install Armory addon.
3. Tried the latest build of Blender 2.93 Beta. 

> Then it could maybe help to add an entry to the operator to the menu bar in the header.

Yes, this should be a better course of action.

**Comment by tong** [comment]
The node replacement procedure not only fails on every armory_examples project.
```
ERROR: There were errors in the node update procedure
```
But also messes up the logic nodes by creating unconnected, duplicate nodes like:

![armory_logic_nodes-update_error](https://user-images.githubusercontent.com/203646/126638153-131c132a-ca0a-4b2c-b200-5a0068cf2c23.png)

This feature should be turned off until fixed, imho, maybe just spitting warning messages in the meantime.

**Comment by MoritzBrueckner** [comment]
Yes, this is because some nodes have wrong or no update procedure, it's not that much of an issue of the replacement system in general. For example the input node enums have changed their value IDs (title case to lower case or so IIRC) and their update procedure doesn't take that into account.

So some nodes need to get updated in that regard and the replacement system itself should probably remove new duplicate nodes if they couldn't be updated correctly.
