### ISSUE TITLE
[Logic nodes] Add node inputs for the Gamepad & Keyboard nodes for swappable controls as well as a "Wait for input" node.

### ISSUE THREAD

**Issue by ItsCubeTime** [armory3d/armory#2215]
This would be useful for creating keybinding menus where the players can change the controls to there preference.

The idea is that the "Wait for input" node would stop execution until any key (or gamepad button) is pressed & then provide a node output (either a string or an enum, or whatever type/class is used in the Haxe code for controls currently) for the key that was pressed.

This output could then be hooked up to a set variable node, of which variable could then also be hooked to a "Gamepad" & "Keyboard" input event node allowing the programmer to implement - lets say a menu for swapping in-game hotkeys.

![image](https://user-images.githubusercontent.com/20190653/119843657-09ccea80-bf08-11eb-97f5-f4b82879a8ed.png)
The reason for adding a little dot next to the "Down" dropdown is to also allow for letting whether the input node should execute on tick when the given key/button is pressed, on release or start, this would probably be a spearate type or maybe just an integer switch.

![image](https://user-images.githubusercontent.com/20190653/119845217-5e249a00-bf09-11eb-9f5a-8b1b7bca5d1c.png)

**Comment by knowledgenude** [comment]
I guess this requires another socket type. I tought i could reuse Action socket type but it is different and i am still analphabet in python to do that. I think as the Action socket is supposed to work with strings, the default value (strings array) should be selected as default value in the node .py to allow reuse.

I personally see a good oportunity to extend the array management through nodes (the hability to add/remove/select elements directly on the node (on user level) and  choose default elements in the respecive  .py.

Obviously the add/remove option need to have a way to disable in the .py for nodes like the input/action. This is just an idea, dont know if is possible.

**Comment by ItsCubeTime** [comment]
Thanks for picking this up! please do let me know if you progress any further :)

**Comment by knowledgenude** [comment]
@ItsCubeTime , i've started to work on that, see here: https://github.com/knowledgenude/armory

I've removed the Gamepad/keyboad started nodes, because they would require a released option too (i need to stop doing things while im sleepy). And `any key` pressed doesn't makes too much sense as you wouldn't expect a user to use "esc" key to jump or etc. so you can just add all keys you want to the input map and see if any of them was started/released.

The node design must be improved to hide unused inputs, unfortunately i don't know how to do that yet :) I'm looking for other sugestions. In case i change the InputMap class later, these nodes should stay compatible.

# Added nodes: `On Input Map` and `Set Input Map`

**Comment by MoritzBrueckner** [comment]
> And any key pressed doesn't makes too much sense as you wouldn't expect a user to use "esc" key to jump or etc. so you can just add all keys you want to the input map and see if any of them was started/released.

There still might be use cases for it, for example the common "Press any key to continue"  message before main menus in games. Or maybe the user wants to listen for key presses in general to let players type in something (their name or whatever).

> The node design must be improved to hide unused inputs, unfortunately i don't know how to do that yet :) I'm looking for other sugestions.

Can you elaborate a bit what you mean by that? I've implemented some custom sockets [here](https://gitlab.com/koui/koui-logic-nodes/-/blob/master/definitions/_sockets.py) and Armory itself has some ([source](https://github.com/armory3d/armory/blob/master/blender/arm/logicnode/arm_sockets.py)), maybe that can help you.

**Comment by knowledgenude** [comment]
> There still might be use cases for it, for example the common "Press any key to continue" message before main menus in games. Or maybe the user wants to listen for key presses in general to let players type in something (their name or whatever).

I will make a PR for that again, but  this time with `released and started` options, thanks for the use example! Do you think i should create a node for each input type (i.e. `Get Keyboard Pressed`, `Get Gamepad Pressed`...) or just a property to select the type? Also name suggestions are **good** :sweat_smile: 

> Can you elaborate a bit what you mean by that? I've implemented some custom sockets here and Armory itself has some (source), maybe that can help you.

The `Set Input Map node` have **two properties**, one for `input type` and other for `operation` (add, replace or remove by key). I would like if i select the replace key operation, the replace key input appear and hide otherwise. I tryed to mimic this from gate node  but i got problems (maybe i can do it again and post to someone see what is wrong). Also the deadzone input shouldn't be displayed for keyboard, only for mouse and gamepad.

If a singular node for each operation/input type is better, i would do it :) I just fear it can overbloat too much...

I don't think is a good idea to leave nodes like `On Keyboard`, `On Input Map`, etc. with self updates, maybe is better a `run input` for them? So users can choose the update rate (at least for `On Input Map` should have significant performance impact). In that case i would create a new node for this and deprecate the old ones.

I asked about the custom input socket but was for the **Keyboard, Gamepad and Mouse nodes**, because if i just add an input there, users will need to know the key name (no list for select it, and i don't know if this is even possible to do).

One question regarding the input class: should all input types have the SAME variables even if they don't use it? (i say that because the `index` and `deadzone` variables). If yes, then the things will be easier

Sorry for ask too much, i don't feel secure as this is not a thing that only me will use. Feel comfortable to do any appointments!

**Comment by MoritzBrueckner** [comment]
> Do you think i should create a node for each input type (i.e. `Get Keyboard Pressed`, `Get Gamepad Pressed`...) or just a property to select the type? Also name suggestions are **good** 😅

That's a good question... I think having something like a mask where you could toggle individual input types would be cool, but on the other hand it could make the logic node complicated to use. Maybe having just a checkbox called "Any" on the already existing nodes is totally sufficient and there would be no need for redundant code. Then the key/button/etc selection could be hidden if "Any" is selected and a new output would appear that outputs the key.

> I would like if i select the replace key operation, the replace key input appear and hide otherwise.

That can be a bit complicated. There are some helper operators [here](https://github.com/armory3d/armory/blob/616a0e230da6a69e8aeb3f0494ac384806b606ac/blender/arm/logicnode/arm_nodes.py#L111-L294), but depending on the use case it can get more complicated and you have to use the Blender API ([`NodeInputs`](https://docs.blender.org/api/current/bpy.types.NodeInputs.html)). I think by now there is even the possibility to disable node sockets without hiding them, that could be a solution as well even if consistency with other nodes is important.

If the hide/show socket operations are too complicated you can also just clear everything and then recreate the sockets. However this will remove some connections.

> I don't think is a good idea to leave nodes like On Keyboard, On Input Map, etc. with self updates, maybe is better a run input for them? So users can choose the update rate (at least for On Input Map should have significant performance impact). In that case i would create a new node for this and deprecate the old ones.

I don't think that's a good idea, it would make simple use cases more complicated by introducing yet another node connection that has to be made. For your new node it could make sense though, if you say that the performance is not so good. But maybe there are ways to improve the performance first.

> I asked about the custom input socket but was for the Keyboard, Gamepad and Mouse nodes, because if i just add an input there, users will need to know the key name (no list for select it, and i don't know if this is even possible to do).

Not necessarily, you can combine the current dropdown with an input socket, but you would need your own socket class for that to be able to define the dropdown draw function. This socket can be connected to other output sockets that "emit" key names and you could even add some nodes that let the user select from the dropdown and then convert that to a key output.

> One question regarding the input class: should all input types have the SAME variables even if they don't use it? (i say that because the index and deadzone variables, Keyboard for example don't have it). If yes, then the things will be easier

Sorry, I don't quite understand what you mean. Do you mean the InputMap class?

> Sorry for ask too much, i don't feel secure as this is not a thing that only me will use.

Nothing to worry about, I also feel insecure a lot about those things, it's easy to think too complicated and on the other hand it's easy to over-engineer things and to find the right balance can be really difficult.

**Comment by knowledgenude** [comment]
> Sorry, I don't quite understand what you mean. Do you mean the InputMap class?

I mean that the `InputComponent` class should have only fields that all its childs share (at last that is how i see this pattern), so it ends like that:

`InputComponent`: Key, scale
`KeyboardComponent`: Key, scale
`MouseComponent`: Key, scale, deadzone
`GamepadComponent`: Key, scale, deadzone, index

But that makes everything worst to figure out, because i can't set the index of gamepad component if it is "mapped" as `InputComponent`. The only solution i found is to put all that fields in the `InputComponent` class and ignore the fact that some childs don't use specifics fields. I don't know if there is some unnecessary use of memory on having unused fiels in the class but i suppose the best for now is to leave as that, but looks like it is something i may fix later.

I've pushed a commit to the `InputMap` and added a way to `copy` and set the `index of the input` (only used by gamepad class yet). So in case has two players, then just copy the `input map` of player 1 and set a different index for it, right?

For the nodes i will create the way i think is good taking the considerations you made in count and send prints after all done to get opinions. Thanks as always for your great help!

**Comment by MoritzBrueckner** [comment]
> But that makes everything worst to figure out, because i can't set the index of gamepad component if it is "mapped" as `InputComponent`

That depends on what you do with the component. Do you know in advance what type of component you have stored? Then you could just cast it to the right type. Otherwise, yes it could make sense to move deadzone and index to the super class, I don't think that it takes away much memory (there aren't many instances of those classes right?).

> So in case has two players, then just copy the input map of player 1 and set a different index for it, right?

Sounds good 👍

**Comment by knowledgenude** [comment]
That is because of how is **Iron Input** class design, in other case i would just move the **input** field to the base class (InputComponent). So i would just set this field for each InputComponent child (i.e. gamepad.input = Input.getGamepad(), keyboard.input = Input.getKeyboard())... That doesn't works because started/released/down methods are not in the base class in Iron, so for while the best is to keep as it is (all fields in the base class).
