### ISSUE TITLE
compiling API errors with OnCanvasElementNode and GetBoneFkIkOnlyNode nodes

### ISSUE THREAD

**Issue by onelsonic** [armory3d/armory#2229]
I was unable to compile the API documentation on windows (https://github.com/armory3d/armsdk/tree/master/api)

These two nodes are returning errors. I guess they need some edits : 

https://github.com/armory3d/armory/blob/master/Sources/armory/logicnode/OnCanvasElementNode.hx
`../armory/Sources/armory/logicnode/OnCanvasElementNode.hx:7: characters 8-18 : Type not found : zui.Canvas`

https://github.com/armory3d/armory/blob/master/Sources/armory/logicnode/GetBoneFkIkOnlyNode.hx
`../armory/Sources/armory/logicnode/GetBoneFkIkOnlyNode.hx:26: characters 21-34 : iron.data.TObj has no field is_IK_FK_only (Suggestion: is_ik_fk_only)`

**Comment by knowledgenude** [comment]
The first error is not related to the node, it is because the Zui library is not loaded. I need to force enable it like that:

![Screenshot from 2021-06-13 21-44-25](https://user-images.githubusercontent.com/63247726/121826926-a6291800-cc90-11eb-820f-3716ef3878d0.png)

I don't know how to enable it for the API compilation, maybe someone could help you on that.

The second error should be fixed in https://github.com/armory3d/armory/pull/2231
