### ISSUE TITLE
Playback / callback failed

### ISSUE THREAD

**Issue by knowledgenude** [armory3d/armory#2234]
Edit: Sorry for the wrong description, i was out of time. 

I've tested it again and seems that this error happens when the `Audio.play()` function is called too much before the sound is finished. In the example i only had connected an update node because the sound is short. In case the sound length is 5 seconds for example, even with a delay of 2 seconds between the calls, the error also happens. Maybe some limit is reached, but i will keep this open as i don't have sure.

The type error happens because the `play()` function is returning a `null` value that is going to the channels array in the `update` function of https://github.com/armory3d/iron/blob/master/Sources/iron/object/SpeakerObject.hx

By filtering the null value the type error is fixed, but no audio is played anymore. This looks a low level issue.

[Test file](https://github.com/armory3d/armory/files/6678693/test.zip)

Error message:

```
playback callback failed (delivered -32 / 4116 frames)
poll failed (Success)
Trace: TypeError: Cannot read property 'get_finished' of null
    at iron_object_SpeakerObject.update (<anonymous>:16736:9)
    at iron_App.update (<anonymous>:2908:27)
    at kha_TimeTask.task (<anonymous>:24237:3)
    at Function.kha_Scheduler.executeTimeTasks (<anonymous>:24120:75)
    at Function.kha_Scheduler.executeFrame (<anonymous>:24070:17)
    at kha_SystemImpl.renderCallback (<anonymous>:24851:16)
```

**Comment by MoritzBrueckner** [comment]
Hi,

this probably happens becausethe amount of channels Kha can play simultaneously are hard-coded:
https://github.com/Kode/Kha/blob/26f60707af9dbe25f2f6ecd33d5af49291450e08/Sources/kha/audio2/Audio1.hx#L9

If there are 32 channels already taken, no new channel can be allocated and `null` is returned instead. So for now, it seems to be the best to filter the null value as you stated (see https://github.com/armory3d/iron/pull/129). Do you have no playback at all in this case? For me it works, but it stops after a while until the 32 channels are free again (when the sounds have played).

There are a few possible solutions for those cases when no channel is available:
- Make Iron's audio playback independent of Kha's playback. This requires some work.
- Allow to re-trigger a single sound, so instead of creating a new channel for each sound, (optionally!) re-use the same channel and simply reset its playback position to the beginning.

**Comment by knowledgenude** [comment]
Yes, after the `playback callback failed` error i don't get any sound played anymore even waiting a long time (at least in Krom -> Linux). Looks like Iron sound box is broken with so many sounds :)

I personally can't see a scenario where more than 32 channels can be used, so i would stick with the `retrigger` option for particular sounds (as for machine guns). I don't know exactly if you already mean that in your answer, but what about retriggering the last sound when the 32 channels limit is reached? This probably can avoid errors in all other situations and may not even be noticeable.

**Comment by MoritzBrueckner** [comment]
This indeed sounds like a Linux thing, I don't have that particular error on Windows: https://github.com/Kode/Kinc/blob/307ff2e56445a0d9c41f13ed94a527b393615f70/Backends/System/Linux/Sources/kinc/backend/sound.cpp#L195

Do you have some other error message [`write failed`](https://github.com/Kode/Kinc/blob/307ff2e56445a0d9c41f13ed94a527b393615f70/Backends/System/Linux/Sources/kinc/backend/sound.cpp#L44-L45) somewhere? The -32 frames delivered actually look like an error code according to the [ALSA API](https://www.alsa-project.org/alsa-doc/alsa-lib/group___p_c_m.html#gabc748a500743713eafa960c7d104ca6f) and the mentioned error should happen in this case. Problem is, I can't find what value the individual error codes have and I don't have Linux to test it.

Also quite interesting error message: `poll failed (Success)`. It seems to originate from [here](https://github.com/Kode/Kinc/blob/307ff2e56445a0d9c41f13ed94a527b393615f70/Backends/System/Linux/Sources/kinc/backend/sound.cpp#L176-L177). Maybe this is actually a bug and in case of a success there shouldn't be this error, I don't know. It could be helpful to recreate this in pure Kha (play a sound at least 33 times in a row) and if the same error happens you could open a Kha issue.

But you can hear a sound (about 32 times) and only after that you can't hear anything? Or is there no playback at all?

**Comment by knowledgenude** [comment]
Now that you've mentioned that, yes. I remember of `write failed` and `-32 frames delivered` errors and they happens frequently. But as these errors don't was not but only messages in the console for me, i ignored them. Maybe it is a different issue in Kha (or even in Linux). Thanks for bringing this up!

Unfortunately i don't know how to run pure Kha to make tests, but i will try that sometime and see what happens. I ask for help on that when i need.

About the main issue: after you reasoning the first solution you mentioned looks more feasible. Looking forward on that!

As mine error doesn't seems related to the audio and you pushed a commit to fix the speaker issue, you can close this or leave open to track the possible improvements to be made on Iron `Audio` class. Thanks again for your help!

**Comment by MoritzBrueckner** [comment]
> Unfortunately i don't know how to run pure Kha to make tests, but i will try that sometime and see what happens. I ask for help on that when i need.

It's quite simple, you can start from the https://github.com/Kha-Samples/Empty repo for example. Just open this in VSCode and let it run.

I made you a small project that simply creates a new sound channel in each update step to copy the behaviour in the blend file above. I manually changed the update frequency from 1/60s to 1/120s so that its more likely that no channels are available. It should output a lot of "No free channel" messages.

[KhaAudioPlayback.zip](https://github.com/armory3d/armory/files/6687963/KhaAudioPlayback.zip) (open & run in VSCode)

If you don't have an issue with this, then the issues are caused by something more complicated and might even be caused by something in Iron or the interplay between Iron and Kha. Otherwise it's probably a Kha issue or there's something wrong with your drivers for example.

> About the main issue: after you reasoning the first solution you mentioned looks more feasible. Looking forward on that!
> 
> As mine error doesn't seems related to the audio and you pushed a commit to fix the speaker issue, you can close this or leave open to track the possible improvements to be made on Iron Audio class. Thanks again for your help!

I'm currently working on a small prototype of an audio engine in Kha but I currently have too less time to seriously work on it. This could be included in Armory in the future if everything works out well, but until then it will take some time. Nonetheless having a "retrigger" option and maybe even the mentioned configuration on what to do if all channels are occupied would be great. An extra issue for this could certainly help.

**Comment by knowledgenude** [comment]
@MoritzBrueckner Hello! I tryed to run the example file but i got this error (in print because i can't select it to copy):
![Screenshot from 2021-06-21 19-43-32](https://user-images.githubusercontent.com/63247726/122836696-18b97980-d2c9-11eb-9b6f-95a9d909b0bb.png)

And then i changed the runtime executable path and chrome opened like that:
![Screenshot from 2021-06-21 20-07-42](https://user-images.githubusercontent.com/63247726/122838433-77342700-d2cc-11eb-90c3-f71fb461121f.png)

Problems: The debug type is not recognized. Make sure that you have a corresponding debug extension installed and that it is enabled. This line is sublimed `"type": "krom",`

Debug console: crbug/1173575, non-JS module files deprecated.
/home/paulohenrique/:486

VSCode is really hard for a non programmer, i couldn't understand how it works, and when i got it working i simple don't know why it is working and i hate that feeling. I will take a time in the weekend and try another way. Thanks for your effort on making this example :)

> I'm currently working on a small prototype of an audio engine in Kha but I currently have too less time to seriously work on it. This could be included in Armory in the future if everything works out well, but until then it will take some time. 

That sounds interesting! I understand you, i also have many small projects (obviously not compared to this level) and couldn't find time to focus, and when i have i am so tired :smile: But i really enjoy the learning process of it and i hope to also share cool stuff coming from that :+1: 

> Nonetheless having a "retrigger" option and maybe even the mentioned configuration on what to do if all channels are occupied would be great. An extra issue for this could certainly help.

Yes, i will close this one because i'm almost sure that is a Kha/Linux thing that i will need to research next week. I'm full of exams now so we can see on the retrigger option later :) Opening a issue right now!

**Comment by MoritzBrueckner** [comment]
Hmm, as the error message states, make sure to have all the Kha/Krom extensions installed. Maybe you need to remove the .vscode directory first (because it could contain Windows commands) and instead run `Ctrl + Shift + P > Kha: Init Project`, I don't know. I had the same error in other projects before, the Kha debugger unfortunately isn't always that stable. If you find the cause, let me know and good look with the exams :)
