### ISSUE TITLE
Lamps from Scene A are also on Scene B

### ISSUE THREAD

**Issue by knowledgenude** [armory3d/armory#2292]
I tested with individual worlds for both scenes, but the same issue happens

[lamps.zip](https://github.com/armory3d/armory/files/6931904/lamps.zip)

**Comment by tong** [comment]
It seems this only happens when the 2nd scene has no light.

**Comment by knowledgenude** [comment]
It happens even with another lamp in the Scene B, if the other lamp is of different type. For some reason when i enable shadowmap atlas the issue goes away

**Comment by MoritzBrueckner** [comment]
Hi, I just tried the test file and I'm not sure if I can reproduce the issue. Am I right that you see the red light when starting in scene 1, and when pressing space to change scenes it is still shown? If yes, that doesn't happen for me on Windows and latest master. Shadow map atlas is turned off and the second scene has no lights, it's the unmodified file from above.

Also, when directly starting from scene 2 there are no visible lights.

**Comment by knowledgenude** [comment]
I updated now and the bug stills exists here... Maybe it is related to OpenGL? I think @ tong also tested on Linux

**Comment by MoritzBrueckner** [comment]
Then I would guess that it happens due to uniforms for which no value is passed if there is no light of the type to which the uniform belongs in the scene. This would explain why it also happens if the lamp types differ and why it doesn't happen on DirectX because this might be undefined behaviour. I will do some tests in the next days :)

If the above should be true, I think there are two possible solutions: we could either hard code default values in the shaders (like `uniform vec3 color = vec3(0.1, 0.2, 0.3);` or pass default values. I don't know if there is a performance difference, but let's see.

**Comment by tong** [comment]
I can confirm that this solves the issue.
