### ISSUE TITLE
Realtime postprocess not working

### ISSUE THREAD

**Issue by tong** [armory3d/armory#2323]
Since #2315 realtime postprocessing (`rp_pp`) stopped working for me for all uniforms wrapped with `#ifdef _CPostprocess` condition. Not sure why this is happening, `_CPostprocess` is correctly defined when `rp_pp` is enabled.

**Comment by onelsonic** [comment]
Try rebuild a project from an empty Blender file (default cube).
Not sure if it is the case but sometimes it seems like the ArmoryUI properties that were setup are kept in some cached info within the Blender file itself.

**Comment by tong** [comment]
Doesn't help.

Reproduce:
- Create empty project
- Enable realtime postprocessing
- Enable Chromatic Aberration
- Set Chromatic Aberration type to Spectral

Results in black screen.

**Comment by MoritzBrueckner** [comment]
Can confirm this. I think this is due to the fact that defines seem to be added to the `compiled.inc` include that some shaders include ([source](https://github.com/armory3d/armory/blob/55cfead0844923d419d75bf4bd677ebed714b4b5/blender/arm/write_data.py#L543-L546)), but not all shaders include that file. Now the question is whether that should be the case, or if those defines should be put in another defines.inc for example that is always included, or if Kha is able to compile the shaders correctly when the flag is also set in Khamake.
