### ISSUE TITLE
Blender 3 support

### ISSUE THREAD

**Issue by tong** [armory3d/armory#2402]
Is there a roadmap/strategy for blender3 support?

Here https://github.com/tong/armory/tree/blender3 would be a branch which allows to build, at least, an empty project with b3.

**Comment by MoritzBrueckner** [comment]
I don't think that there is a roadmap. In the last years we always used the LTS versions, but there are probably a lot of people that want to use Armory with Blender 3.0.

It's very cool that you already have a working branch, maybe we can use that to build on top of it? We can also ask Lubos whether he can create a blender-3.0 branch or maybe I even have the permissions for that. I don't think that there are many breaking changes, but the new property API looks like it would give us a lot more freedom than we currently have, for example we can probably finally implement min/max values for node inputs.

For the work on 2.9 we had a spreadsheet with required and possible tasks, do you think we should do the same for 3.0? It looks like less work this time so I don't know if it's worth it.

**Comment by onelsonic** [comment]
The next LTS version is scheduled for Q2 2022,
Blender 3.3 LTS and should be out in June next year.
The thing is a lot of things can change in Blender by then which is the point of the LTS versions.
If so, Armory will need to be updated for each in between Blender versions 3.0, 3.1, 3.2 and minor updates which seems a waist of limited resources since the LTS version can be used.
The current LTS version has been updated 6 times 2.93.6 17Nov21 and still works.
With limited resources it would be more effective to focus on the next LTS version once a built or pre-built is out and proper planned it.
What are your thoughts?

**Comment by tong** [comment]
I think concentrating on LTS, but having a 3.0 branch sounds preferably.

There is this new, spreadsheet style _Projects_(Beta) view on gh, maybe a good fit for a tasklist (?)

**Comment by MoritzBrueckner** [comment]
@tong I will create a blender-3.3 branch and tag then, is 3.3 LTS correct? Should I copy your commits over to that branch or do you want to open a PR for them?

Using the new projects beta sounds good, is there a way to add entries without creating issues? Or should we add an issue for each task (maybe there aren't that many things to update anyway...)?

**Comment by MoritzBrueckner** [comment]
[Branch](https://github.com/armory3d/armory/tree/blender-3.3-lts) and tag are now created, but the new beta projects apparently have to be created on an organization level. @luboslenco would it be ok for you to add a _Projects(Beta)_ project to this repo for working on the 3.3 support? If not we could also use the old project view instead, it's not a big deal.

**Comment by luboslenco** [comment]
Added https://github.com/orgs/armory3d/projects/1, are you able to edit it?

**Comment by MoritzBrueckner** [comment]
Thanks :) No, unfortunately not, maybe the old project view is better then.
