### ISSUE TITLE
Compiling for android error

### ISSUE THREAD

**Issue by e2002e** [armory3d/armory#2407]
When using android studio and building,
'kinc/audio1/stb_vorbis.c' file not found.

I tried disabling the audio in blender, same error.

**Comment by MoritzBrueckner** [comment]
Hi, this is already fixed [here](https://github.com/Kode/Kha/pull/1373/files) but not yet included in the latest Armory SDK. Until it is included, you can manually apply the linked changes by navigating to `SDK/Kha/Backends/Kinc-HL/KoreC/sound.cpp` and then change `audio1` to `libs` as shown in the link.

@luboslenco if possible can you please update Kha for the next SDK release to include the fix? This issue comes up a lot lately (see https://github.com/armory3d/armory/issues/2377 and some other users on Discord had the same problem)

**Comment by e2002e** [comment]
Many thanks.
