### ISSUE TITLE
read storage and write storage didn't work

### ISSUE THREAD

**Issue by mhreez** [armory3d/armory#2432]
Thank you for contributing to Armory!

**Description**
Issue description.
**read storage and write storage didn't work in last update** 

**To Reproduce**

![Untitled](https://user-images.githubusercontent.com/55386433/150638489-cc7438b5-183e-45c7-b3f4-519f85c5d3a1.png)

**Expected behavior**
What you expected to happen.

**System**
Blender:2.39.1
Armory: 2201a
OS:
Graphics card:
1050

**Test File**
*(drag & drop the zipped .blend file here)*
[test.zip](https://github.com/armory3d/armory/files/7918294/test.zip)

**Comment by MoritzBrueckner** [comment]
Hi, can you please share the project with the canvas? It is stored outside of the blend file.

**Comment by mhreez** [comment]
> Hi, can you please share the project with the canvas? It is stored outside of the blend file.
[car game.zip](https://github.com/armory3d/armory/files/7919108/car.game.zip)

**Comment by MoritzBrueckner** [comment]
Thanks! The problem seems to be that already saved files are not overwritten on Windows (so I'm assuming you're on Windows?), and Iron saves the file once when initializing the storage system. So at the start of the first game without a saved file, an empty save file is written and later writes don't do anything.

But luckily, this is already fixed in Kinc (https://github.com/Kode/Kinc/commit/5cee73e5e4cae640a963408014f84abc3ffadfd8), so as soon as Armory updates to the newest Kinc versions and Armorcore is compiled with that, this will be fixed :)

**Comment by mhreez** [comment]
still didn't work with last version

**Comment by MoritzBrueckner** [comment]
Yes, it's still not included in Armory unfortunately.

@luboslenco could you please update Kha/Kinc for the next SDK release? Not only this issue would be fixed but also the export to HL targets is currently broken due to the new array types and it would be fixed then.

**Comment by MoritzBrueckner** [comment]
Small update: the Kha version is updated now, but there are no new Armorcore builds yet, so I guess it still fails on Krom even though it should work now on the HL targets.
