### ISSUE TITLE
Access to phone sensor data possible?

### ISSUE THREAD

**Issue by StrandedAlien** [armory3d/armory#2440]
Maybe through an already existing interface of something like phyphox?

[https://github.com/phyphox/phyphox-webinterface/blob/master/index.html](url)
[https://phyphox.org/](url)

I am not a programmer, but i heard you can pull data of webpages with so called websockets. That would be sweet. I think getting more people on the armory3d train is easier with unique features like multi-platform and something like sensor support. Great for visualizing physics experiments, input devices, alarms and what not... Could turn people into great phycisists, like Rick Sanchez ;-)

**Comment by MoritzBrueckner** [comment]
Hi, Kha (the framework Armory is based on) can read accelerometer and gyroscope data (the API is [here](http://kha.tech/api/kha/input/Sensor.html) and [here](http://kha.tech/api/kha/input/SensorType.html)) and it is possible to capture audio input, but I don't think that there are more sensor types that are supported right now. If you want more you should open an issue on the [Kha repository](https://github.com/Kode/Kha) because that is the place where something like this would most likely get implemented.

I'm not a network programmer, but I think websockets are totally possible already (in Haxe) :)
