### ISSUE TITLE
What GLIBC version used in program? add in wiki

### ISSUE THREAD

**Issue by lahtis** [armory3d/armory#2460]
Can you add in wiki pages and setup what GLIBC version is used for Downloaded armorySDK files?

In ubuntu 18.04 LTS i cannot get  glibc working. Ubuntu 18.04 using 2.27-3 version of glibc.  I cannot upgrade latest version in distribution. I probably tested the ArmorySDK-2022-1a and ArmorySDK-2022-3 versions in vain, it used GLIBC_2.29.

**Comment by MoritzBrueckner** [comment]
Hi, I was hoping someone else would answer this since I'm not a Linux user, but because no one did so far, here's what I was told on the Discord server while asking about this issue:

The binaries for [Kha](https://github.com/Kode/Kha) and [Kinc](https://github.com/Kode/Kinc) tools are built on the CI with Ubuntu 18.04, so those shouldn't be a problem for you. If the issue happens with the Krom/Armorcore executable, I would guess that it uses whatever version of GLIBC the [`ubuntu-latest`](https://github.com/armory3d/armorcore/blob/131a575ad2c3bdc9fa48f3f15be8d2e357bc5df2/.github/workflows/linux_opengl.yml#L14) image is using. @luboslenco Maybe you can shed some light on this? Should this be documented in the Armory wiki or better in the Armorcore repo?

**Comment by tong** [comment]
You can check with `objdump -T <Krom>`

**Comment by Himik-NAV** [comment]
hello. have you solved the problem?
I have the same problem, but I solved it by switching to the ubuntu version above. but there is another problem - the compilation swears for some reason - it does not find x11 or wayland... and that really stopped everything)))

**Comment by lahtis** [comment]
> hello. have you solved the problem? I have the same problem, but I solved it by switching to the ubuntu version above. but there is another problem - the compilation swears for some reason - it does not find x11 or wayland... and that really stopped everything)))

Not solved.

**Comment by luboslenco** [comment]
Krom binary is now built on 18.04 LTS as well, you can get it by cloning the latest https://github.com/armory3d/armsdk.
