### ISSUE TITLE
Armory Flips RGB channel when using Geometry Node in combination with color ramp

### ISSUE THREAD

**Issue by JAWS81** [armory3d/armory#2467]
Armory flips the RGB channel of textures when using shaders with above mentioned setup to control texture distribution.

Using this setup on a mix RBG Fac input results in mix of color even when using pure black and white checker board texture as input.

[ANT.zip](https://github.com/armory3d/armory/files/8374710/ANT.zip)

**Comment by MoritzBrueckner** [comment]
Some more context on this issue: https://forums.armory3d.org/t/textured-terrain-rgb-channel-flipped/4850.

**Comment by MoritzBrueckner** [comment]
Looks like the issue goes away if you add a `Separate XYZ` node between the color ramp output and the mix input and use one of its outputs. Apparently Armory's way of converting rgb colors to bw doesn't correctly preserve brightness or luminance or something like that and as a result the mix node gets a slightly different input in Armory than in Blender.

**Comment by JAWS81** [comment]
Yes, you are right. I tested your advice on the red and blue example and now it looks identical in Blender and Armory.
BUT if I use it in my initial file to distribute texture over a plane it is still wrong and the mixing of the texture is wrong. It looks like flipped RGB values anyhow.

**Comment by MoritzBrueckner** [comment]
Thanks, regarding the other file I still have the feeling that this is caused by a negative z coordinate as I wrote in the forum. If you now use both my workaround from above and a math node that calculates the maximum of the z coordinate and 0 (please try it before and after the color ramp), does the issue still persist? The blue white stripes look like a negative version of the gray/beige stripes.

Can you please share your original file from the forum post (here or in the forum via PM)? That would help a lot, even though it's probably a different issue than the RGB -> grayscale conversion.

**Comment by JAWS81** [comment]
Hi. You are once again right. I forgot the math node. With it or with a clamp node it works perfectly. Thanks for your efforts.
Attached my example if further testing is required.
[ANT.zip](https://github.com/armory3d/armory/files/8853953/ANT.zip)
e
