### ISSUE TITLE
Neither wayland nor X11 found

### ISSUE THREAD

**Issue by pozitigor1** [armory3d/armory#2487]
I cant start game with krom, terminal writes this:
Failed to load libXi.so
Neither wayland nor X11 found.

**Comment by donjwan88** [comment]
> I cant start game with krom, terminal writes this: Failed to load libXi.so Neither wayland nor X11 found.

me to

**Comment by donjwan88** [comment]
when i use window krom
![1](https://user-images.githubusercontent.com/24539931/167290659-249545db-0bec-47a8-8628-c58ca77f35ed.png)

**Comment by MoritzBrueckner** [comment]
Hi @donjwan88, this is a completely different issue (please look at the different error messages). But thanks anyways for the report, your issue will be fixed with https://github.com/armory3d/armory/pull/2488. For now it will work if you disable live patch and make sure that there aren't any unconnected reroute sockets in your node trees.

As for the original issue: there is a bit more information in https://forums.armory3d.org/t/help-opensuse/4878, and someone else on the Discord server had exactly the same issue a few weeks ago.

Maybe related: https://github.com/armory3d/armory/issues/2478

**Comment by jeffrds** [comment]
Hi there ,
It seems to work with git version at least on Fedora . I could see on linux mint if someone needs to.
 https://github.com/armory3d/armory/wiki/gitversion
Perhaps you will need to  replace the pull origin master with pull origin main .

This issue comes from the Mars or Avril´s  release . I always switch to git after a release , so I am not sure about the month .

Hope this helps .

**Comment by pozitigor1** [comment]
Hi @jeffrds, thanks for your answer, I'm currently using manjaro linux, so I can't try the git version because everything works fine for me, but in the future, when I return to LMDE or linux mint, I'll try the way you described!

**Comment by jeffrds** [comment]
Hi @pozitigor1 , you´re welcome . But I think you need to forget this way   as my last answer is not accurate . It happens that my git version was not updated since at least March , my mistake :)
 
As I told in my last message , it seems that there is a conflict between main and master on Kha repo when you use pull origin command . 

So you have to forget my solution . I tried on both linux mint and fedora Kde with the last release , the git version and also  the old release from March and April  ... same error :  Failed to load libXi.so
Neither wayland nor X11 found.

I can not tell if the error is on the armory February release as I can´t download prior to this date on itch.io . I´ve also put the binary linux Krom from my old git but it complains about  different API versions between Kha and Krom  .

On discord , there is also this error from an  armorpaint user in April . So I tried to see if there is something wrong with ArmorPaint_09_linux64.zip  but I can not even start the app on Fedora .  I can use ArmorPaint 08 without issue though . I will try on linux mint  later this week . 

I am  sorry I could not be of more help on this subject .

**Comment by MoritzBrueckner** [comment]
Hey @luboslenco, sorry for the ping.

Because this issue comes up a lot recently by different users, could it be that the Krom binary used on Linux is simply missing https://github.com/armory3d/armorcore/commit/2573559c91bb0e1594477ce9990ec5544ecf3735 ?

Or do you think this will be fixed by the full switch to Armorcore that seems to be in progress right now? Btw, it's awesome to see you working on this! :)

**Comment by luboslenco** [comment]
I believe it is already included. :( I guess this started happening after merging https://github.com/Kode/Kinc/pull/668. I pushed one fix at https://github.com/Kode/Kinc/pull/692 but it looks like some distros still have issues opening a window via x11.

So we need to compare the x11 code before the https://github.com/Kode/Kinc/pull/668, see what changed and push a fix into Kinc. The bad part is that some distros work, some don't.

The wayland backend is missing the `kinc_wayland_display_init()` function, once that is implemented we can enable wayland in armory as well.

**Comment by luboslenco** [comment]
(Link https://github.com/armory3d/armorpaint/issues/1400)

**Comment by luboslenco** [comment]
Should be ok now with https://github.com/Kode/Kinc/pull/710 and https://github.com/Kode/Kinc/pull/711 applied?

**Comment by pozitigor1** [comment]
idk, for now im using archlinux on my system, as soon as my system crashes, I'll install ubuntu or debian!

**Comment by pozitigor1** [comment]
He @luboslenco you made a mistake in the first debian package that needs to be installed, it is not called libxrand-dev, but libxrandr-dev.
So the full code is:
`sudo apt install libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev`

**Comment by luboslenco** [comment]
Edited, thanks. So you still need to install these packages with the latest armory?

**Comment by pozitigor1** [comment]
on debian linux I still need to install these packages

**Comment by pozitigor1** [comment]
OK, so now I could use armory on any distro that I choose, I'm closing the issue, thanks to everyone
