### ISSUE TITLE
When I move the frame from its place, the code does not work correctly

### ISSUE THREAD

**Issue by donjwan88** [armory3d/armory#2504]
Thank you for contributing to Armory!
When I move the frame from its place, the code does not work correctly Especially the code for animation the texture 

**Description**
Issue description.

**To Reproduce**
https://youtu.be/FkleJpsyxJU

**Expected behavior**
I dont know

**System**
Blender:2.93.8
Armory:2022.6.0
OS:window10
Graphics card:1070

**Test File**
download file from here
https://drive.google.com/file/d/1uQaJs20PZToXwYI212tI5SCr57KvJhI_/view?usp=sharing

**Comment by e2002e** [comment]
Expected behaviour: I don't know ?

**Comment by MoritzBrueckner** [comment]
@ e2002e I think the UI should be visible in both cases. It might be caused by a race condition in the exporter code which may give different results depending on what node was selected/updated last (e.g.), see https://discord.com/channels/486771218599510021/486773516956336128/986712134387892296 (and the following messages).
