### ISSUE TITLE
Timer Node "Out" and "Done" socket are identical

### ISSUE THREAD

**Issue by JAWS81** [armory3d/armory#2516]
**Description**
It seems that the "Out" socket and the "Done" socket of the timer node do the exact same. 
They are both only activated after the timer has finished.

**To Reproduce**
Just print something connected the timer nodes "Out" and "Done" socket to see its behavior

**Expected behavior**
I was expecting that the"Out" socket gets actived right after the timer is started, maybe also after stop and pause. Not sure about the last two options. But at least after starting.

**System**
Blender: 2.93
Armory:2207
OS:Windows11
Graphics card:RTX2080Super

**Comment by QuantumCoderQC** [comment]
Hi, this seems to be a misunderstanding/ lack of documentation about the node rather than a bug. The `out` socket will be executed after every "repetition" of the timer logic node. The `done` socket will be executed only after all the repetitions are complete.

I believe, in your test case, the "repetition" was set to 1. So both `out` and `done` were executed after the first repetition. Would you agree?

**Comment by JAWS81** [comment]
Hi, yes you are right that was my setup. Okay I assumed it to work differently than it really does. I will close this issue than.
Thanks for your explanation.
