### ISSUE TITLE
Torque to vector node

### ISSUE THREAD

**Issue by vuaieo** [armory3d/armory#2541]
hi i realized very important node shortcut for physics like games would be to able to rotate rigid body to vector but by torgue. similar how look at node , just spend maybe 10 hours on this issue because me not math genius ...
![torque to axis and limit it by torgue1](https://user-images.githubusercontent.com/110411323/182524600-8def38c1-e721-48f3-b5d8-8eb7266d7ae3.jpg)
wth physics based games if able to make them easy could be alternative to big game engines still.. but not like right now for speed and fun...

**Comment by QuantumCoderQC** [comment]
Hi, I think this is a very specific application for a Logic Node. Perhaps it is better suited for Logic Pack.

**Comment by knowledgenude** [comment]
@vuaieo , so by "torque to vector" you mean something like get "rotation" velocity? That is not possible, because rigid bodies are not "rotated" by the physics engine like we do in Blender, instead the physics engine applies forces to the object and tries to simulate how real life physics works. Imagine yourself turning your head arround, while it seems to be "rotating" around some origin, there are muscles producing forces in specific points of your neck to make your head turn arround. How would you rotate some object in your table? You would need to apply force to it with your hand at some point to make it rotate, so the rotational force in that case is the velocity of that "point", I will try to explain better...

**(But in short, you can use the Get Point Velocity node to achieve what you need)**

So why is not possible to get the perfect "rotation" velocity as you are thinking? Imagine a children's bicycle, it has smaller wheels than adult bicycles, and consequently reaches a much lower speed, this is due to the fact that the size of the wheels are smaller, the same applies to the bicycle chain, a smaller chain is lighter but slower... So did you notice how much the distance between the origin and the reference point changes such rotational force? So what you get when you try to achieve the rotational velocity without passing any vector, just saying "give me the rotational velocity" like you do with get velocity node? It is not possible, because if you consider the origin point as the "center" it will give you a zero rotational velocity, because remember, the smaller is the "wheel" the lower is the speed, so a 0 sized wheel will give zero velocity.

So if you want "perfection" with that rotation thing, better to simulate it using rotate node instead of physics.
