### ISSUE TITLE
Canvas does not show up anymore after upload to Github

### ISSUE THREAD

**Issue by StrandedAlien** [armory3d/armory#2543]
Thank you for contributing to Armory!

After uploading my files to Github and invoking the Link the Canvas does not show up anymore.
In the browser on my PC it works. Please check. Might be a bug.

Repository with example and blend
https://github.com/StrandedAlien/NoCanvas/tree/main

Live link
https://strandedalien.github.io/NoCanvas/

**Comment by QuantumCoderQC** [comment]
Hi, this might be because of GitHub pages not recognizing files starting with an underscore. This is the error message I get when I open your live link.

![image](https://user-images.githubusercontent.com/55564981/182722491-dc26a6e8-96f1-4edd-aad4-9a8612b67df0.png)

To fix this, you need to add an empty `.nojekyll` file in the root directory of your repository.

More info: https://github.com/orgs/community/discussions/23166

**Comment by StrandedAlien** [comment]
Hi, added the .nojekyll. Said file is hiddem. Pushed submit. No canvas shows up. Maybe i am missing something?

**Comment by StrandedAlien** [comment]
I tried it first with my Swap5 version of the Nixie clock. Does not work at all. However, strange enough, it did not work with NoCanvas file at first after a drag and drop. Then i tried it with "choose file". After the second  time uploading with choose file it worked. But no dice with the Swap5 Nixie clock. Still no show of canvas. Tant pis!

**Comment by StrandedAlien** [comment]
Tried several times uploading with drag and drop and choose file. Now it works. Hurray.
