### ISSUE TITLE
Rendering issues (Armory PBR)

### ISSUE THREAD

**Issue by guzzard** [armory3d/armory#255]
**Cycles**
![cycles](https://user-images.githubusercontent.com/9007314/31013281-a5b3b84a-a515-11e7-8cbf-6db7c7025258.png)

**Armory (with emission on box and metallic on plane)**
![armory](https://user-images.githubusercontent.com/9007314/31013290-ac8e970c-a515-11e7-99b5-7640b6879744.png)

**Armory (no emission on box and no metallic on plane)**
![armory_no_emission_no_metallic](https://user-images.githubusercontent.com/9007314/31013416-513bef48-a516-11e7-9761-6c6fd7b9fb67.png)

**Issues**
- Metalic causing issues on the plane
- Emission causing issues on the cube
- White background not working

**Project file**
[render_test.blend.zip](https://github.com/armory3d/armory/files/1344070/render_test.blend.zip)

**Comment by luboslenco** [comment]
- Environment color should now reflect on metallic surfaces in https://github.com/armory3d/armory/commit/7912b4ca26f95d7ed8605c50054ec3d4998bd991, eliminating black plane error.

To-do:
- Emission is still voxel-only feature
- White background not working is caused by filmic tonamapping enabled in `Properties - Render - Armory Render Props - Tonemap`. Need to merge this option with `Properties - Scene - Color Management - View - Filmic` to prevent confusion.

**Comment by luboslenco** [comment]
Merge with https://github.com/armory3d/armory/issues/624.
