### ISSUE TITLE
Concave side of half sphere or half cylinder shows always as convex. No pano viewer possible this way.

### ISSUE THREAD

**Issue by StrandedAlien** [armory3d/armory#2551]
Thank you for contributing to Armory!

![image](https://user-images.githubusercontent.com/89656885/184713476-73b72341-abf8-41ae-b79d-3c1467202338.png)
[always_convex.blend.zip](https://github.com/armory3d/armory/files/9339713/always_convex.blend.zip)

Camera should show concave side, but object appears inside out.
Normal are correct namely inverted, see blend included.
2-sided on/off in mat settings does not change anything.
Looks like a bug to me.

Uses QC´s viewer for convenient demo, just move mouse to see it after compiling.

**Comment by MoritzBrueckner** [comment]
Hi, this is not a bug, but a wrong material setting. In the material properties, set `Armory Props > Cull Mode` back to `Front` (default value) and the object should look correct again :) By changing the cull mode to `Back`, you reverse the [winding order](https://www.khronos.org/opengl/wiki/Face_Culling#Winding_order) of the faces of the material and in turn the normals get flipped.

**Comment by StrandedAlien** [comment]
Correct? Not for me. Camera parameter clipping also adjusted. When i turn the mouse i can either see the left or the right end of the half cylinder. Please check the blend i have posted.
![image](https://user-images.githubusercontent.com/89656885/185810565-a5d71485-c1ba-4127-94c3-707d2aa33401.png)

![image](https://user-images.githubusercontent.com/89656885/185810578-d0e2ec57-9fe1-4f39-a384-bf5ba43cd00f.png)

**Comment by Dzynek** [comment]
@MoritzBrueckner is right, it works fine for me now.
I am attaching the corrected file:
[always_convex2.zip](https://github.com/armory3d/armory/files/9393711/always_convex2.zip)

**Comment by StrandedAlien** [comment]
I even tried it under Win10, same problem. Meaning its probably neither a Manjaro/Arch Linux or graphics driver issue. Both system run a RX580. I would be interested in others trying this on an ATI-card. I would bet you and Moritz are using Ndivia ;-)
Thanks for your efforts.
![image](https://user-images.githubusercontent.com/89656885/186014104-290aaffd-fdcb-4a5b-87c9-4d39a77e475b.png)

**Comment by MoritzBrueckner** [comment]
Yes, I'm indeed using an Nvidia card, but I just tested it on an AMD laptop GPU and it looks exactly the same for me.

In [this](https://github.com/armory3d/armory/issues/2551#issuecomment-1221619559) answer you said that you only ever see one end of the cylinder, and I think this could be caused by the camera controller simply being on the wrong side for some reason. You're seeing only a part of the mesh, but what you see is definitely on the inside/concave side. If you switch the camera to "Viewport" you will see that everything is rendered correctly. I'm not sure though how you created your last screenshot – this is again with the cull mode set to "Back", right?

> 2-sided on/off in mat settings does not change anything.

This by the way is probably https://github.com/armory3d/armory/issues/2371, the bug is already fixed in Kha but I think it hasn't made it's way upstream into Armory's Krom binaries yet.

**Comment by StrandedAlien** [comment]
> I'm not sure though how you created your last screenshot – this is again with the cull mode set to "Back", right?

I just opened Dzynek´s file pressed F5 and then PrintScreen. No self sabotage involved.

**Comment by MoritzBrueckner** [comment]
In Dzynek's file the normals are inverted (compared to your original file). If you invert them again it should look correct :)
