### ISSUE TITLE
Call group input node automatically cuts input socket link if linked node tree executes cut operation

### ISSUE THREAD

**Issue by rpaladin** [armory3d/armory#2639]
# Description:

Call group input node automatically disconnects input socket if one or more socket links are disconnected from the synced group input node. **Note:** This unexpected behavior works even if two or more links are connected to the group input node. Example: Two print nodes.

## Preview before cut

![image](https://user-images.githubusercontent.com/69180012/198395497-7260ae80-5a23-4d46-ab79-597a08ae6d4a.png)

## Cutting group input node output socket link

![image](https://user-images.githubusercontent.com/69180012/198395532-517bf598-53f7-4619-b00b-a7caded08062.png)

## After cut

![image](https://user-images.githubusercontent.com/69180012/198395545-6006bec0-47c2-4062-a5ca-d5d9a2083f29.png)

**Comment by rpaladin** [comment]
I'd like to clarify further. After experimenting, it appears that the bug happens with _any_ cut socket links in the Node Tree that the Call Node Group node is synced with. Not just the socket links that are connected to Group Input Node, but also any nodes in that Node Tree - the bug isn't specific to a certain node, but rather any node in that Node Tree.

![image](https://user-images.githubusercontent.com/69180012/198401859-1e779bb4-97e9-452b-bdbc-231953e9972c.png)

**Comment by MoritzBrueckner** [comment]
The problem seems to be here: https://github.com/armory3d/armory/blob/0d9acff266dbe7a86683bbb45e7f4581af2b5235/blender/arm/logicnode/miscellaneous/LN_call_group.py#L34-L47

Whenever `update_sockets()` is called, all links are first removed, probably to ensure that there are no wrong connections afterwards (e.g. this is called when the user selects a different node tree in the call group node). I guess this could be made a bit more intelligent/less aggressive.

I personally think a link should be removed if at least one of the following things is true:
- The call group node was changed
- The corresponding socket in the group node no longer exists
- The name or type of the corresponding link in the group has changed (even though this would also remove the link in your specific example). This is debatable, perhaps it would be ok to make this the user's responsibility, and that's what Blender seems to do (no link is removed even if the type changes).

It may make more sense to also change the behaviour of the "Any" type socket if it's used in group input and output nodes. Like in Blender, it could be changed to keep the type and name once a link was connected. If it is removed, the group input/output socket keeps its name and the color. However, this would probably only make sense if there was a better UI to manage the inputs/outputs, like in the sidebar for Blender node groups.

> After experimenting, it appears that the bug happens with any cut socket links in the Node Tree that the Call Node Group node is synced with.

The code I linked above is - among other situations - called when a group's input or output node's `update()` callback is called, which Blender will call for almost every change made to a tree. I guess we could replace `update()` with [`on_socket_state_change()`](https://github.com/armory3d/armory/blob/0d9acff266dbe7a86683bbb45e7f4581af2b5235/blender/arm/logicnode/arm_nodes.py#L162-L166), even if it's just to not waste any useless CPU cycles. It's also happening for example if you add any links in the group's tree.

These were quite a few remarks and possible improvements (and the list may not even be complete, perhaps you have some ideas/opinions on this?), if you want to implement anything of this yourself feel free :) All those remarks are of course connected to each other, but they can be implemented isolated from each other in small steps. Otherwise I may try to improve this when I get time (my todo list is quite long at the moment unfortunately).

**Comment by rpaladin** [comment]
@QuantumCoderQC am I correct in understanding that #2806 resolved issue? I just tested myself, and things seem fine now. 🙂

**Comment by QuantumCoderQC** [comment]
Hi, yes, this was solved with #2806

**Comment by rpaladin** [comment]
Awesome! Thanks.
