### ISSUE TITLE
Network nodes stop working after adding a second print node

### ISSUE THREAD

**Issue by StrandedAlien** [armory3d/armory#2669]
Thank you for contributing to Armory!

**Description**
See my tutorial in the forum: [https://forums.armory3d.org/t/armory-3d-community-channel/5005](url)
Network nodes stop working after adding a second print node. Even if i remove the print node afterwards, i.e. bringing the blend back to start setup, it won´t work anymore. I need to revert with file menu to remedy the issue. That was certainly not meant to be like that. Weird bug, cause i was making the tut without doc, and this did cost me some time.

**To Reproduce**
Download tut blend from the link. Follow tut and make it work. Then add second print node like in the second screenshot.
Try to run it. Remove print node again, returning to setup in screenshot one. Kaputt!

![image](https://user-images.githubusercontent.com/89656885/203833751-235703e4-1630-4ce8-8cce-87241f6e008b.png)

![image](https://user-images.githubusercontent.com/89656885/203833840-3b466517-d8ee-4234-9c5b-288ace63cba7.png)

Does not run anymore

**Expected behavior**
What you expected to happen.

It should have worked again, after removing the second print node, but nope, no way. Need to revert/reload the untouched original file.

**System**
Blender: 3.3.1
Armory: 22/11 plus Update cause of networking nodes
OS: Manjaro (Arch Linux) up-to-date
Graphics card: RX 580 8GB

**Test File**
Working  file, but needs websocketd running see forum tut.
For Windows try with python3 count.py

[websockets.zip](https://github.com/armory3d/armory/files/10086415/websockets.zip)

**Comment by Onek8** [comment]
Hey thanks for being the first to report on networking! Once the buffer is read it is not available any more, meaning once an api matches an event ( health -> health ) the data gets parsed from a buffer to its original type such as integer, string, vector ect. What you can do to reuse a value is once it matches an api you can set object property and get it multiple times afterwards. Let me know if this clears your issue.

**Comment by Onek8** [comment]
As for the other issue you mention for reverting back, I have not ran into this issue on linux perhaps you can disable cache build?

**Comment by Onek8** [comment]
Also f8 I believe reloads all nodes and armory scripts

**Comment by Onek8** [comment]
You need to use the message parser
![chatRelay](https://user-images.githubusercontent.com/20072039/203855996-a0676c09-8c6e-4539-8e1b-1dac304d2149.png)
![chatDisplay](https://user-images.githubusercontent.com/20072039/203855999-4ff13cb1-f4b3-4194-a0fa-1aabc772c305.png)
![chat](https://user-images.githubusercontent.com/20072039/203856001-a4ce4781-3946-4d5e-ad5f-879faa2b3c58.png)

**Comment by StrandedAlien** [comment]
Thanks. Lots of info. I need to try that out...

**Comment by MoritzBrueckner** [comment]
For accessing a value multiple times from sockets that only output it once, you can also use the `Retain Value` node which will store a value for as long as you want it to be stored. Note that it doesn't necessarily create a copy of the data (it depends on whether the data type is [mutable or immutable](https://github.com/armory3d/armory/wiki/Common-Mistakes#passing-values-around-does-not-necessarily-copy-the-values)), perhaps @Onek8 can tell whether this node will work in this particular case or whether it could fail if the buffer is reused.

I think we should document all this better, both the network nodes as well as the way values are passed between sockets and the possible pitfalls.

I will close this issue now since it doesn't seem to be a bug :)
