### ISSUE TITLE
Networking Nodes Not Working for Windows C

### ISSUE THREAD

**Issue by PowerBroker2** [armory3d/armory#2721]
**Description**
Can't get networking nodes to successfully create a host connection.

**To Reproduce**
When compiling and running the attached blend file for Windows C (via Visual Studio), the below error will be thrown:

![](https://cdn.discordapp.com/attachments/486773516956336128/1055227175105745027/Capture.PNG)

**Expected behavior**
What you expected to happen.

**System**
Blender: 3.3.0
Armory: 2210
OS: Windows 10
Graphics card: NVIDIA GeForce RTX 3090

**Test File**
*(drag & drop the zipped .blend file here)*
[blend.zip](https://github.com/armory3d/armory/files/10282198/blend.zip)

**Comment by Onek8** [comment]
Ok i just tested your example file and it works for me on windows. Use the following command to see if your ide did not close the process correctly, otherwise check your firewall settings cause it looks like your not binding to the port
netstat -aon | findstr :8001
![image](https://user-images.githubusercontent.com/20072039/209028226-90caae84-cfea-4181-ba3f-504bb0479696.png)

**Comment by PowerBroker2** [comment]
I get a similar result:

![Capture](https://user-images.githubusercontent.com/20977405/209042378-c3c7c222-fc75-4a2c-a348-c5f985016e88.PNG)

Does this mean the port was already open when I launched the game? If so, how do I close the port?

**Comment by Onek8** [comment]
For windows should be one of these below for that process is showing in your last command

taskkill 15948 
taskkill /PID 15948 /F
taskkill //PID 15948 //F

Otherwise you can just use ctrl alt del ( task manager ) and find the name of your app in the process list to kill since your on windows desktop. Running your application with a debugger will close all related processes when closing the debugger itself however if you run in release your creating a server process along side the gui window process so you would need/want to close a server host before the application gui closes. Normally you would probably deploy the host in a headless/gui-less target and manage the process with something like systemd however for in game hosting you will want to close a host before the gui closes. For now atleast

**Comment by PowerBroker2** [comment]
Ok, I killed the process and the errors go away. Not sure if it's working but at least I don't have errors. Thanks!

**Comment by MoritzBrueckner** [comment]
@Onek8 Should there be a `Failed` socket for these cases? If the code raises an exception the user isn't able to react to that in logic nodes, so it's not possible e.g. to show a "Could not connect to server" error message to the player.

**Comment by Onek8** [comment]
I will take a look tonight and add a failed socket as that would indeed be very useful!

**Comment by Onek8** [comment]
I didnt have the time to look add it the other day, but now I am wondering if a failed socket is even valid use case because in general we should use server status codes to dictate logic since the system socket actually has a specific system error. If we simply try catch for the create network node we can also concatenate an additional error message around the system socket error that states something like " could not bind to port " so maybe something like ->

"Failed to create server host listening on " + port  + " with the following error: " + err + " . Check if there is a system process occupying the port, or use port '0' for armory to use the first available network port when creating a server host."
