### ISSUE TITLE
Cmft radiance hangs sometimes after cleaning project.

### ISSUE THREAD

**Issue by lampysprites** [armory3d/armory#2760]
Thank you for contributing to Armory!

**Description**
Sometimes cmft.exe never finishes doing its thing. The process remains running at 0% cpu usage. Happens at random after using clean operator which i guess just makes it to re-run during build. After happening once it keeps happening. The same project will run later.

**To Reproduce**
Clean project, run in krom.

**Expected behavior**
Build continues.

**System**
Blender: 3.3.2
Armory: at 7b34cffc294bbcb22d9b6dcaf6fb5df4f41bae0d (with some unrelated things changed)
OS: wondows 10 build 19044
Graphics card: Intel® UHD Graphics 600
possibly worth mentioning that sdk is on an external ssd

**Test File**
output: https://pastebin.com/09D9NRLb
blend and build folder: [cmft freeze.zip](https://github.com/armory3d/armory/files/10424639/cmft.freeze.zip)

**Comment by MoritzBrueckner** [comment]
I wonder if the hangs are caused by what is described [here](https://github.com/dariomanesku/cmft#remark-):

> If you are running OpenCL procesing on the same GPU that it connected to your monitor you may experience the following problem: when you are processing big cubemaps (~1024 face size) with small 'glossScale' parameter (<7 for example), OpenCL kernels may take a long time to execute and that may cause the operative system to step in and kill the display/gpu driver in the middle of processing! In case this happens, the processing will continue on CPU. You will get the expected results but the processing will run slower. To avoid this you can:
> - Use smaller input size. (this is crucial!)
> - Choose a bigger 'glossScale' parameter.
> - Use a workaround on Windows: increase the TdrDelay or modify the TdrLevel in the registry and restart the machine. More details here: http://msdn.microsoft.com/en-us/library/windows/hardware/ff569918%28v=vs.85%29.aspx
> - Run cmft on a faster GPU.
> - Run cmft on a GPU that is not connected to the monitor.

However, Armory uses a `glossScale` of 8 and uses a face size (both src and dst) of 128, so I'm not sure whether this applies... Also, if the display/GPU driver was killed I would expect that your monitor goes black for a short amount of time, but I might be mistaken here.

There was a [similar report on Discord](https://discord.com/channels/486771218599510021/487613529990365184/1051977185977708684) (also see the messages following the one I linked) in which the cmft process eventually finished but only after a long time:
```
CMFT info: Radiance ->  <GPU>  |   32 | 118.160s | 118.260s
```

The GPU used in that issue is an AMD Radeon RX 6400, according to @ knowledgenude "it doesn't have encoders and probably other stuff needed for the task".

@ lampysprites If you wait a few minutes, does cmft eventually finish computations in your case? If so, what's the full cmft output? Is there a single entry that takes all the time like the one `<GPU>` task I pasted above? In the output log you can see a column for "Face", each face apart from 64 and 128 is listed six times (six faces in a cube), but 64 and 128 are only listed five times. So the hang clearly happens within the actual computations assuming that it's not only the logging that hangs.

**Comment by lampysprites** [comment]
Nothing after 15 minutes at least.

What I am using is indeed a placeholder gpu, so prerformace might very well be the issue.

I aleady changed TdrDelay before all that.

128 appears six times in the output both then and now, 64 only fivce.

**Comment by lampysprites** [comment]
With that change it hasn't happened for a while, and I've been pressing clean before each build.

**Comment by rpaladin** [comment]
> With that change it hasn't happened for a while, and I've been pressing clean before each build.

Glad to hear that! Just a tip, if you want to build without having to manually clear the cache each time, you can simply uncheck the `Cache Build` setting. 🙂

![image](https://user-images.githubusercontent.com/69180012/213881998-3ee0d99d-4510-4207-891f-21d171684cf6.png)
