### ISSUE TITLE
Add Boolean operations to the node tree

### ISSUE THREAD

**Issue by chuiliuyiyi** [armory3d/armory#2869]
I plan to add Boolean operations to the game. Can you help me add Boolean operations.

**Comment by rpaladin** [comment]
Armory also supports a variety of Boolean related logic nodes.

**Comment by MoritzBrueckner** [comment]
As @ rpaladin correctly pointed out, Armory already has these capabilities. In logic nodes for example there's the `Invert Boolean` node and the `Gate` note (representing a [logic gate](https://en.wikipedia.org/wiki/Logic_gate) plus some comparison functions). In Haxe you obviously don't need any Armory-specific functionality since Haxe already has all the basic boolean operators.
