### ISSUE TITLE
Can Chinese characters be supported

### ISSUE THREAD

**Issue by chuiliuyiyi** [armory3d/armory#2870]
Can Chinese characters be supported，Chinese node tree running error。

**Comment by MoritzBrueckner** [comment]
Hi, can you please provide more information?

- What's the full error message? Is it actually an error or just a warning?
- When exactly does the error occur?
- Does the error happen for the name of the logic tree? Or for the name of individual nodes? Or for some string values within the nodes?

In general, we cannot name logic trees arbitrarily since they are converted to Haxe code which has strict naming requirements (see https://github.com/armory3d/armory/issues/1567 for an explanation). Of course we can (and already do) replace not allowed characters with allowed once, but then the node tree is called differently at runtime because we _have_ to rename it. In those cases you will see a warning (that's why I asked above if your error really is an error).

I will wait for you to answer, but I think there's nothing we can do here.

**Comment by chuiliuyiyi** [comment]
In Blender, I chose the Chinese interface, but in Armory, the Chinese node tree cannot be read. You can only switch to the English interface. The newly created node tree is in English and can only be saved and read.

**Comment by MoritzBrueckner** [comment]
> the Chinese node tree cannot be read.

Can you please elaborate what you mean by "cannot be read" here (and later with "can only be saved and read")? Also, **please answer my questions above**, for example I still don't understand whether you are talking about the _name_ of the logic tree or something else. You need to provide more information to get help with your problem.

Is this about the UI translation only? Or something runtime related? Armory doesn't provide any UI translations and due to the lack of potential translation maintainers I doubt that it will happen anytime soon (also see https://github.com/armory3d/armory/issues/2365#issuecomment-1083531796).

**Comment by MoritzBrueckner** [comment]
Closing this due to open unanswered questions. We can reopen this anytime if it's clear what this issue is about.
