### ISSUE TITLE
Add GI probes

### ISSUE THREAD

**Issue by guzzard** [armory3d/armory#291]
**Cycles**
![cycles](https://user-images.githubusercontent.com/9007314/31881394-b0f3b030-b7e3-11e7-9658-8ae688aee6e1.jpg)

**Armory**
![armory](https://user-images.githubusercontent.com/9007314/31881552-312c69c2-b7e4-11e7-850a-d8b305c16f93.jpg)

**Issues**
- Cube is not reflected in the plane
- Differences in light/shadowing on the cube

**Blender file**
[render_test_7.blend.zip](https://github.com/armory3d/armory/files/1406469/render_test_7.blend.zip)

**Comment by luboslenco** [comment]
For some 'fake' reflections `Armory Render Path - SSR (Screen space reflections)` can be enabled, but it's nowhere near the quality of path-traced reflections. Since it's a screen space effect it will have no idea about the bottom side of the cube, and the color will be off. Will eventually solve this with some reflection probes, but want to align that functionality with eevee to remain compatible.

**Comment by luboslenco** [comment]
Continue at https://github.com/armory3d/armory/issues/649.
