### ISSUE TITLE
Nishita sky crashes when strength set to zero.

### ISSUE THREAD

**Issue by e2002e** [armory3d/armory#2937]
Thank you for contributing to Armory!

When using a nishita sky and setting the environment light to 0, crashes occur:
double free or corruption (out)
WARNING: Player exited code -6
.
Blender: 3.6
Armory: lattest
OS: PopOS
Graphics card: rtx 3050 driver 535

**Comment by MoritzBrueckner** [comment]
Hi, I'm assuming the crash happens on Krom? I can't reproduce this and I'm a bit surprised that the crashes only seem to happen when you set the env strength to 0, as this only changes a shader uniform. However, there was an issue with Nishita skies in Krom builds that I fixed in https://github.com/armory3d/armorcore/pull/64, unfortunately this fix will not make it into the SDK until https://github.com/armory3d/armorcore/issues/63 gets fixed... Maybe check the fixes with a custom Krom build, if you know how to compile it.

**Comment by e2002e** [comment]
Ok, thanks for the reply.
I found out that the wrong drivers version may lead to black screens with some settings on.
Anyway, did you try the refraction shader ?
I had to modify it since your last review more that one month ago, that works great without aberant tweaks to the refract function.

**Comment by rpaladin** [comment]
If you just created this issue as an intentionally misleading false report and to nag for a code review, then that's rather despicable behavior in my opinion.

**Comment by e2002e** [comment]
@rpaladin, no that is never my intention.

**Comment by e2002e** [comment]
I'm closing this since I can't reproduce the issue.
I was quite sure that using a nishita sky with 0 strength would allow for a lit sky without the environment light.
This doesn't hold true right now, don't know why. Sorry about the disturbancy.

**Comment by e2002e** [comment]
I'm reopening since this is still an issue.
I tested the code again, with nvidia drivers 510, and the exit code is now -11.
