### ISSUE TITLE
Ammo auto deactivation

### ISSUE THREAD

**Issue by yulbryn** [armory3d/armory#313]
When working on my example using physics with a Leap-controlled hand to interact with boxes, all the boxes always deactivate themselves quickly.

I bound one box to the keyboard and only when moving it (while pressing the keyboard), physics came back and box will interact with the hand. As soon as the keyboard is not pressed, box stopped interacting.

I don't understand, since the hand is always moving so I ended up creating a Trait and setActivationState(DISABLE_DEACTIVATION) on object update, but I don't think that is the best way. Any idea if this is linked to Ammo or Armory ?

**Comment by luboslenco** [comment]
Hm, Armory now handles `Properties - Physics - Rigid Body Dynamics - Deactivation - Linear Vel / Angular Vel`, maybe tweaking those will help?

It is also possible to disable deactivation from UI now with 'Physics - Armory Props - Force Deactivation' unchecked. (Blender has deactivation disabled by default, which is not feasible for real-time stuff, so that is the reason for this additional flag.)

(https://github.com/armory3d/armory/commit/0a81944b40252ff5bf2032e8d1dd3247c43cacbc, https://github.com/armory3d/haxebullet/commit/84e77a29fb9e228a23eed1d778ef94f4778ead09)

**Comment by yulbryn** [comment]
Using the Armory property Force Deactivation unchecked made it work without my workaround.
Thanx !
