### ISSUE TITLE
Logic Nodes rotation in degrees

### ISSUE THREAD

**Issue by Defaultsound** [armory3d/armory#362]
Been tinkering with logic nodes a bit, and so far its got what you need to make some simple games. 

But, I've found myself needing some extra nodes that coming from UE4 would prove useful.

-Variables (Getters and Setters)
Might have over looked this, but so far I haven't sussed how you can store variables using Logic nodes. UE4s get and set Variable nodes have proven to be a robust system. I would suggest something similar to that.

-Lerping 
Used for various instances, smoothing rotations, translations (Also being able to lerp over time or some sort of timeline would be good) Also various lerp variable types, (Floats, Vectors etc) 

-Look at Point 
Similar my other request for constraints, either that use the constraint system or just a node that would return the correct rotations to look towards another object. Has many uses in games.

-Rotation in degrees (Mapped between 0 and 360) 
Currently "get rotation" outputs in radians, converting it to degrees a little cumbersome. Also using radians for logic can be complex. Having it in a clamped value between 0 and 360 would make this a lot easier.

I'll probably think/ come across some more ideas. I know these could be added manually as custom nodes, but these could prove useful to have in base Armory. Correct me if I am wrong on any of these ideas or they already exist. :)

*(optional - drag & drop zipped .blend file here)*

**Comment by luboslenco** [comment]
Nice! This will help a lot to develop logic nodes further.

**Comment by MadMinstrel** [comment]
A simple Else impulse output on most logic nodes would be nice as well.

**Comment by PixelPartner** [comment]
About rotation in degrees - how about having three outputs;

1. in radians like before

2. in degrees accumulated

3. in degrees clamped to 0-360

**Comment by MoritzBrueckner** [comment]
Hi, I think this issue can be closed now as we have [rotation sockets](https://github.com/armory3d/armory/pull/2305) (documentation is still missing though) since 2021.09 which work with both radians and degrees. There's also a new [`Separate Rotation`](https://github.com/armory3d/armory/wiki/reference_motion#separate-rotation) node which can decompose a given rotation into eulers, axis angle and quaternion representations.

Regarding the other points of the list in the first post above:

- [Variable nodes](https://github.com/armory3d/armory/wiki/reference_values#variable) are implemented for a long time even though there probably is room for improvement when it comes to usability
- Lerping is now supported via the new [tween nodes](https://github.com/armory3d/armory/pull/2336) ([documentation](https://github.com/armory3d/armory/wiki/reference_values#tween-float)) for scalars, vectors and rotations
- There's a [`Look At`](https://github.com/armory3d/armory/wiki/reference_motion#look-at) node that should do exactly what's mentioned above, it takes in a location and another target location and outputs a rotation
