### ISSUE TITLE
Weird transform issues on character

### ISSUE THREAD

**Issue by donalffons** [armory3d/armory#366]
This is one of the characters, that I use a lot in my work (it's exported from MakeHuman):
![image](https://user-images.githubusercontent.com/33040347/33236007-24109d1c-d247-11e7-9d88-f364e3728c20.png)

In Armory he looks a little overweight:
![image](https://user-images.githubusercontent.com/33040347/33236012-460fd07c-d247-11e7-9c03-791857681f4d.png)

[Worker.zip](https://github.com/armory3d/armory/files/1503512/Worker.zip)

**Comment by luboslenco** [comment]
Hah that's a big guy. It seems to come from the two weak spots in armory right now - displacement and translucency.

If you update to the latest version and uncheck `Properties - Render - Armory Render Path - Displacement`, displacement socket will get disregarded and the weight should be back to normal.

I then selected hair/eyebrow materials and checked `Properties - Material - Armory Props - Discard` option, which will drop pixels below specified alpha value - this reduces the 'white stroke'.

![skin](https://user-images.githubusercontent.com/3685704/33240750-71be11ba-d2bb-11e7-8dbc-b3f22d4cdc4d.jpg)

There is a bit of skin going through his trousers, which could by caused by vertices being influenced by more than 4 bones. In that case armory takes the bones with 4 highest weights, but the remaining ones are dropped. This is done to keep skinning efficient on the gpu. I may fix this in the future at least for the cpu skinning option, at a cost of performance. In the meantime I think adjusting the weights to 4 bones per vertex is the go-to solution.:/

**Comment by donalffons** [comment]
Thanks for the detailed explanation. Unfortunately I can't find the displacement option under render path (either it's not there or I'm getting old - or both).
I'm not so concerned with him showing a little bit of skin. As long as he looks 90% good, I'm happy :).

I leave it up to you wether to close this issue or not.

Thanks for your help!

**Comment by luboslenco** [comment]
No prob! Perhaps it's the updater acting up again? It's a quite recent commit(https://github.com/armory3d/armory/commit/68754ad79c871128c4c3e8c450ef9dc6186269a5), should be there on the bottom of render path panel.

New builds out next week, will be resolved out of the box soon.:)

**Comment by donalffons** [comment]
Let's blame the updater :).

I will just wait for the next build. Very very excited about all that...

**Comment by Kotarosdevgame** [comment]
thanks for reply to all 
in Games at least i suggest to make the cloth join to the Body the config and modifier stays still correct and each material in the physics tab there further to change ,and in edit mode you can pick by seperate one of these again to change in edit mode reduce the edge unsubdivide 1 or 2 times and decimate modifier if its necessary.
