### ISSUE TITLE
Microsoft Edge problems

### ISSUE THREAD

**Issue by donalffons** [armory3d/armory#454]
Hi,

to continue the discussion from [here](http://forums.armory3d.org/t/microsoft-edge/603/13) and [there](http://forums.armory3d.org/t/html5-on-safari-and-microsoft-edge/619/7): Edge support is very limited at the moment.

Here is a simple test scene: It's really just the standard cube with the 'mobile' rendering preset.
[Edge.zip](https://github.com/armory3d/armory/files/1609772/Edge.zip)

When I play this in Edge, the scene actually shows up working, however Edge throws error at seamingly random intervals:
![image](https://user-images.githubusercontent.com/33040347/34649634-643f6d90-f3b3-11e7-8227-381a9db4da0e.png)

@luboslenco, if this is currently not a priority for you, it would be great if you could leave a few breadcrumbs on where this issue might come from (armory? iron? if you can think of a reason, that is...). Maybe me or someone else can pick up the issue then...

The progress is great! It's also great to see that more developers are jumping on. Can't wait for 0.2.
-Sebastian

**Comment by donalffons** [comment]
...one more thing: KodeGarden seems to work without errors in Edge (I tried [this example](http://kodegarden.org/#25da53357942c8c6993900a768ff74cbb016173d)]. So it seems like this is more of an Armory and maybe not so much of a Kha problem.

**Comment by luboslenco** [comment]
Heyo!

I have submitted a patch which should prevent throwing errors at random intervals: https://github.com/Kode/Kha/pull/724.

More problems:
- Edge is unable to create depth cube maps, which means no shadows for point lamps. Spot lamp and sun shadows(with cascades set to 1) should work.
- Deferred rendering presets will not work in Edge because of no support for GL_EXT_draw_buffers extensions.

An ideal fix would be Edge supporting webgl2, which has these features in core. The request for webgl2 seems to be pending for years now: https://wpdev.uservoice.com/forums/257854-microsoft-edge-developer/suggestions/6517037-webgl-2-0. :(

**Comment by donalffons** [comment]
Boom! It's already accepted and commited :).
That's great news, I'll try the patch asap. If Edge would at least work with reduced quality settings, that will be already a great step!
