### ISSUE TITLE
Doesn't work at all with addon:Render: EasyFX

### ISSUE THREAD

**Issue by echerry93** [armory3d/armory#466]
https://blenderartists.org/forum/showthread.php?385925-Addon-EasyFX-Post-Production-Done-Directly-in-the-Image-Editor    -    https://www.rymdnisse.net/download/blender-addons/easyfx/ 

While this addon is enabled, none of Armory's options are visible;  trying to disable/enable Armory with both of them enabled at startup, brings errors.

**Comment by luboslenco** [comment]
Hm, EasyFX registers a type with `bl_idname = "World"`:

```py
class WorldPanel(Panel):
    bl_category = "EasyFX"
    bl_label = "World"
    bl_idname = "World"
```

which appears to confuse Blender because it already has a `World` type. Armory then has trouble retrieving the Blender `World` object:

![capture](https://user-images.githubusercontent.com/3685704/35188302-28d07954-fe33-11e7-839d-ba179fda78c9.PNG)

Prefixing the bl_idname in EasyFX addon seems to fix the issue:
```py
    bl_idname = "easyfx.World"
```

I am not yet sure if there is a way to make Armory 'defend' against this.
