### ISSUE TITLE
Check viewport camera controls using touch

### ISSUE THREAD

**Issue by j2l** [armory3d/armory#536]
Is touch fully implemented in camera movement?
Here's what I get on Android:
https://photos.app.goo.gl/G5WfUfrCwgFko7GT2

**Comment by garyritchie** [comment]
Perhaps related: I'm exporting to html5, and while mouse input works to rotate the camera, touch does not (Nexus 5x, Chrome) using this setup:

![image](https://user-images.githubusercontent.com/853094/41042385-89a8b7bc-696f-11e8-8a3d-d44f4acac9c1.png)

Instead, the camera reacts to touch by snapping it's rotation -- as if coords was used instead of movement. Checked the source of Mouse and Surface Coords nodes but I'm a little out of my element.

**Comment by luboslenco** [comment]
Touch input should generate smooth movement coords now. Viewport camera itself does not handle zooming using multi-touch yet. Alternative - [viewport gamepad](https://github.com/armory3d/armory_examples/tree/master/virtual_gamepad).
