### ISSUE TITLE
License: Patent Protection

### ISSUE THREAD

**Issue by AndreaMonzini** [armory3d/armory#545]
Hello,
i think that Zlib and MIT license are great license but unfortunately they do not have patent protection in particular from patent trolls.

I read cases of MIT license software that are forked, patented and the patent trolls sued the users.

So i suggest to manually add Patent Protection  to the Zlib license or switch more easily to Apache License 2.0 that is a similar permissive free license but also have patent protection.
Blender "Cycles" also uses Apache License 2.0.

As Armory is growing very well i suggest to protect it also from patent trolls in some way.

**Comment by quantum-entangler** [comment]
Can you please bring examples of cases where the code was stolen and patented by third parties?

**Comment by Justinfront** [comment]
https://www.quora.com/Does-BSD-or-MIT-license-allow-someone-to-take-your-idea-and-get-a-software-patent-or-does-your-copyright-notice-prevent-it

Seems an american problem, and changing the license does not provide protection?

**Comment by quantum-entangler** [comment]
As many of the answers on that quora question point out you should be fine so long as you can prove prior art on your part.

**Comment by AndreaMonzini** [comment]
This is the discussion i have read today:

https://discourse.redox-os.org/t/mit-licence-really-suitable/92/10

**Comment by quantum-entangler** [comment]
I wouldn't mind seeing Apache license be adopted, however the issue with it could turn out to be distributing to consoles. Especially where Nintendo and Sony are concerned. They generally make a habit of not allowing for viral licensed code/binaries into their ecosystems. Apache however since its fairly contained might be an exception to this however I've yet to see/hear of an example. Then again I'm not personally particularly interested in developing for the console nor the mobile platforms so I don't keep up with it as much.

**Comment by ja-moli** [comment]
Everything I'm reading about Apache license seems fine. Any problem/objection/cons this License could have?

**Comment by ja-moli** [comment]
> AS alternative zlib + patent protection advice would be ok.

What this man said. Add to zlib some patent protection advice and we all will sleep fine.

**Comment by luboslenco** [comment]
zlib is used to align with the rest of the libraries (Kore, Kha, Krom, Iron, Armory are all zlib now) to make everything as straightforward as possible and ensure trouble-free console deploy. One problem is that modifying the license with some additions can also turn people away.:/

**Comment by ja-moli** [comment]
Sincerely hoping nobody does to you what described above. Someone fork your work, patent it, and then sue you so you can't use 'their' property anymore.

**Comment by Justinfront** [comment]
Well no, your assuming the world is America.

**Comment by ubaldy** [comment]
How is this an open issue? Scare tactics are a form of manipulation. Please close this issue.

**Comment by ja-moli** [comment]
The issue can stay opened since no forum rule has been broken.
We are not doing any 'scare tactic'. We are discussing a problem we see, to be informed if there is going to be a fix. A user who is going to use a program can ask about these kind of things.
You are very badly thought person and you deserved to be reported, for doing false accusations.

**Comment by nanjizal** [comment]
ja-moli, your github is empty, perhaps fill it and then have an opinion on how others license the stuff they decide to share? You recieved an answer from Lubos, the current licenses are very normal. I agree with ubaldy your statements are rather negative, before commenting further please put some of your work on github?

**Comment by ubaldy** [comment]
Extremely negative and non-productive thread. Opinion based and non-technical. Advising that this thread be locked similar to Stack Overflow where this very commonly happens.

@ja-moli 
I appreciate your concern, I really do. I don't recall accusing you of anything though and I do not appreciate your attack on my person.

**Comment by luboslenco** [comment]
If anyone has experience on resolving these issues please contact me directly, as this affects the whole Haxe + Kha + Armory stack, which all use MIT and Zlib.
