### ISSUE TITLE
Ubuntu Mesa drivers - main UI flickers, render screen crashes

### ISSUE THREAD

**Issue by ja-moli** [armory3d/armory#553]
Hello. AMD r9 380. Intel core i7. 4770k. 16 gig ram.
In ubuntu I'm trying Mesa drivers, who are the best graphical drivers I've ever used
for gaming.  However, it seems Armory doesn't like them.

It happened to me in Ubuntu 16.04 with Mesa 17.02
And it happens to me in Ubuntu 18.04 with Mesa 18.0.0-rc4

With AmdGpupro graphic drivers works fine in Ubuntu 16.04. (There are no Amdgpu pro for 18.04)

The user interface: Left and right panels flickers quickly in grey, alternating with the usual options.
This doesn't happen to regular Blender.

![ui](https://user-images.githubusercontent.com/12383027/37204020-f46221f4-238f-11e8-9a43-269320ba1ac5.jpg)

The Render screen: Only shows noise.
![render](https://user-images.githubusercontent.com/12383027/37204026-fef608e2-238f-11e8-8db8-77c4d4b4e2fc.jpg)

Armory v0.2 sdk was updated through addons panel. Problem remains.

**Comment by guzzard** [comment]
@luboslenco, still an issue on Ubuntu with 4.4 kernel, R9 390 card, radeon+radeonsi, mesa 17.3.3

**Comment by savuori** [comment]
Also, by default Armory attempts to use GLSL 3.30 which radeon mesa drivers don't support. Try enabling legacy shader support in Armory: User Settings -> Add-Ons -> Render: Armory -> Show Advanced -> Legacy Shaders.

Browser builds seem to work as well. Probably because webgl uses GLSL ES which is supported up to v3.1 with radeon mesa drivers.

**Comment by luboslenco** [comment]
Latest `Armory_04b_linux64` should perhaps work better.
