### ISSUE TITLE
LightMap baking, Purple everywhere

### ISSUE THREAD

**Issue by SonKim** [armory3d/armory#559]
Just trying to get bake some basic stuff a cube on a plane, it renders correct in Cycles by in Armory  0.3.0 everything is purple.  I included the entire scene and baked maps in the zip.  Could it a driver issue? I'm running a GTX 1080, windows 10 64-bit, graphics driver = 391.24.

*(optional - drag & d
[Bake Test.zip](https://github.com/armory3d/armory/files/1845148/Bake.Test.zip)
![purplerender_bakedmap](https://user-images.githubusercontent.com/7035871/37873305-eac29aac-2fce-11e8-9d65-3225ba0366b3.jpg)

rop zipped .blend file here)*

**Comment by luboslenco** [comment]
Hm, purple means armory was not able to locate/load textures. So this is most likely an issue with armory.

The bake interface still has one 'issue' which I hope to fix down the road - once the baking process finishes, you need to hit the `Apply` button manually. Due to how baking works we need to adjust the materials a little, and this `Apply` button simply puts it back and packs the lightmap textures.

I pushed a commit(https://github.com/armory3d/armory/commit/840ae450b8b3c0c744d3aca0afebc1c71b29f396) now to atleast show this notice directly in Blender:
![capture](https://user-images.githubusercontent.com/3685704/37874122-e2f6daae-3028-11e8-8003-b900aef44cca.PNG)

Let me know if the issue persist after pressing the `Apply`. I think the safest way is to start from clean project. Or maybe you already did `Apply` in the first place and the issue is something else.

Some more info:
https://github.com/armory3d/armory_examples/tree/master/material_baked

**Comment by SonKim** [comment]
Thanks, for the quick reply. I just tried baking using the material_baked scene. I get a different error this time.

![baked_error](https://user-images.githubusercontent.com/7035871/37879654-1a3f0be6-3031-11e8-8052-fb38436bd3ed.jpg)

**Comment by luboslenco** [comment]
I think the example you are using is the old one for armory 0.2. You can get the latest git examples .zip here:
https://github.com/armory3d/armory_examples/archive/master.zip

And I need to finalize 0.3 asap to end this confusion, sorry!

**Comment by SonKim** [comment]
Thanks Lubos!

I didn't know there were new version of the sample scene, the updated scene baked with no error - I think I understand the baking workflow now

**Comment by daciansolgen3** [comment]
i got ewrror when i try to bake in armory 
![namnlos](https://user-images.githubusercontent.com/26695864/50742602-4ce27200-1216-11e9-82ee-37bc489312a2.png)

can some one please help me??? i use blender 2.8
