### ISSUE TITLE
Bug On enable Armory Again / still

### ISSUE THREAD

**Issue by mushroomeo** [armory3d/armory#575]
*(optional - drag & drop zipped .blend file here)*
i just downloaded and extracted armory and tryed to enable it in addons and got same bug , so cant use it still like 0.1 version...
![armory enable bug](https://user-images.githubusercontent.com/9019563/38340088-d9d45e14-3871-11e8-8ab3-588a0dbdd41e.jpg)

**Comment by AFWSI** [comment]
I’m with lubos on this and saying there’s prolly a conflict with addons somewhere. So far, it seems your the only one running into this issue. Do you have multiple 2.79 versions? Two things I’d would try and not sure if they would solve it or not. 

1: Make a “config” folder within your Armory “2.79” folder. 
2: Disable every addon and try enabling just Armory.

If you don’t know the reason for adding the “config” folder. It’s to make sure that your settings is not crossing over from a different blender of the same version. I got multiple 2.79s on my computer and when I open one, it will say multiple missing addons. This is because I added and enabled on one 2.79 ,but not the other and it’s reading the same “config” folder from appdata for both.

**Comment by mushroomeo** [comment]
thanks very much that script solved the problem !!! : )

found out other solution and here is what i did:
found out if deleting addons in C:\Users\azuma\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons then armory started working

so i went to C:\Users\"yourusernamename"\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons and started delete addons that i have installed. after each 1 deleted addon i restarted Armory unil i saw the button "Play in Viewport" in 3D view

the addon that did conflict was : Code Autocomplete
version 2.0.0

later i reinstalled it and armory worked still.

**Comment by luboslenco** [comment]
Happy the solution was found, bookmarking this as a reference when it pops up again..
