### ISSUE TITLE
Tween node design

### ISSUE THREAD

**Issue by MadMinstrel** [armory3d/armory#603]
Here's a possible Tween node design I came up with to open the discission.

![tween_node_2](https://user-images.githubusercontent.com/2458205/39031034-4027ed66-4466-11e8-9a11-e5f9b2a83bc9.png)

this node would have an internal timer.
the Default input takes a value between 0 and 1. by default the node outputs a value between value 1 and value 2 defined by this input. this is needed to set the initial state. e.g. if value 1 = 3, value 2 = 4, and default = 0.5, the output should be 3.5

an impulse to the Forward input tweens the value over the given time period to value 2
an impulse to the Back input tweens the value over the given time period to value 1
an impulse to the Toggle input checks its current state and tweens to the other value

if an impulse happens during a tween, and that impulse reverses the direction, the node tweens from its last output, over a period proportional to the difference in the values. e.g. If the node is tweening from 0 to 1 over 1000 ms, its last output is 0.6, and a Toggle impulse comes in, it tweens from 0.6 to 0 over 600ms.

The Out impulse is sent after the tween is over.

**Comment by nanjizal** [comment]
It's too complex I have read it several times and still find it confusing and I have built simple tweens myself and used tweens extensively in comercial situations. 
Often it's good to build a whole interactions over one tween via the update parameter so you can use it to modify lots of widths of elements so that one object grows and the others reduce in size to fit, it can be costly to have lots of separate tweens with timers.
So the building block should be simple.
So you can have a start time constant and end time constant input, a timer input.  The output supplied would be from 0 - > 1, or 1 -> 0 linear accross the time ( depending on if start and end constants being positive in respect of each other ), has two other outputs, boolean started and ended.  Then you can put the linear output through a transform equation node ( lots can be supplied ) that take 0->1 and outputs 0->1 and then through a multiplier node and then can be added to a property.  Some times you want to set the final destination.  So you have a node that calculates the difference and you use that for the multiplier value.  By grouping these nodes you can build any tween and should be feasible to use one to control many properties in a transition with only one, or use inout sine and circ transforms to create nice 3d movement along a vector.

Step transform
inputs:
start: Float
end: Float
timer: Float
reset: Bool

outputs: Float ( 0 to 1 )
started: Bool
ended: Bool

But if in doubt perhaps look at language like Scratch, but the original proposal seems too complex and not flexible enough.  Example scratch found after quick google.
https://scratch.mit.edu/projects/44237598/#editor

**Comment by MoritzBrueckner** [comment]
Tween nodes are now implemented in https://github.com/armory3d/armory/pull/2336.
