### ISSUE TITLE
Physics not working

### ISSUE THREAD

**Issue by George-the-1st** [armory3d/armory#66]
Using the newest build (64-bit version) and tried to use physics....didn't go over too well. Tried changing the settings from using different shapes to different items. Applying modifiers and what not. Turning off the physics makes it work but it doesn't the other way around. It simply crashes. Associated file messaged to you on the forums.

**Comment by luboslenco** [comment]
Fixed in [new Windows build](http://forums.armory3d.org/t/build-3-is-out/104/7).

I also discovered another issue thanks to your blend, camera scale has to be set to (1.0, 1.0, 1.0) https://github.com/armory3d/armory/issues/67.
Then as I unchecked *viewport camera* option I was able to move through the maze!

**Comment by George-the-1st** [comment]
I've done the fixes and learned how to setup the camera (in certain ways) to get behavior I want. I'll start to think about adding documentation as well as the bug reports soon. Need more time studying the render engine.
