### ISSUE TITLE
KeyError: 'world_pass' or 'compositor_pass' in export_data of make.py

### ISSUE THREAD

**Issue by KUbo0** [armory3d/armory#680]
Just downloaded armory3, clicked the play, got the error:
> Traceback (most recent call last):
>   File "E:/Armory_04_win64_b27/Armory/armsdk//armory/blender\arm\props_ui.py", line 498, in execute
>   File "E:/Armory_04_win64_b27/Armory/armsdk//armory/blender\arm\make.py", line 428, in play
>   File "E:/Armory_04_win64_b27/Armory/armsdk//armory/blender\arm\make.py", line 350, in build
>   File "E:/Armory_04_win64_b27/Armory/armsdk//armory/blender\arm\make.py", line 168, in export_data
> KeyError: 'world_pass'
> 
> location: <unknown location>:-1

changed parameters - did not help
downloaded archhviz demo scene - same thing
I tried to search in the issues and on the web - unsuccessfully

changed in Armory Render Path, World from World to Clear or No clear, error:
> Traceback (most recent call last):
>   File "E:/Armory_04_win64_b27/Armory/armsdk//armory/blender\arm\props_ui.py", line 498, in execute
>   File "E:/Armory_04_win64_b27/Armory/armsdk//armory/blender\arm\make.py", line 428, in play
>   File "E:/Armory_04_win64_b27/Armory/armsdk//armory/blender\arm\make.py", line 350, in build
>   File "E:/Armory_04_win64_b27/Armory/armsdk//armory/blender\arm\make.py", line 168, in export_data
> KeyError: 'compositor_pass'
> 
> location: <unknown location>:-1

**Comment by luboslenco** [comment]
- Please post the full console output - in Blender click `Window - Toggle System Console`
- What is your Windows version?
- Where is your .blend file saved?

I guess something blocks the shader generation.

**Comment by KUbo0** [comment]
today started blender, couldn't find armory's menues; in addons tab armory was enabled, on disable I got next error message:

> Traceback (most recent call last):
>   File "E:\Armory_04_win64_b27\Armory\2.79\scripts\modules\addon_utils.py", line 398, in disable
>     mod.unregister()
>   File "E:\Armory_04_win64_b27\Armory\2.79\scripts\addons\armory.py", line 425, in unregister
>     bpy.ops.arm_addon.stop()
>   File "E:\Armory_04_win64_b27\Armory\2.79\scripts\modules\bpy\ops.py", line 189, in __call__
>     ret = op_call(self.idname_py(), None, kw)
> RuntimeError: Error: Traceback (most recent call last):
>   File "E:\Armory_04_win64_b27\Armory\2.79\scripts\addons\armory.py", line 347, in execute
>     import start
> ImportError: No module named 'start'
> 
> location: E:\Armory_04_win64_b27\Armory\2.79\scripts\modules\bpy\ops.py:189

and this was on enable:

> Traceback (most recent call last):
>   File "E:\Armory_04_win64_b27\Armory\2.79\scripts\modules\addon_utils.py", line 350, in enable
>     mod.register()
>   File "E:\Armory_04_win64_b27\Armory\2.79\scripts\addons\armory.py", line 418, in register
>     bpy.utils.register_module(__name__)
>   File "E:\Armory_04_win64_b27\Armory\2.79\scripts\modules\bpy\utils\__init__.py", line 684, in register_module
>     raise Exception("register_module(%r): defines no classes" % module)
> Exception: register_module('armory'): defines no classes

then tryed to extract Armory_04_win64_b27.7z (MD5: 8843fb73c5676bd5df8835f67e6fdf65) to other location and got 7zip (v.15.14) error; seems like archive was corrupted, but test was ok.
now I downloaded Armory_04_win64_b27.zip and successfuly extracted it. Next I extracted archviz_templates-18.03a, opened room.blend and build was Finished in 43.54649066925049, but on play got next error (short windows message translate from rus):
  

> event :	BEX64
>   application:	Krom.exe
>   ver:	0.0.0.0
>   time app:	5b1cf0af
>   module:	StackHash_67f9
>   exception offset:	0000000000000000
>   exception:	c0000005
>   exception data:	0000000000000008
>   os ver:	6.1.7601.2.1.0.256.48
>   lang code:	1049
>   add 1:	67f9
>   add 2:	67f98f32b1fa3785907c45f69e3cf543
>   add 3:	db23
>   add 4:	db23b2756780d09278777733ea08c077

  tryed c++ player runtime with no effect after build, nor browser - new tab opened but it only black

**Comment by luboslenco** [comment]
I guess this is Windows 7 then. If the test was ok then the archive should not be corrupted. Check that the anti-virus software is not deleting or blocking some files. Especially since you describe different behavior when starting it today.

Sorry I am not able to get more from this. Before going to other examples I suggest trying the empty scene only.

**Comment by KUbo0** [comment]
Thank you

**Comment by MGRed305** [comment]
hi I don't know any technical stuff but I might have had the same issue and this is how I fixed it

So after downloading the SDK and following the setup instructions in this page (https://github.com/armory3d/armory/wiki/setup) I eagerly press the updated SDK button but the update failed what I didn't notice was my important armory files changed its names form NAME ( i.e armory, iron, Kha, etc) to NAME_backup ( i.e armory_backup, iron_backup, Kha_backup, etc )

so I think that is the reason the addon malfunctioned 

and then I changed the names back and reinstalled the addon and didn't press the update button this time and tested by pressing F5 and it worked

but I could be wrong for you case cause I thought this will help you because of the very first Traceback on the very first post matched with my traceback when I had the error pop up

and in case if this didn't help and my post looks really bad I'm really sorry I'm new to this kinda stuff and still trying to figure out how the console works and other stuff I hope to improve one day
