### ISSUE TITLE
Pack assets into single file

### ISSUE THREAD

**Issue by DevMagicLord** [armory3d/armory#688]
Hi, 

Game packaging would be appreciated to get all game media inside one pack file.

**Comment by MoritzBrueckner** [comment]
Hi, since this issue came up in a [recent discussion on Discord](https://discord.com/channels/486771218599510021/487613529990365184/1084224770058489946): what problem would this feature solve? Are there any good use cases?

**Comment by tong** [comment]
The heaps engine uses *pak* for this: https://github.com/HeapsIO/heaps/tree/master/hxd/fmt/pak
Though, i am wondering too what this actually solves.

**Comment by tong** [comment]
I'am wondering too what this actually solves.
What i can think of is:
1. Make it hard for users to mess with resource files.
While this is lousy security, it would require some work to unpack/pack the files and probably enough for most of end users.
2. Better compression compared to every file compressed by itself.

If that's it would say it's not worth the work since (1) users should be able to do as they wish and (2) the compression improvement wouldn't be that great.

Btw, heaps does this too: https://github.com/HeapsIO/heaps/tree/master/hxd/fmt/pak
.. so maybe i am missing something here.
