### ISSUE TITLE
Automatic Navmesh generation

### ISSUE THREAD

**Issue by DevMagicLord** [armory3d/armory#690]
Hi,

Could Armory get automatic navmesh generation ? 
Navmesh would be generated on top of meshes tagged static.

**Comment by cumminham** [comment]
There is already something like that.. but its a hold over from BGE.
It does generate a usable mesh.
But in general from my tests the nav agent doesn't seem to account for changes in elevation... so if ur using it the environment needs to be flat. Or it will walk through the ground and on air. Which i think is due to the physics.  You have to hit the 'animated' box in rigid body physics for it to work and that seems to prevent the object from being affected by physics.
Hope that helps.

**Comment by DevMagicLord** [comment]
Armory already generate the navmesh on demand.
