### ISSUE TITLE
Texture error and obj flicker

### ISSUE THREAD

**Issue by Hazukiaoi** [armory3d/armory#734]
When  I use a texture on any model, the render will error and obj flicker
and i pack the error video and blender file.

blender version : 2.79 7c8a254
armory SDK version : 0.5
[CarGame.zip](https://github.com/armory3d/armory/files/2137888/CarGame.zip)

*(drag & drop zipped .blend file here)*

**Comment by luboslenco** [comment]
Thanks for reporting the issue. I pushed a patch https://github.com/armory3d/armory/commit/3239c985943252bcb0680d29f14d966124c090d3 and it should work now.

![capture](https://user-images.githubusercontent.com/3685704/41924825-47daffa0-796b-11e8-83cc-5f25b77cca06.PNG)

The problem was parsing the node names, hopefully fixed.

![capture2](https://user-images.githubusercontent.com/3685704/41924901-70e5dfc8-796b-11e8-9cfc-b5530a48dbbc.PNG)

**Comment by Hazukiaoi** [comment]
Yes, when i change all node name to english,it work!
