### ISSUE TITLE
Project local armory setup

### ISSUE THREAD

**Issue by sh-dave** [armory3d/armory#777]
(i'm not quite sure if this is ok in github or would be better suited for the forums, but here it goes)

I want to make a project local armory configuration and try to be independent of the globally installed sdk.
Here's what i'm thinking about what the directory layout should look like after reading the `write_data.py` script:

```
project_root
    Bundled
    Kha
    Libraries
        armory
        iron
        -
        haxebullet
        haxerecast
        hscript
        iron_format
        zui
        -
        ...
    Shaders
    Sources
    Subprojects
```

Things i'm not quite sure about when they're used or where they should live

    - armory/blender (is it even possible to use a plugin per project in blender?)
    - lib/armory_tools
    - Krom

**Comment by luboslenco** [comment]
There is a way to clone full [armsdk](https://github.com/armory3d/armsdk) and configure a path to it in the Blender user preferences. We should be able to detect whether `armsdk` is present in the local project directory and automatically pick it up.

I think that would resemble the usual Kha workflow (great for production). For command line builds the only difference would be calling `node armsdk/Kha/make` instead of `node Kha/make`. Coupled with https://github.com/armory3d/armory/issues/778 that should hopefully make projects fully portable.

**Comment by luboslenco** [comment]
Armory will now pick `project_root/armsdk` when available. Needs latest `armory.py` installed in Blender. Should be fully self contained now! https://github.com/armory3d/armory/commit/43a3ab2d6ef162208b04488fc8f6350493939ac3
