### ISSUE TITLE
GL Error 1286 invalid framebuffer operation crash on macOS

### ISSUE THREAD

**Issue by kenthinson** [armory3d/armory#839]
Getting a crash with the newest git version. I even deleted all the Armory files and reinstalled just to make sure. 

![screen shot 2018-08-21 at 5 21 01 pm](https://user-images.githubusercontent.com/2245494/44435864-eca0ab80-a566-11e8-9e44-98e60774d21e.png)

**Comment by luboslenco** [comment]
This is on macOS right? Do all scenes crash, even the default cube?

GL Error 1286 indicates `invalid framebuffer operation` along the lines of https://github.com/Kode/Kore/blob/master/Backends/Graphics4/OpenGL/Sources/Kore/OpenGL.cpp#L260. May be caused by the new windowing interface in Kha, will check!

**Comment by kenthinson** [comment]
@luboslenco yes this is OSX 10.13.6. It seems to be kind of random. :/

**Comment by luboslenco** [comment]
OpenGL now deprecated on macOS, putting focus on Metal api there.
