### ISSUE TITLE
Blender externs

### ISSUE THREAD

**Issue by luboslenco** [armory3d/armory#849]
Investigate possibility to write Armory add-on in Haxe using Blender Python externs for higher code reuse and add-on stability.

**Comment by sh-dave** [comment]
Just FYI you're not the only one: https://github.com/hamaluik/hx-blender-api 😄

**Comment by troyedwardsjr** [comment]
It also comes with the benefit of strong typing and strict compile-time type checking which Python lacks as a dynamic language, as well as makes it so you only have the change the extern functions once if the blender API changes again instead of changing every individual API call.

**Comment by mohamed36haihi** [comment]
Must wait till the blender 2.8 python api is stable and usuable

**Comment by troyedwardsjr** [comment]
@zicklag We've already done an initial conversion by compiling Blender as a Python module and then trying out several transpilers. However, I've found this method doesn't work because many properties only seem to exist at runtime without any explicit declaration. One of the potential cons of a dynamic / interpreted language.

Instead, I've opted to parse the Sphinx XML docs in order to create the externs, as those are fully typed. Which appears to being working well so far.

If anyone wants to help you can find it here: https://github.com/armory3d/blender_externs

I haven't had time to work on it lately due to being busy with dev work.

**Comment by zicklag** [comment]
Oh, great that's awesome! So you're able to generate Haxe externs from the Blender API automatically? I'll have to test that out.

**Comment by luboslenco** [comment]
@zicklag Sounds good, could be a nice start. If you want to keep it safe then maybe just give it a few more weeks till we jump onto b2.8 beta. 🙂

**Comment by zicklag** [comment]
Sounds like a good idea. I'm not sure I'll get the time for it, but if I did I wanted to make sure that it made any sense. :slightly_smiling_face:

**Comment by zicklag** [comment]
I've almost finished the blender extern generator! I'll be submitting a PR for it very soon. It is based on the Sphinx XML documentation like @troyedwardsjr started to do and it looks like it is working very well.

**Comment by zicklag** [comment]
I've got my current WIP code and externs in [katharostech/blender_externs@blender2.8](https://github.com/katharostech/blender_externs/tree/blender2.8) if anybody wants to test/review. There are still a few issues, like with functions in the API named `new` and classes missing constructors, but for the most part it is doing well.

**Comment by zicklag** [comment]
Got a potentially useful [reply](https://community.haxe.org/t/difficulties-getting-haxe-to-compile-to-a-blender-plugin/1380/3?u=zicklag) to my forum topic a while ago on the issues that I had while attempting this. I'm putting this on the back burner for now, but that would be good to look into if we pick this up again.

**Comment by luboslenco** [comment]
Putting this one on hold for now to focus on other issues.
