### ISSUE TITLE
Autobuild and Livepatching

### ISSUE THREAD

**Issue by George-the-1st** [armory3d/armory#95]
These two settings, and possibly more, have poor descriptions that don't give you information on what that they actually do.

**Comment by luboslenco** [comment]
Tracking this globally as 'Minimal docs out of the box.' issue mentioned in manual home page as one of the major preview limitations. (otherwise we could open 30 issues like this and get this section out of control).

**Comment by George-the-1st** [comment]
pardon but I'm not getting what you mean by this. Explain?

**Comment by luboslenco** [comment]
Just meant that I am aware of it but most of the settings have sucky descriptions, so I am tracking it 'together':)

If you are curious about Live-Patching and Auto-Build specifically:
- Live-Patching is meant to enable live synchronization with built-in player, ie mirror scene changes done in viewport/editors
- Auto-Build is meant to enable mirroring of these changes automatically, otherwise you have to manually press the build button

**Comment by George-the-1st** [comment]
Great thanks. On the topic of documents, are you planning on accepting and rejecting edits as they are made or are you just going to wait for the official build. I'm willing to keep up with the changes that are made but if you aren't willing to accept them then I might as well not bother. It is, of course, up to you. Just tell me so I don't end up spending time updating docs when I could be doing something else if the effort will be in vain.
