### ISSUE TITLE
flutter  dart support

### ISSUE THREAD

**Issue by AttSee** [armory3d/armory#978]
Flutter it gives access to native Android and iOS UI components which makes it far better than Flutter
Flutter aims to provide 60 frames per second (fps) performance, or 120 fps performance on devices capable of 120Hz updates

It is also possible to build applications for the desktop I did not try that
https://github.com/google/flutter-desktop-embedding
Also
I think will be adding good(dart & Flutter )

**Comment by nanjizal** [comment]
It is viable to use native components within Haxe without requiring Flutter.  
Obviously Kha and Armory3D are designed to use a 'GL' window so native aspects will need to be around, next to, or on top, but not actually in.
Currently there is not much information or up to date libraries on native component integration with Haxe but there is work ongoing on this front. It is likely to produce clean and light solutions, so really no need to tie yourself to Flutter.
Places to look for more details: Basis, HaxeUI, NME.
I think it's beyond scope to provide Flutter support and any native component support would be much cleaner using Haxe c++/Java/obj-c/HashLink directly and avoid any bloat that Flutter will likely incur.  I have not provided specific links because I am unsure on the best ones but check twitter.

**Comment by AttSee** [comment]
good ..
armory performance is better than unity  and godot ? I love it

**Comment by AttSee** [comment]
we can get some inspiration from Flutter is its Android export workflow, it's great.

**Comment by luboslenco** [comment]
Thanks for the link, will keep an eye on it to improve our workflow.
